/*
Compliance Provider API

REST API for implementations of custom Compliance Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package legacy

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomAttributeV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomAttributeV2{}

// CustomAttributeV2 Custom attribute allows to store and transfer dynamic data. Its content can be edited and send in requests to store.
type CustomAttributeV2 struct {
	// UUID of the Attribute for unique identification
	Uuid string `json:"uuid"`
	// Name of the Attribute that is used for identification
	Name string `json:"name"`
	// Optional description of the Attribute, should contain helper text on what is expected
	Description *string `json:"description,omitempty"`
	// Version of the attribute
	Version int32 `json:"version"`
	// Type of the Attribute
	Type AttributeType `json:"type"`
	// Content of the Attribute
	Content []BaseAttributeContentDtoV2 `json:"content,omitempty"`
	// Type of the Content
	ContentType AttributeContentType `json:"contentType"`
	// Properties of the Attributes
	Properties CustomAttributeProperties `json:"properties"`
}

type _CustomAttributeV2 CustomAttributeV2

// NewCustomAttributeV2 instantiates a new CustomAttributeV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomAttributeV2(uuid string, name string, version int32, type_ AttributeType, contentType AttributeContentType, properties CustomAttributeProperties) *CustomAttributeV2 {
	this := CustomAttributeV2{}
	this.Uuid = uuid
	this.Name = name
	this.Version = version
	this.Type = type_
	this.ContentType = contentType
	this.Properties = properties
	return &this
}

// NewCustomAttributeV2WithDefaults instantiates a new CustomAttributeV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomAttributeV2WithDefaults() *CustomAttributeV2 {
	this := CustomAttributeV2{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *CustomAttributeV2) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *CustomAttributeV2) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *CustomAttributeV2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomAttributeV2) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustomAttributeV2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustomAttributeV2) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustomAttributeV2) SetDescription(v string) {
	o.Description = &v
}

// GetVersion returns the Version field value
func (o *CustomAttributeV2) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CustomAttributeV2) SetVersion(v int32) {
	o.Version = v
}

// GetType returns the Type field value
func (o *CustomAttributeV2) GetType() AttributeType {
	if o == nil {
		var ret AttributeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetTypeOk() (*AttributeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CustomAttributeV2) SetType(v AttributeType) {
	o.Type = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *CustomAttributeV2) GetContent() []BaseAttributeContentDtoV2 {
	if o == nil || IsNil(o.Content) {
		var ret []BaseAttributeContentDtoV2
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetContentOk() ([]BaseAttributeContentDtoV2, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *CustomAttributeV2) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []BaseAttributeContentDtoV2 and assigns it to the Content field.
func (o *CustomAttributeV2) SetContent(v []BaseAttributeContentDtoV2) {
	o.Content = v
}

// GetContentType returns the ContentType field value
func (o *CustomAttributeV2) GetContentType() AttributeContentType {
	if o == nil {
		var ret AttributeContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetContentTypeOk() (*AttributeContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *CustomAttributeV2) SetContentType(v AttributeContentType) {
	o.ContentType = v
}

// GetProperties returns the Properties field value
func (o *CustomAttributeV2) GetProperties() CustomAttributeProperties {
	if o == nil {
		var ret CustomAttributeProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeV2) GetPropertiesOk() (*CustomAttributeProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *CustomAttributeV2) SetProperties(v CustomAttributeProperties) {
	o.Properties = v
}

func (o CustomAttributeV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomAttributeV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["version"] = o.Version
	toSerialize["type"] = o.Type
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	toSerialize["contentType"] = o.ContentType
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *CustomAttributeV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"version",
		"type",
		"contentType",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomAttributeV2 := _CustomAttributeV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomAttributeV2)

	if err != nil {
		return err
	}

	*o = CustomAttributeV2(varCustomAttributeV2)

	return err
}

type NullableCustomAttributeV2 struct {
	value *CustomAttributeV2
	isSet bool
}

func (v NullableCustomAttributeV2) Get() *CustomAttributeV2 {
	return v.value
}

func (v *NullableCustomAttributeV2) Set(val *CustomAttributeV2) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomAttributeV2) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomAttributeV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomAttributeV2(val *CustomAttributeV2) *NullableCustomAttributeV2 {
	return &NullableCustomAttributeV2{value: val, isSet: true}
}

func (v NullableCustomAttributeV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomAttributeV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


