/*
Secret Provider API

REST API for implementations of custom Secret Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// BaseAttributeContentDtoV3 - Base Attribute Content
type BaseAttributeContentDtoV3 struct {
	BooleanAttributeContentV3 *BooleanAttributeContentV3
	CodeBlockAttributeContentV3 *CodeBlockAttributeContentV3
	DateAttributeContentV3 *DateAttributeContentV3
	DateTimeAttributeContentV3 *DateTimeAttributeContentV3
	FileAttributeContentV3 *FileAttributeContentV3
	FloatAttributeContentV3 *FloatAttributeContentV3
	IntegerAttributeContentV3 *IntegerAttributeContentV3
	ObjectAttributeContentV3 *ObjectAttributeContentV3
	ResourceObjectContent *ResourceObjectContent
	StringAttributeContentV3 *StringAttributeContentV3
	TextAttributeContentV3 *TextAttributeContentV3
	TimeAttributeContentV3 *TimeAttributeContentV3
}

// BooleanAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns BooleanAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func BooleanAttributeContentV3AsBaseAttributeContentDtoV3(v *BooleanAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		BooleanAttributeContentV3: v,
	}
}

// CodeBlockAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns CodeBlockAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func CodeBlockAttributeContentV3AsBaseAttributeContentDtoV3(v *CodeBlockAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		CodeBlockAttributeContentV3: v,
	}
}

// DateAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns DateAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func DateAttributeContentV3AsBaseAttributeContentDtoV3(v *DateAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		DateAttributeContentV3: v,
	}
}

// DateTimeAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns DateTimeAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func DateTimeAttributeContentV3AsBaseAttributeContentDtoV3(v *DateTimeAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		DateTimeAttributeContentV3: v,
	}
}

// FileAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns FileAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func FileAttributeContentV3AsBaseAttributeContentDtoV3(v *FileAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		FileAttributeContentV3: v,
	}
}

// FloatAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns FloatAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func FloatAttributeContentV3AsBaseAttributeContentDtoV3(v *FloatAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		FloatAttributeContentV3: v,
	}
}

// IntegerAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns IntegerAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func IntegerAttributeContentV3AsBaseAttributeContentDtoV3(v *IntegerAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		IntegerAttributeContentV3: v,
	}
}

// ObjectAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns ObjectAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func ObjectAttributeContentV3AsBaseAttributeContentDtoV3(v *ObjectAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		ObjectAttributeContentV3: v,
	}
}

// ResourceObjectContentAsBaseAttributeContentDtoV3 is a convenience function that returns ResourceObjectContent wrapped in BaseAttributeContentDtoV3
func ResourceObjectContentAsBaseAttributeContentDtoV3(v *ResourceObjectContent) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		ResourceObjectContent: v,
	}
}

// StringAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns StringAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func StringAttributeContentV3AsBaseAttributeContentDtoV3(v *StringAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		StringAttributeContentV3: v,
	}
}

// TextAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns TextAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func TextAttributeContentV3AsBaseAttributeContentDtoV3(v *TextAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		TextAttributeContentV3: v,
	}
}

// TimeAttributeContentV3AsBaseAttributeContentDtoV3 is a convenience function that returns TimeAttributeContentV3 wrapped in BaseAttributeContentDtoV3
func TimeAttributeContentV3AsBaseAttributeContentDtoV3(v *TimeAttributeContentV3) BaseAttributeContentDtoV3 {
	return BaseAttributeContentDtoV3{
		TimeAttributeContentV3: v,
	}
}


// UnmarshalJSON decodes BaseAttributeContentDtoV3 by switching on the JSON "contentType" field.
// Patched by tools/fixoneof — the generator's match-counting decoder
// fails on this oneOf because multiple variants share the same Go struct
// shape and pass strict decode simultaneously.
func (dst *BaseAttributeContentDtoV3) UnmarshalJSON(data []byte) error {
	var probe struct {
		Disc string `json:"contentType"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("BaseAttributeContentDtoV3: probe contentType: %w", err)
	}
	dst.BooleanAttributeContentV3 = nil
	dst.CodeBlockAttributeContentV3 = nil
	dst.DateAttributeContentV3 = nil
	dst.DateTimeAttributeContentV3 = nil
	dst.FileAttributeContentV3 = nil
	dst.FloatAttributeContentV3 = nil
	dst.IntegerAttributeContentV3 = nil
	dst.ObjectAttributeContentV3 = nil
	dst.ResourceObjectContent = nil
	dst.StringAttributeContentV3 = nil
	dst.TextAttributeContentV3 = nil
	dst.TimeAttributeContentV3 = nil
	switch probe.Disc {
	case "boolean":
		var v BooleanAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode BooleanAttributeContentV3: %w", err)
		}
		dst.BooleanAttributeContentV3 = &v
		return nil
	case "codeblock":
		var v CodeBlockAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode CodeBlockAttributeContentV3: %w", err)
		}
		dst.CodeBlockAttributeContentV3 = &v
		return nil
	case "date":
		var v DateAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode DateAttributeContentV3: %w", err)
		}
		dst.DateAttributeContentV3 = &v
		return nil
	case "datetime":
		var v DateTimeAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode DateTimeAttributeContentV3: %w", err)
		}
		dst.DateTimeAttributeContentV3 = &v
		return nil
	case "file":
		var v FileAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode FileAttributeContentV3: %w", err)
		}
		dst.FileAttributeContentV3 = &v
		return nil
	case "float":
		var v FloatAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode FloatAttributeContentV3: %w", err)
		}
		dst.FloatAttributeContentV3 = &v
		return nil
	case "integer":
		var v IntegerAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode IntegerAttributeContentV3: %w", err)
		}
		dst.IntegerAttributeContentV3 = &v
		return nil
	case "object":
		var v ObjectAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode ObjectAttributeContentV3: %w", err)
		}
		dst.ObjectAttributeContentV3 = &v
		return nil
	case "resource":
		var v ResourceObjectContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode ResourceObjectContent: %w", err)
		}
		dst.ResourceObjectContent = &v
		return nil
	case "string":
		var v StringAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode StringAttributeContentV3: %w", err)
		}
		dst.StringAttributeContentV3 = &v
		return nil
	case "text":
		var v TextAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode TextAttributeContentV3: %w", err)
		}
		dst.TextAttributeContentV3 = &v
		return nil
	case "time":
		var v TimeAttributeContentV3
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("BaseAttributeContentDtoV3: decode TimeAttributeContentV3: %w", err)
		}
		dst.TimeAttributeContentV3 = &v
		return nil
	default:
		return fmt.Errorf("BaseAttributeContentDtoV3: unknown contentType %q", probe.Disc)
	}
}




// Marshal data from the first non-nil pointers in the struct to JSON
func (src BaseAttributeContentDtoV3) MarshalJSON() ([]byte, error) {
	if src.BooleanAttributeContentV3 != nil {
		return json.Marshal(&src.BooleanAttributeContentV3)
	}

	if src.CodeBlockAttributeContentV3 != nil {
		return json.Marshal(&src.CodeBlockAttributeContentV3)
	}

	if src.DateAttributeContentV3 != nil {
		return json.Marshal(&src.DateAttributeContentV3)
	}

	if src.DateTimeAttributeContentV3 != nil {
		return json.Marshal(&src.DateTimeAttributeContentV3)
	}

	if src.FileAttributeContentV3 != nil {
		return json.Marshal(&src.FileAttributeContentV3)
	}

	if src.FloatAttributeContentV3 != nil {
		return json.Marshal(&src.FloatAttributeContentV3)
	}

	if src.IntegerAttributeContentV3 != nil {
		return json.Marshal(&src.IntegerAttributeContentV3)
	}

	if src.ObjectAttributeContentV3 != nil {
		return json.Marshal(&src.ObjectAttributeContentV3)
	}

	if src.ResourceObjectContent != nil {
		return json.Marshal(&src.ResourceObjectContent)
	}

	if src.StringAttributeContentV3 != nil {
		return json.Marshal(&src.StringAttributeContentV3)
	}

	if src.TextAttributeContentV3 != nil {
		return json.Marshal(&src.TextAttributeContentV3)
	}

	if src.TimeAttributeContentV3 != nil {
		return json.Marshal(&src.TimeAttributeContentV3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BaseAttributeContentDtoV3) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BooleanAttributeContentV3 != nil {
		return obj.BooleanAttributeContentV3
	}

	if obj.CodeBlockAttributeContentV3 != nil {
		return obj.CodeBlockAttributeContentV3
	}

	if obj.DateAttributeContentV3 != nil {
		return obj.DateAttributeContentV3
	}

	if obj.DateTimeAttributeContentV3 != nil {
		return obj.DateTimeAttributeContentV3
	}

	if obj.FileAttributeContentV3 != nil {
		return obj.FileAttributeContentV3
	}

	if obj.FloatAttributeContentV3 != nil {
		return obj.FloatAttributeContentV3
	}

	if obj.IntegerAttributeContentV3 != nil {
		return obj.IntegerAttributeContentV3
	}

	if obj.ObjectAttributeContentV3 != nil {
		return obj.ObjectAttributeContentV3
	}

	if obj.ResourceObjectContent != nil {
		return obj.ResourceObjectContent
	}

	if obj.StringAttributeContentV3 != nil {
		return obj.StringAttributeContentV3
	}

	if obj.TextAttributeContentV3 != nil {
		return obj.TextAttributeContentV3
	}

	if obj.TimeAttributeContentV3 != nil {
		return obj.TimeAttributeContentV3
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BaseAttributeContentDtoV3) GetActualInstanceValue() (interface{}) {
	if obj.BooleanAttributeContentV3 != nil {
		return *obj.BooleanAttributeContentV3
	}

	if obj.CodeBlockAttributeContentV3 != nil {
		return *obj.CodeBlockAttributeContentV3
	}

	if obj.DateAttributeContentV3 != nil {
		return *obj.DateAttributeContentV3
	}

	if obj.DateTimeAttributeContentV3 != nil {
		return *obj.DateTimeAttributeContentV3
	}

	if obj.FileAttributeContentV3 != nil {
		return *obj.FileAttributeContentV3
	}

	if obj.FloatAttributeContentV3 != nil {
		return *obj.FloatAttributeContentV3
	}

	if obj.IntegerAttributeContentV3 != nil {
		return *obj.IntegerAttributeContentV3
	}

	if obj.ObjectAttributeContentV3 != nil {
		return *obj.ObjectAttributeContentV3
	}

	if obj.ResourceObjectContent != nil {
		return *obj.ResourceObjectContent
	}

	if obj.StringAttributeContentV3 != nil {
		return *obj.StringAttributeContentV3
	}

	if obj.TextAttributeContentV3 != nil {
		return *obj.TextAttributeContentV3
	}

	if obj.TimeAttributeContentV3 != nil {
		return *obj.TimeAttributeContentV3
	}

	// all schemas are nil
	return nil
}

type NullableBaseAttributeContentDtoV3 struct {
	value *BaseAttributeContentDtoV3
	isSet bool
}

func (v NullableBaseAttributeContentDtoV3) Get() *BaseAttributeContentDtoV3 {
	return v.value
}

func (v *NullableBaseAttributeContentDtoV3) Set(val *BaseAttributeContentDtoV3) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseAttributeContentDtoV3) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseAttributeContentDtoV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseAttributeContentDtoV3(val *BaseAttributeContentDtoV3) *NullableBaseAttributeContentDtoV3 {
	return &NullableBaseAttributeContentDtoV3{value: val, isSet: true}
}

func (v NullableBaseAttributeContentDtoV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseAttributeContentDtoV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


