/*
Notification Provider API

REST API for implementations of custom Notification Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the NotificationAttributeDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationAttributeDto{}

// NotificationAttributeDto Attribute values prepared for notification templates: plain scalar values or reference strings only, decoupled from internal attribute content versioning
type NotificationAttributeDto struct {
	// Attribute name
	Name string `json:"name"`
	// Human-readable attribute label
	Label string `json:"label"`
	// Attribute content type
	ContentType AttributeContentType `json:"contentType"`
	// Extracted values; scalar types carry raw data, complex types carry the human-readable reference string
	Values []interface{} `json:"values"`
	// Metadata only: aggregate set of source objects that contributed any value to this attribute. NOT positionally paired with values — values are deduplicated independently of source accumulation
	SourceObjects []NameAndUuidDto `json:"sourceObjects,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NotificationAttributeDto NotificationAttributeDto

// NewNotificationAttributeDto instantiates a new NotificationAttributeDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationAttributeDto(name string, label string, contentType AttributeContentType, values []interface{}) *NotificationAttributeDto {
	this := NotificationAttributeDto{}
	this.Name = name
	this.Label = label
	this.ContentType = contentType
	this.Values = values
	return &this
}

// NewNotificationAttributeDtoWithDefaults instantiates a new NotificationAttributeDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationAttributeDtoWithDefaults() *NotificationAttributeDto {
	this := NotificationAttributeDto{}
	return &this
}

// GetName returns the Name field value
func (o *NotificationAttributeDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NotificationAttributeDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NotificationAttributeDto) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *NotificationAttributeDto) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *NotificationAttributeDto) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *NotificationAttributeDto) SetLabel(v string) {
	o.Label = v
}

// GetContentType returns the ContentType field value
func (o *NotificationAttributeDto) GetContentType() AttributeContentType {
	if o == nil {
		var ret AttributeContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *NotificationAttributeDto) GetContentTypeOk() (*AttributeContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *NotificationAttributeDto) SetContentType(v AttributeContentType) {
	o.ContentType = v
}

// GetValues returns the Values field value
func (o *NotificationAttributeDto) GetValues() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *NotificationAttributeDto) GetValuesOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *NotificationAttributeDto) SetValues(v []interface{}) {
	o.Values = v
}

// GetSourceObjects returns the SourceObjects field value if set, zero value otherwise.
func (o *NotificationAttributeDto) GetSourceObjects() []NameAndUuidDto {
	if o == nil || IsNil(o.SourceObjects) {
		var ret []NameAndUuidDto
		return ret
	}
	return o.SourceObjects
}

// GetSourceObjectsOk returns a tuple with the SourceObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationAttributeDto) GetSourceObjectsOk() ([]NameAndUuidDto, bool) {
	if o == nil || IsNil(o.SourceObjects) {
		return nil, false
	}
	return o.SourceObjects, true
}

// HasSourceObjects returns a boolean if a field has been set.
func (o *NotificationAttributeDto) HasSourceObjects() bool {
	if o != nil && !IsNil(o.SourceObjects) {
		return true
	}

	return false
}

// SetSourceObjects gets a reference to the given []NameAndUuidDto and assigns it to the SourceObjects field.
func (o *NotificationAttributeDto) SetSourceObjects(v []NameAndUuidDto) {
	o.SourceObjects = v
}

func (o NotificationAttributeDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationAttributeDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["label"] = o.Label
	toSerialize["contentType"] = o.ContentType
	toSerialize["values"] = o.Values
	if !IsNil(o.SourceObjects) {
		toSerialize["sourceObjects"] = o.SourceObjects
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotificationAttributeDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"label",
		"contentType",
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationAttributeDto := _NotificationAttributeDto{}

	err = json.Unmarshal(data, &varNotificationAttributeDto)

	if err != nil {
		return err
	}

	*o = NotificationAttributeDto(varNotificationAttributeDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "label")
		delete(additionalProperties, "contentType")
		delete(additionalProperties, "values")
		delete(additionalProperties, "sourceObjects")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotificationAttributeDto struct {
	value *NotificationAttributeDto
	isSet bool
}

func (v NullableNotificationAttributeDto) Get() *NotificationAttributeDto {
	return v.value
}

func (v *NullableNotificationAttributeDto) Set(val *NotificationAttributeDto) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationAttributeDto) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationAttributeDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationAttributeDto(val *NotificationAttributeDto) *NullableNotificationAttributeDto {
	return &NullableNotificationAttributeDto{value: val, isSet: true}
}

func (v NullableNotificationAttributeDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationAttributeDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


