/*
Notification Provider API

REST API for implementations of custom Notification Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the NotificationEventObjectDataDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationEventObjectDataDto{}

// NotificationEventObjectDataDto Object data enabled on the notification profile, describing the event's subject object. Best-effort: categories the subject does not support, that are disabled, or that failed to load are absent
type NotificationEventObjectDataDto struct {
	// The object this data describes: the event object, or for approval events the approval's target object
	Subject NotificationAssociationDto `json:"subject"`
	// The subject's custom attributes keyed by attribute name
	CustomAttributes map[string]NotificationAttributeDto `json:"customAttributes,omitempty"`
	// The subject's connector-sourced metadata, grouped by connector and source object type
	Metadata []NotificationMetadataGroupDto `json:"metadata,omitempty"`
	// The subject's associated objects: owner, groups, RA profile
	Associations []NotificationAssociationDto `json:"associations,omitempty"`
	// The subject's content representation when its resource type provides one
	Content *NotificationObjectContentDto `json:"content,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NotificationEventObjectDataDto NotificationEventObjectDataDto

// NewNotificationEventObjectDataDto instantiates a new NotificationEventObjectDataDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationEventObjectDataDto(subject NotificationAssociationDto) *NotificationEventObjectDataDto {
	this := NotificationEventObjectDataDto{}
	this.Subject = subject
	return &this
}

// NewNotificationEventObjectDataDtoWithDefaults instantiates a new NotificationEventObjectDataDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationEventObjectDataDtoWithDefaults() *NotificationEventObjectDataDto {
	this := NotificationEventObjectDataDto{}
	return &this
}

// GetSubject returns the Subject field value
func (o *NotificationEventObjectDataDto) GetSubject() NotificationAssociationDto {
	if o == nil {
		var ret NotificationAssociationDto
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *NotificationEventObjectDataDto) GetSubjectOk() (*NotificationAssociationDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *NotificationEventObjectDataDto) SetSubject(v NotificationAssociationDto) {
	o.Subject = v
}

// GetCustomAttributes returns the CustomAttributes field value if set, zero value otherwise.
func (o *NotificationEventObjectDataDto) GetCustomAttributes() map[string]NotificationAttributeDto {
	if o == nil || IsNil(o.CustomAttributes) {
		var ret map[string]NotificationAttributeDto
		return ret
	}
	return o.CustomAttributes
}

// GetCustomAttributesOk returns a tuple with the CustomAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationEventObjectDataDto) GetCustomAttributesOk() (map[string]NotificationAttributeDto, bool) {
	if o == nil || IsNil(o.CustomAttributes) {
		return map[string]NotificationAttributeDto{}, false
	}
	return o.CustomAttributes, true
}

// HasCustomAttributes returns a boolean if a field has been set.
func (o *NotificationEventObjectDataDto) HasCustomAttributes() bool {
	if o != nil && !IsNil(o.CustomAttributes) {
		return true
	}

	return false
}

// SetCustomAttributes gets a reference to the given map[string]NotificationAttributeDto and assigns it to the CustomAttributes field.
func (o *NotificationEventObjectDataDto) SetCustomAttributes(v map[string]NotificationAttributeDto) {
	o.CustomAttributes = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *NotificationEventObjectDataDto) GetMetadata() []NotificationMetadataGroupDto {
	if o == nil || IsNil(o.Metadata) {
		var ret []NotificationMetadataGroupDto
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationEventObjectDataDto) GetMetadataOk() ([]NotificationMetadataGroupDto, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *NotificationEventObjectDataDto) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []NotificationMetadataGroupDto and assigns it to the Metadata field.
func (o *NotificationEventObjectDataDto) SetMetadata(v []NotificationMetadataGroupDto) {
	o.Metadata = v
}

// GetAssociations returns the Associations field value if set, zero value otherwise.
func (o *NotificationEventObjectDataDto) GetAssociations() []NotificationAssociationDto {
	if o == nil || IsNil(o.Associations) {
		var ret []NotificationAssociationDto
		return ret
	}
	return o.Associations
}

// GetAssociationsOk returns a tuple with the Associations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationEventObjectDataDto) GetAssociationsOk() ([]NotificationAssociationDto, bool) {
	if o == nil || IsNil(o.Associations) {
		return nil, false
	}
	return o.Associations, true
}

// HasAssociations returns a boolean if a field has been set.
func (o *NotificationEventObjectDataDto) HasAssociations() bool {
	if o != nil && !IsNil(o.Associations) {
		return true
	}

	return false
}

// SetAssociations gets a reference to the given []NotificationAssociationDto and assigns it to the Associations field.
func (o *NotificationEventObjectDataDto) SetAssociations(v []NotificationAssociationDto) {
	o.Associations = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *NotificationEventObjectDataDto) GetContent() NotificationObjectContentDto {
	if o == nil || IsNil(o.Content) {
		var ret NotificationObjectContentDto
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationEventObjectDataDto) GetContentOk() (*NotificationObjectContentDto, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *NotificationEventObjectDataDto) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given NotificationObjectContentDto and assigns it to the Content field.
func (o *NotificationEventObjectDataDto) SetContent(v NotificationObjectContentDto) {
	o.Content = &v
}

func (o NotificationEventObjectDataDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationEventObjectDataDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject"] = o.Subject
	if !IsNil(o.CustomAttributes) {
		toSerialize["customAttributes"] = o.CustomAttributes
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Associations) {
		toSerialize["associations"] = o.Associations
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotificationEventObjectDataDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationEventObjectDataDto := _NotificationEventObjectDataDto{}

	err = json.Unmarshal(data, &varNotificationEventObjectDataDto)

	if err != nil {
		return err
	}

	*o = NotificationEventObjectDataDto(varNotificationEventObjectDataDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subject")
		delete(additionalProperties, "customAttributes")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "associations")
		delete(additionalProperties, "content")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotificationEventObjectDataDto struct {
	value *NotificationEventObjectDataDto
	isSet bool
}

func (v NullableNotificationEventObjectDataDto) Get() *NotificationEventObjectDataDto {
	return v.value
}

func (v *NullableNotificationEventObjectDataDto) Set(val *NotificationEventObjectDataDto) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationEventObjectDataDto) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationEventObjectDataDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationEventObjectDataDto(val *NotificationEventObjectDataDto) *NullableNotificationEventObjectDataDto {
	return &NullableNotificationEventObjectDataDto{value: val, isSet: true}
}

func (v NullableNotificationEventObjectDataDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationEventObjectDataDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


