/*
Authority Provider Legacy API

REST API for implementations of custom Legacy Authority Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the CertRevocationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertRevocationDto{}

// CertRevocationDto struct for CertRevocationDto
type CertRevocationDto struct {
	// Certificate serial number
	CertificateSN string `json:"certificateSN"`
	// Issuer domain name
	IssuerDN string `json:"issuerDN"`
	// Revocation reason
	Reason CertificateRevocationReason `json:"reason"`
	AdditionalProperties map[string]interface{}
}

type _CertRevocationDto CertRevocationDto

// NewCertRevocationDto instantiates a new CertRevocationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertRevocationDto(certificateSN string, issuerDN string, reason CertificateRevocationReason) *CertRevocationDto {
	this := CertRevocationDto{}
	this.CertificateSN = certificateSN
	this.IssuerDN = issuerDN
	this.Reason = reason
	return &this
}

// NewCertRevocationDtoWithDefaults instantiates a new CertRevocationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertRevocationDtoWithDefaults() *CertRevocationDto {
	this := CertRevocationDto{}
	return &this
}

// GetCertificateSN returns the CertificateSN field value
func (o *CertRevocationDto) GetCertificateSN() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CertificateSN
}

// GetCertificateSNOk returns a tuple with the CertificateSN field value
// and a boolean to check if the value has been set.
func (o *CertRevocationDto) GetCertificateSNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertificateSN, true
}

// SetCertificateSN sets field value
func (o *CertRevocationDto) SetCertificateSN(v string) {
	o.CertificateSN = v
}

// GetIssuerDN returns the IssuerDN field value
func (o *CertRevocationDto) GetIssuerDN() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuerDN
}

// GetIssuerDNOk returns a tuple with the IssuerDN field value
// and a boolean to check if the value has been set.
func (o *CertRevocationDto) GetIssuerDNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerDN, true
}

// SetIssuerDN sets field value
func (o *CertRevocationDto) SetIssuerDN(v string) {
	o.IssuerDN = v
}

// GetReason returns the Reason field value
func (o *CertRevocationDto) GetReason() CertificateRevocationReason {
	if o == nil {
		var ret CertificateRevocationReason
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CertRevocationDto) GetReasonOk() (*CertificateRevocationReason, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CertRevocationDto) SetReason(v CertificateRevocationReason) {
	o.Reason = v
}

func (o CertRevocationDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertRevocationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certificateSN"] = o.CertificateSN
	toSerialize["issuerDN"] = o.IssuerDN
	toSerialize["reason"] = o.Reason

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CertRevocationDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certificateSN",
		"issuerDN",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertRevocationDto := _CertRevocationDto{}

	err = json.Unmarshal(data, &varCertRevocationDto)

	if err != nil {
		return err
	}

	*o = CertRevocationDto(varCertRevocationDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "certificateSN")
		delete(additionalProperties, "issuerDN")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCertRevocationDto struct {
	value *CertRevocationDto
	isSet bool
}

func (v NullableCertRevocationDto) Get() *CertRevocationDto {
	return v.value
}

func (v *NullableCertRevocationDto) Set(val *CertRevocationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCertRevocationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCertRevocationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertRevocationDto(val *CertRevocationDto) *NullableCertRevocationDto {
	return &NullableCertRevocationDto{value: val, isSet: true}
}

func (v NullableCertRevocationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertRevocationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


