/*
Compliance Provider API

REST API for implementations of custom Compliance Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// BaseAttributeContentDtoV2 - Base Attribute ContentV2 definition
type BaseAttributeContentDtoV2 struct {
	BooleanAttributeContentV2 *BooleanAttributeContentV2
	CodeBlockAttributeContentV2 *CodeBlockAttributeContentV2
	CredentialAttributeContentV2 *CredentialAttributeContentV2
	DateAttributeContentV2 *DateAttributeContentV2
	DateTimeAttributeContentV2 *DateTimeAttributeContentV2
	FileAttributeContentV2 *FileAttributeContentV2
	FloatAttributeContentV2 *FloatAttributeContentV2
	IntegerAttributeContentV2 *IntegerAttributeContentV2
	ObjectAttributeContentV2 *ObjectAttributeContentV2
	SecretAttributeContentV2 *SecretAttributeContentV2
	StringAttributeContentV2 *StringAttributeContentV2
	TextAttributeContentV2 *TextAttributeContentV2
	TimeAttributeContentV2 *TimeAttributeContentV2
}

// BooleanAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns BooleanAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func BooleanAttributeContentV2AsBaseAttributeContentDtoV2(v *BooleanAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		BooleanAttributeContentV2: v,
	}
}

// CodeBlockAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns CodeBlockAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func CodeBlockAttributeContentV2AsBaseAttributeContentDtoV2(v *CodeBlockAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		CodeBlockAttributeContentV2: v,
	}
}

// CredentialAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns CredentialAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func CredentialAttributeContentV2AsBaseAttributeContentDtoV2(v *CredentialAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		CredentialAttributeContentV2: v,
	}
}

// DateAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns DateAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func DateAttributeContentV2AsBaseAttributeContentDtoV2(v *DateAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		DateAttributeContentV2: v,
	}
}

// DateTimeAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns DateTimeAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func DateTimeAttributeContentV2AsBaseAttributeContentDtoV2(v *DateTimeAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		DateTimeAttributeContentV2: v,
	}
}

// FileAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns FileAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func FileAttributeContentV2AsBaseAttributeContentDtoV2(v *FileAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		FileAttributeContentV2: v,
	}
}

// FloatAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns FloatAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func FloatAttributeContentV2AsBaseAttributeContentDtoV2(v *FloatAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		FloatAttributeContentV2: v,
	}
}

// IntegerAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns IntegerAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func IntegerAttributeContentV2AsBaseAttributeContentDtoV2(v *IntegerAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		IntegerAttributeContentV2: v,
	}
}

// ObjectAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns ObjectAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func ObjectAttributeContentV2AsBaseAttributeContentDtoV2(v *ObjectAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		ObjectAttributeContentV2: v,
	}
}

// SecretAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns SecretAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func SecretAttributeContentV2AsBaseAttributeContentDtoV2(v *SecretAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		SecretAttributeContentV2: v,
	}
}

// StringAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns StringAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func StringAttributeContentV2AsBaseAttributeContentDtoV2(v *StringAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		StringAttributeContentV2: v,
	}
}

// TextAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns TextAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func TextAttributeContentV2AsBaseAttributeContentDtoV2(v *TextAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		TextAttributeContentV2: v,
	}
}

// TimeAttributeContentV2AsBaseAttributeContentDtoV2 is a convenience function that returns TimeAttributeContentV2 wrapped in BaseAttributeContentDtoV2
func TimeAttributeContentV2AsBaseAttributeContentDtoV2(v *TimeAttributeContentV2) BaseAttributeContentDtoV2 {
	return BaseAttributeContentDtoV2{
		TimeAttributeContentV2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *BaseAttributeContentDtoV2) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BooleanAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.BooleanAttributeContentV2)
	if err == nil {
		jsonBooleanAttributeContentV2, _ := json.Marshal(dst.BooleanAttributeContentV2)
		if string(jsonBooleanAttributeContentV2) == "{}" { // empty struct
			dst.BooleanAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.BooleanAttributeContentV2); err != nil {
				dst.BooleanAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.BooleanAttributeContentV2 = nil
	}

	// try to unmarshal data into CodeBlockAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.CodeBlockAttributeContentV2)
	if err == nil {
		jsonCodeBlockAttributeContentV2, _ := json.Marshal(dst.CodeBlockAttributeContentV2)
		if string(jsonCodeBlockAttributeContentV2) == "{}" { // empty struct
			dst.CodeBlockAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.CodeBlockAttributeContentV2); err != nil {
				dst.CodeBlockAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CodeBlockAttributeContentV2 = nil
	}

	// try to unmarshal data into CredentialAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.CredentialAttributeContentV2)
	if err == nil {
		jsonCredentialAttributeContentV2, _ := json.Marshal(dst.CredentialAttributeContentV2)
		if string(jsonCredentialAttributeContentV2) == "{}" { // empty struct
			dst.CredentialAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.CredentialAttributeContentV2); err != nil {
				dst.CredentialAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CredentialAttributeContentV2 = nil
	}

	// try to unmarshal data into DateAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.DateAttributeContentV2)
	if err == nil {
		jsonDateAttributeContentV2, _ := json.Marshal(dst.DateAttributeContentV2)
		if string(jsonDateAttributeContentV2) == "{}" { // empty struct
			dst.DateAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.DateAttributeContentV2); err != nil {
				dst.DateAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DateAttributeContentV2 = nil
	}

	// try to unmarshal data into DateTimeAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.DateTimeAttributeContentV2)
	if err == nil {
		jsonDateTimeAttributeContentV2, _ := json.Marshal(dst.DateTimeAttributeContentV2)
		if string(jsonDateTimeAttributeContentV2) == "{}" { // empty struct
			dst.DateTimeAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.DateTimeAttributeContentV2); err != nil {
				dst.DateTimeAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DateTimeAttributeContentV2 = nil
	}

	// try to unmarshal data into FileAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.FileAttributeContentV2)
	if err == nil {
		jsonFileAttributeContentV2, _ := json.Marshal(dst.FileAttributeContentV2)
		if string(jsonFileAttributeContentV2) == "{}" { // empty struct
			dst.FileAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.FileAttributeContentV2); err != nil {
				dst.FileAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.FileAttributeContentV2 = nil
	}

	// try to unmarshal data into FloatAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.FloatAttributeContentV2)
	if err == nil {
		jsonFloatAttributeContentV2, _ := json.Marshal(dst.FloatAttributeContentV2)
		if string(jsonFloatAttributeContentV2) == "{}" { // empty struct
			dst.FloatAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.FloatAttributeContentV2); err != nil {
				dst.FloatAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.FloatAttributeContentV2 = nil
	}

	// try to unmarshal data into IntegerAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.IntegerAttributeContentV2)
	if err == nil {
		jsonIntegerAttributeContentV2, _ := json.Marshal(dst.IntegerAttributeContentV2)
		if string(jsonIntegerAttributeContentV2) == "{}" { // empty struct
			dst.IntegerAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.IntegerAttributeContentV2); err != nil {
				dst.IntegerAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.IntegerAttributeContentV2 = nil
	}

	// try to unmarshal data into ObjectAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.ObjectAttributeContentV2)
	if err == nil {
		jsonObjectAttributeContentV2, _ := json.Marshal(dst.ObjectAttributeContentV2)
		if string(jsonObjectAttributeContentV2) == "{}" { // empty struct
			dst.ObjectAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.ObjectAttributeContentV2); err != nil {
				dst.ObjectAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ObjectAttributeContentV2 = nil
	}

	// try to unmarshal data into SecretAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.SecretAttributeContentV2)
	if err == nil {
		jsonSecretAttributeContentV2, _ := json.Marshal(dst.SecretAttributeContentV2)
		if string(jsonSecretAttributeContentV2) == "{}" { // empty struct
			dst.SecretAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.SecretAttributeContentV2); err != nil {
				dst.SecretAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.SecretAttributeContentV2 = nil
	}

	// try to unmarshal data into StringAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.StringAttributeContentV2)
	if err == nil {
		jsonStringAttributeContentV2, _ := json.Marshal(dst.StringAttributeContentV2)
		if string(jsonStringAttributeContentV2) == "{}" { // empty struct
			dst.StringAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.StringAttributeContentV2); err != nil {
				dst.StringAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.StringAttributeContentV2 = nil
	}

	// try to unmarshal data into TextAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.TextAttributeContentV2)
	if err == nil {
		jsonTextAttributeContentV2, _ := json.Marshal(dst.TextAttributeContentV2)
		if string(jsonTextAttributeContentV2) == "{}" { // empty struct
			dst.TextAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.TextAttributeContentV2); err != nil {
				dst.TextAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TextAttributeContentV2 = nil
	}

	// try to unmarshal data into TimeAttributeContentV2
	err = newStrictDecoder(data).Decode(&dst.TimeAttributeContentV2)
	if err == nil {
		jsonTimeAttributeContentV2, _ := json.Marshal(dst.TimeAttributeContentV2)
		if string(jsonTimeAttributeContentV2) == "{}" { // empty struct
			dst.TimeAttributeContentV2 = nil
		} else {
			if err = validator.Validate(dst.TimeAttributeContentV2); err != nil {
				dst.TimeAttributeContentV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimeAttributeContentV2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BooleanAttributeContentV2 = nil
		dst.CodeBlockAttributeContentV2 = nil
		dst.CredentialAttributeContentV2 = nil
		dst.DateAttributeContentV2 = nil
		dst.DateTimeAttributeContentV2 = nil
		dst.FileAttributeContentV2 = nil
		dst.FloatAttributeContentV2 = nil
		dst.IntegerAttributeContentV2 = nil
		dst.ObjectAttributeContentV2 = nil
		dst.SecretAttributeContentV2 = nil
		dst.StringAttributeContentV2 = nil
		dst.TextAttributeContentV2 = nil
		dst.TimeAttributeContentV2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BaseAttributeContentDtoV2)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BaseAttributeContentDtoV2)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BaseAttributeContentDtoV2) MarshalJSON() ([]byte, error) {
	if src.BooleanAttributeContentV2 != nil {
		return json.Marshal(&src.BooleanAttributeContentV2)
	}

	if src.CodeBlockAttributeContentV2 != nil {
		return json.Marshal(&src.CodeBlockAttributeContentV2)
	}

	if src.CredentialAttributeContentV2 != nil {
		return json.Marshal(&src.CredentialAttributeContentV2)
	}

	if src.DateAttributeContentV2 != nil {
		return json.Marshal(&src.DateAttributeContentV2)
	}

	if src.DateTimeAttributeContentV2 != nil {
		return json.Marshal(&src.DateTimeAttributeContentV2)
	}

	if src.FileAttributeContentV2 != nil {
		return json.Marshal(&src.FileAttributeContentV2)
	}

	if src.FloatAttributeContentV2 != nil {
		return json.Marshal(&src.FloatAttributeContentV2)
	}

	if src.IntegerAttributeContentV2 != nil {
		return json.Marshal(&src.IntegerAttributeContentV2)
	}

	if src.ObjectAttributeContentV2 != nil {
		return json.Marshal(&src.ObjectAttributeContentV2)
	}

	if src.SecretAttributeContentV2 != nil {
		return json.Marshal(&src.SecretAttributeContentV2)
	}

	if src.StringAttributeContentV2 != nil {
		return json.Marshal(&src.StringAttributeContentV2)
	}

	if src.TextAttributeContentV2 != nil {
		return json.Marshal(&src.TextAttributeContentV2)
	}

	if src.TimeAttributeContentV2 != nil {
		return json.Marshal(&src.TimeAttributeContentV2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BaseAttributeContentDtoV2) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BooleanAttributeContentV2 != nil {
		return obj.BooleanAttributeContentV2
	}

	if obj.CodeBlockAttributeContentV2 != nil {
		return obj.CodeBlockAttributeContentV2
	}

	if obj.CredentialAttributeContentV2 != nil {
		return obj.CredentialAttributeContentV2
	}

	if obj.DateAttributeContentV2 != nil {
		return obj.DateAttributeContentV2
	}

	if obj.DateTimeAttributeContentV2 != nil {
		return obj.DateTimeAttributeContentV2
	}

	if obj.FileAttributeContentV2 != nil {
		return obj.FileAttributeContentV2
	}

	if obj.FloatAttributeContentV2 != nil {
		return obj.FloatAttributeContentV2
	}

	if obj.IntegerAttributeContentV2 != nil {
		return obj.IntegerAttributeContentV2
	}

	if obj.ObjectAttributeContentV2 != nil {
		return obj.ObjectAttributeContentV2
	}

	if obj.SecretAttributeContentV2 != nil {
		return obj.SecretAttributeContentV2
	}

	if obj.StringAttributeContentV2 != nil {
		return obj.StringAttributeContentV2
	}

	if obj.TextAttributeContentV2 != nil {
		return obj.TextAttributeContentV2
	}

	if obj.TimeAttributeContentV2 != nil {
		return obj.TimeAttributeContentV2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BaseAttributeContentDtoV2) GetActualInstanceValue() (interface{}) {
	if obj.BooleanAttributeContentV2 != nil {
		return *obj.BooleanAttributeContentV2
	}

	if obj.CodeBlockAttributeContentV2 != nil {
		return *obj.CodeBlockAttributeContentV2
	}

	if obj.CredentialAttributeContentV2 != nil {
		return *obj.CredentialAttributeContentV2
	}

	if obj.DateAttributeContentV2 != nil {
		return *obj.DateAttributeContentV2
	}

	if obj.DateTimeAttributeContentV2 != nil {
		return *obj.DateTimeAttributeContentV2
	}

	if obj.FileAttributeContentV2 != nil {
		return *obj.FileAttributeContentV2
	}

	if obj.FloatAttributeContentV2 != nil {
		return *obj.FloatAttributeContentV2
	}

	if obj.IntegerAttributeContentV2 != nil {
		return *obj.IntegerAttributeContentV2
	}

	if obj.ObjectAttributeContentV2 != nil {
		return *obj.ObjectAttributeContentV2
	}

	if obj.SecretAttributeContentV2 != nil {
		return *obj.SecretAttributeContentV2
	}

	if obj.StringAttributeContentV2 != nil {
		return *obj.StringAttributeContentV2
	}

	if obj.TextAttributeContentV2 != nil {
		return *obj.TextAttributeContentV2
	}

	if obj.TimeAttributeContentV2 != nil {
		return *obj.TimeAttributeContentV2
	}

	// all schemas are nil
	return nil
}

type NullableBaseAttributeContentDtoV2 struct {
	value *BaseAttributeContentDtoV2
	isSet bool
}

func (v NullableBaseAttributeContentDtoV2) Get() *BaseAttributeContentDtoV2 {
	return v.value
}

func (v *NullableBaseAttributeContentDtoV2) Set(val *BaseAttributeContentDtoV2) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseAttributeContentDtoV2) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseAttributeContentDtoV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseAttributeContentDtoV2(val *BaseAttributeContentDtoV2) *NullableBaseAttributeContentDtoV2 {
	return &NullableBaseAttributeContentDtoV2{value: val, isSet: true}
}

func (v NullableBaseAttributeContentDtoV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseAttributeContentDtoV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


