/*
Compliance Provider API

REST API for implementations of custom Compliance Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the JsonSchemaAttributeConstraint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonSchemaAttributeConstraint{}

// JsonSchemaAttributeConstraint JSON Schema attribute constraint restricting a string value to JSON conforming to an inline JSON Schema (draft 2020-12)
type JsonSchemaAttributeConstraint struct {
	// Description of the constraint
	Description *string `json:"description,omitempty"`
	// Error message to be displayed for wrong data
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// Attribute Constraint Type
	Type AttributeConstraintType `json:"type"`
	// Inline JSON Schema document the value must conform to
	Data string `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _JsonSchemaAttributeConstraint JsonSchemaAttributeConstraint

// NewJsonSchemaAttributeConstraint instantiates a new JsonSchemaAttributeConstraint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonSchemaAttributeConstraint(type_ AttributeConstraintType, data string) *JsonSchemaAttributeConstraint {
	this := JsonSchemaAttributeConstraint{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewJsonSchemaAttributeConstraintWithDefaults instantiates a new JsonSchemaAttributeConstraint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonSchemaAttributeConstraintWithDefaults() *JsonSchemaAttributeConstraint {
	this := JsonSchemaAttributeConstraint{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *JsonSchemaAttributeConstraint) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonSchemaAttributeConstraint) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *JsonSchemaAttributeConstraint) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *JsonSchemaAttributeConstraint) SetDescription(v string) {
	o.Description = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *JsonSchemaAttributeConstraint) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonSchemaAttributeConstraint) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *JsonSchemaAttributeConstraint) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *JsonSchemaAttributeConstraint) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetType returns the Type field value
func (o *JsonSchemaAttributeConstraint) GetType() AttributeConstraintType {
	if o == nil {
		var ret AttributeConstraintType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JsonSchemaAttributeConstraint) GetTypeOk() (*AttributeConstraintType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JsonSchemaAttributeConstraint) SetType(v AttributeConstraintType) {
	o.Type = v
}

// GetData returns the Data field value
func (o *JsonSchemaAttributeConstraint) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *JsonSchemaAttributeConstraint) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *JsonSchemaAttributeConstraint) SetData(v string) {
	o.Data = v
}

func (o JsonSchemaAttributeConstraint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonSchemaAttributeConstraint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	toSerialize["type"] = o.Type
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JsonSchemaAttributeConstraint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJsonSchemaAttributeConstraint := _JsonSchemaAttributeConstraint{}

	err = json.Unmarshal(data, &varJsonSchemaAttributeConstraint)

	if err != nil {
		return err
	}

	*o = JsonSchemaAttributeConstraint(varJsonSchemaAttributeConstraint)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "errorMessage")
		delete(additionalProperties, "type")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJsonSchemaAttributeConstraint struct {
	value *JsonSchemaAttributeConstraint
	isSet bool
}

func (v NullableJsonSchemaAttributeConstraint) Get() *JsonSchemaAttributeConstraint {
	return v.value
}

func (v *NullableJsonSchemaAttributeConstraint) Set(val *JsonSchemaAttributeConstraint) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonSchemaAttributeConstraint) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonSchemaAttributeConstraint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonSchemaAttributeConstraint(val *JsonSchemaAttributeConstraint) *NullableJsonSchemaAttributeConstraint {
	return &NullableJsonSchemaAttributeConstraint{value: val, isSet: true}
}

func (v NullableJsonSchemaAttributeConstraint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonSchemaAttributeConstraint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


