/*
Authority Provider v3 API

REST API for implementations of custom v3 Authority Provider

API version: 2.18.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// CertificateOperationStatusV3 the model 'CertificateOperationStatusV3'
type CertificateOperationStatusV3 string

// List of CertificateOperationStatusV3
const (
	CERTIFICATEOPERATIONSTATUSV3_IN_PROGRESS CertificateOperationStatusV3 = "inProgress"
	CERTIFICATEOPERATIONSTATUSV3_COMPLETED CertificateOperationStatusV3 = "completed"
	CERTIFICATEOPERATIONSTATUSV3_FAILED CertificateOperationStatusV3 = "failed"
)

// All allowed values of CertificateOperationStatusV3 enum
var AllowedCertificateOperationStatusV3EnumValues = []CertificateOperationStatusV3{
	"inProgress",
	"completed",
	"failed",
}

func (v *CertificateOperationStatusV3) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CertificateOperationStatusV3(value)
	for _, existing := range AllowedCertificateOperationStatusV3EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CertificateOperationStatusV3", value)
}

// NewCertificateOperationStatusV3FromValue returns a pointer to a valid CertificateOperationStatusV3
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCertificateOperationStatusV3FromValue(v string) (*CertificateOperationStatusV3, error) {
	ev := CertificateOperationStatusV3(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CertificateOperationStatusV3: valid values are %v", v, AllowedCertificateOperationStatusV3EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CertificateOperationStatusV3) IsValid() bool {
	for _, existing := range AllowedCertificateOperationStatusV3EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CertificateOperationStatusV3 value
func (v CertificateOperationStatusV3) Ptr() *CertificateOperationStatusV3 {
	return &v
}

type NullableCertificateOperationStatusV3 struct {
	value *CertificateOperationStatusV3
	isSet bool
}

func (v NullableCertificateOperationStatusV3) Get() *CertificateOperationStatusV3 {
	return v.value
}

func (v *NullableCertificateOperationStatusV3) Set(val *CertificateOperationStatusV3) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateOperationStatusV3) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateOperationStatusV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateOperationStatusV3(val *CertificateOperationStatusV3) *NullableCertificateOperationStatusV3 {
	return &NullableCertificateOperationStatusV3{value: val, isSet: true}
}

func (v NullableCertificateOperationStatusV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateOperationStatusV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

