/*
Authority Provider v3 API

REST API for implementations of custom v3 Authority Provider

API version: 2.17.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the AggregateHealthInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregateHealthInfo{}

// AggregateHealthInfo Aggregate health response returned by GET /v2/health. Per the health-interface specification the liveness and readiness components are mandatory in every aggregate health response; the connector runtime always supplies them.
type AggregateHealthInfo struct {
	// Current connector operational status (worst of the connector's own health and the liveness/readiness probes)
	Status HealthStatus `json:"status"`
	Components AggregateHealthInfoComponents `json:"components"`
	AdditionalProperties map[string]interface{}
}

type _AggregateHealthInfo AggregateHealthInfo

// NewAggregateHealthInfo instantiates a new AggregateHealthInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregateHealthInfo(status HealthStatus, components AggregateHealthInfoComponents) *AggregateHealthInfo {
	this := AggregateHealthInfo{}
	this.Status = status
	this.Components = components
	return &this
}

// NewAggregateHealthInfoWithDefaults instantiates a new AggregateHealthInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregateHealthInfoWithDefaults() *AggregateHealthInfo {
	this := AggregateHealthInfo{}
	return &this
}

// GetStatus returns the Status field value
func (o *AggregateHealthInfo) GetStatus() HealthStatus {
	if o == nil {
		var ret HealthStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AggregateHealthInfo) GetStatusOk() (*HealthStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AggregateHealthInfo) SetStatus(v HealthStatus) {
	o.Status = v
}

// GetComponents returns the Components field value
func (o *AggregateHealthInfo) GetComponents() AggregateHealthInfoComponents {
	if o == nil {
		var ret AggregateHealthInfoComponents
		return ret
	}

	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *AggregateHealthInfo) GetComponentsOk() (*AggregateHealthInfoComponents, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Components, true
}

// SetComponents sets field value
func (o *AggregateHealthInfo) SetComponents(v AggregateHealthInfoComponents) {
	o.Components = v
}

func (o AggregateHealthInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregateHealthInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["components"] = o.Components

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AggregateHealthInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"components",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregateHealthInfo := _AggregateHealthInfo{}

	err = json.Unmarshal(data, &varAggregateHealthInfo)

	if err != nil {
		return err
	}

	*o = AggregateHealthInfo(varAggregateHealthInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "components")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAggregateHealthInfo struct {
	value *AggregateHealthInfo
	isSet bool
}

func (v NullableAggregateHealthInfo) Get() *AggregateHealthInfo {
	return v.value
}

func (v *NullableAggregateHealthInfo) Set(val *AggregateHealthInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateHealthInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateHealthInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateHealthInfo(val *AggregateHealthInfo) *NullableAggregateHealthInfo {
	return &NullableAggregateHealthInfo{value: val, isSet: true}
}

func (v NullableAggregateHealthInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateHealthInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


