/*
Authority Provider v3 API

REST API for implementations of custom v3 Authority Provider

API version: 2.18.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the CrlRequestDtoV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrlRequestDtoV3{}

// CrlRequestDtoV3 struct for CrlRequestDtoV3
type CrlRequestDtoV3 struct {
	// Authority attributes
	AuthorityAttributes []RequestAttribute `json:"authorityAttributes"`
	// RA profile attributes
	RaProfileAttributes []RequestAttribute `json:"raProfileAttributes"`
	// If true, the delta CRL is returned where supported; otherwise the full CRL.
	Delta *bool `json:"delta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CrlRequestDtoV3 CrlRequestDtoV3

// NewCrlRequestDtoV3 instantiates a new CrlRequestDtoV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrlRequestDtoV3(authorityAttributes []RequestAttribute, raProfileAttributes []RequestAttribute) *CrlRequestDtoV3 {
	this := CrlRequestDtoV3{}
	this.AuthorityAttributes = authorityAttributes
	this.RaProfileAttributes = raProfileAttributes
	var delta bool = false
	this.Delta = &delta
	return &this
}

// NewCrlRequestDtoV3WithDefaults instantiates a new CrlRequestDtoV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrlRequestDtoV3WithDefaults() *CrlRequestDtoV3 {
	this := CrlRequestDtoV3{}
	var delta bool = false
	this.Delta = &delta
	return &this
}

// GetAuthorityAttributes returns the AuthorityAttributes field value
func (o *CrlRequestDtoV3) GetAuthorityAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.AuthorityAttributes
}

// GetAuthorityAttributesOk returns a tuple with the AuthorityAttributes field value
// and a boolean to check if the value has been set.
func (o *CrlRequestDtoV3) GetAuthorityAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthorityAttributes, true
}

// SetAuthorityAttributes sets field value
func (o *CrlRequestDtoV3) SetAuthorityAttributes(v []RequestAttribute) {
	o.AuthorityAttributes = v
}

// GetRaProfileAttributes returns the RaProfileAttributes field value
func (o *CrlRequestDtoV3) GetRaProfileAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.RaProfileAttributes
}

// GetRaProfileAttributesOk returns a tuple with the RaProfileAttributes field value
// and a boolean to check if the value has been set.
func (o *CrlRequestDtoV3) GetRaProfileAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.RaProfileAttributes, true
}

// SetRaProfileAttributes sets field value
func (o *CrlRequestDtoV3) SetRaProfileAttributes(v []RequestAttribute) {
	o.RaProfileAttributes = v
}

// GetDelta returns the Delta field value if set, zero value otherwise.
func (o *CrlRequestDtoV3) GetDelta() bool {
	if o == nil || IsNil(o.Delta) {
		var ret bool
		return ret
	}
	return *o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrlRequestDtoV3) GetDeltaOk() (*bool, bool) {
	if o == nil || IsNil(o.Delta) {
		return nil, false
	}
	return o.Delta, true
}

// HasDelta returns a boolean if a field has been set.
func (o *CrlRequestDtoV3) HasDelta() bool {
	if o != nil && !IsNil(o.Delta) {
		return true
	}

	return false
}

// SetDelta gets a reference to the given bool and assigns it to the Delta field.
func (o *CrlRequestDtoV3) SetDelta(v bool) {
	o.Delta = &v
}

func (o CrlRequestDtoV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrlRequestDtoV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authorityAttributes"] = o.AuthorityAttributes
	toSerialize["raProfileAttributes"] = o.RaProfileAttributes
	if !IsNil(o.Delta) {
		toSerialize["delta"] = o.Delta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CrlRequestDtoV3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authorityAttributes",
		"raProfileAttributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrlRequestDtoV3 := _CrlRequestDtoV3{}

	err = json.Unmarshal(data, &varCrlRequestDtoV3)

	if err != nil {
		return err
	}

	*o = CrlRequestDtoV3(varCrlRequestDtoV3)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authorityAttributes")
		delete(additionalProperties, "raProfileAttributes")
		delete(additionalProperties, "delta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCrlRequestDtoV3 struct {
	value *CrlRequestDtoV3
	isSet bool
}

func (v NullableCrlRequestDtoV3) Get() *CrlRequestDtoV3 {
	return v.value
}

func (v *NullableCrlRequestDtoV3) Set(val *CrlRequestDtoV3) {
	v.value = val
	v.isSet = true
}

func (v NullableCrlRequestDtoV3) IsSet() bool {
	return v.isSet
}

func (v *NullableCrlRequestDtoV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrlRequestDtoV3(val *CrlRequestDtoV3) *NullableCrlRequestDtoV3 {
	return &NullableCrlRequestDtoV3{value: val, isSet: true}
}

func (v NullableCrlRequestDtoV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrlRequestDtoV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


