/*
Authority Provider v3 API

REST API for implementations of custom v3 Authority Provider

API version: 2.17.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the CertificateRevocationListResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateRevocationListResponseDto{}

// CertificateRevocationListResponseDto struct for CertificateRevocationListResponseDto
type CertificateRevocationListResponseDto struct {
	// Base64-encoded DER CRL data (full or delta per the request)
	CrlData string `json:"crlData"`
	// Whether the returned CRL is a delta CRL
	Delta *bool `json:"delta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CertificateRevocationListResponseDto CertificateRevocationListResponseDto

// NewCertificateRevocationListResponseDto instantiates a new CertificateRevocationListResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateRevocationListResponseDto(crlData string) *CertificateRevocationListResponseDto {
	this := CertificateRevocationListResponseDto{}
	this.CrlData = crlData
	var delta bool = false
	this.Delta = &delta
	return &this
}

// NewCertificateRevocationListResponseDtoWithDefaults instantiates a new CertificateRevocationListResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateRevocationListResponseDtoWithDefaults() *CertificateRevocationListResponseDto {
	this := CertificateRevocationListResponseDto{}
	var delta bool = false
	this.Delta = &delta
	return &this
}

// GetCrlData returns the CrlData field value
func (o *CertificateRevocationListResponseDto) GetCrlData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CrlData
}

// GetCrlDataOk returns a tuple with the CrlData field value
// and a boolean to check if the value has been set.
func (o *CertificateRevocationListResponseDto) GetCrlDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CrlData, true
}

// SetCrlData sets field value
func (o *CertificateRevocationListResponseDto) SetCrlData(v string) {
	o.CrlData = v
}

// GetDelta returns the Delta field value if set, zero value otherwise.
func (o *CertificateRevocationListResponseDto) GetDelta() bool {
	if o == nil || IsNil(o.Delta) {
		var ret bool
		return ret
	}
	return *o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRevocationListResponseDto) GetDeltaOk() (*bool, bool) {
	if o == nil || IsNil(o.Delta) {
		return nil, false
	}
	return o.Delta, true
}

// HasDelta returns a boolean if a field has been set.
func (o *CertificateRevocationListResponseDto) HasDelta() bool {
	if o != nil && !IsNil(o.Delta) {
		return true
	}

	return false
}

// SetDelta gets a reference to the given bool and assigns it to the Delta field.
func (o *CertificateRevocationListResponseDto) SetDelta(v bool) {
	o.Delta = &v
}

func (o CertificateRevocationListResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateRevocationListResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["crlData"] = o.CrlData
	if !IsNil(o.Delta) {
		toSerialize["delta"] = o.Delta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CertificateRevocationListResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"crlData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateRevocationListResponseDto := _CertificateRevocationListResponseDto{}

	err = json.Unmarshal(data, &varCertificateRevocationListResponseDto)

	if err != nil {
		return err
	}

	*o = CertificateRevocationListResponseDto(varCertificateRevocationListResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "crlData")
		delete(additionalProperties, "delta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCertificateRevocationListResponseDto struct {
	value *CertificateRevocationListResponseDto
	isSet bool
}

func (v NullableCertificateRevocationListResponseDto) Get() *CertificateRevocationListResponseDto {
	return v.value
}

func (v *NullableCertificateRevocationListResponseDto) Set(val *CertificateRevocationListResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateRevocationListResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateRevocationListResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateRevocationListResponseDto(val *CertificateRevocationListResponseDto) *NullableCertificateRevocationListResponseDto {
	return &NullableCertificateRevocationListResponseDto{value: val, isSet: true}
}

func (v NullableCertificateRevocationListResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateRevocationListResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


