/*
Authority Provider Legacy API

REST API for implementations of custom Legacy Authority Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package legacy

import (
	"encoding/json"
)

// checks if the RaProfileCertificateValidationSettingsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RaProfileCertificateValidationSettingsDto{}

// RaProfileCertificateValidationSettingsDto struct for RaProfileCertificateValidationSettingsDto
type RaProfileCertificateValidationSettingsDto struct {
	// Indicator whether validation of certificates associated with RA profile should be enabled, if null, then values in platform settings will be used
	Enabled *bool `json:"enabled,omitempty"`
	// Frequency of validation of certificates in days
	Frequency *int32 `json:"frequency,omitempty"`
	// How many days before expiration should certificate validation status change to Expiring
	ExpiringThreshold *int32 `json:"expiringThreshold,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RaProfileCertificateValidationSettingsDto RaProfileCertificateValidationSettingsDto

// NewRaProfileCertificateValidationSettingsDto instantiates a new RaProfileCertificateValidationSettingsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRaProfileCertificateValidationSettingsDto() *RaProfileCertificateValidationSettingsDto {
	this := RaProfileCertificateValidationSettingsDto{}
	return &this
}

// NewRaProfileCertificateValidationSettingsDtoWithDefaults instantiates a new RaProfileCertificateValidationSettingsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRaProfileCertificateValidationSettingsDtoWithDefaults() *RaProfileCertificateValidationSettingsDto {
	this := RaProfileCertificateValidationSettingsDto{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *RaProfileCertificateValidationSettingsDto) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RaProfileCertificateValidationSettingsDto) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *RaProfileCertificateValidationSettingsDto) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *RaProfileCertificateValidationSettingsDto) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *RaProfileCertificateValidationSettingsDto) GetFrequency() int32 {
	if o == nil || IsNil(o.Frequency) {
		var ret int32
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RaProfileCertificateValidationSettingsDto) GetFrequencyOk() (*int32, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *RaProfileCertificateValidationSettingsDto) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given int32 and assigns it to the Frequency field.
func (o *RaProfileCertificateValidationSettingsDto) SetFrequency(v int32) {
	o.Frequency = &v
}

// GetExpiringThreshold returns the ExpiringThreshold field value if set, zero value otherwise.
func (o *RaProfileCertificateValidationSettingsDto) GetExpiringThreshold() int32 {
	if o == nil || IsNil(o.ExpiringThreshold) {
		var ret int32
		return ret
	}
	return *o.ExpiringThreshold
}

// GetExpiringThresholdOk returns a tuple with the ExpiringThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RaProfileCertificateValidationSettingsDto) GetExpiringThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiringThreshold) {
		return nil, false
	}
	return o.ExpiringThreshold, true
}

// HasExpiringThreshold returns a boolean if a field has been set.
func (o *RaProfileCertificateValidationSettingsDto) HasExpiringThreshold() bool {
	if o != nil && !IsNil(o.ExpiringThreshold) {
		return true
	}

	return false
}

// SetExpiringThreshold gets a reference to the given int32 and assigns it to the ExpiringThreshold field.
func (o *RaProfileCertificateValidationSettingsDto) SetExpiringThreshold(v int32) {
	o.ExpiringThreshold = &v
}

func (o RaProfileCertificateValidationSettingsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RaProfileCertificateValidationSettingsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.ExpiringThreshold) {
		toSerialize["expiringThreshold"] = o.ExpiringThreshold
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RaProfileCertificateValidationSettingsDto) UnmarshalJSON(data []byte) (err error) {
	varRaProfileCertificateValidationSettingsDto := _RaProfileCertificateValidationSettingsDto{}

	err = json.Unmarshal(data, &varRaProfileCertificateValidationSettingsDto)

	if err != nil {
		return err
	}

	*o = RaProfileCertificateValidationSettingsDto(varRaProfileCertificateValidationSettingsDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "frequency")
		delete(additionalProperties, "expiringThreshold")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRaProfileCertificateValidationSettingsDto struct {
	value *RaProfileCertificateValidationSettingsDto
	isSet bool
}

func (v NullableRaProfileCertificateValidationSettingsDto) Get() *RaProfileCertificateValidationSettingsDto {
	return v.value
}

func (v *NullableRaProfileCertificateValidationSettingsDto) Set(val *RaProfileCertificateValidationSettingsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRaProfileCertificateValidationSettingsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRaProfileCertificateValidationSettingsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRaProfileCertificateValidationSettingsDto(val *RaProfileCertificateValidationSettingsDto) *NullableRaProfileCertificateValidationSettingsDto {
	return &NullableRaProfileCertificateValidationSettingsDto{value: val, isSet: true}
}

func (v NullableRaProfileCertificateValidationSettingsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRaProfileCertificateValidationSettingsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


