/*
Authority Provider Legacy API

REST API for implementations of custom Legacy Authority Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package legacy

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JwtTokenSecretContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JwtTokenSecretContent{}

// JwtTokenSecretContent Secret representing JWT Token
type JwtTokenSecretContent struct {
	// Secret type
	Type SecretType `json:"type"`
	// JWT Token content in compact (dot-separated) format specified in [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#section-3)
	Content string `json:"content"`
}

type _JwtTokenSecretContent JwtTokenSecretContent

// NewJwtTokenSecretContent instantiates a new JwtTokenSecretContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJwtTokenSecretContent(type_ SecretType, content string) *JwtTokenSecretContent {
	this := JwtTokenSecretContent{}
	this.Type = type_
	this.Content = content
	return &this
}

// NewJwtTokenSecretContentWithDefaults instantiates a new JwtTokenSecretContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJwtTokenSecretContentWithDefaults() *JwtTokenSecretContent {
	this := JwtTokenSecretContent{}
	return &this
}

// GetType returns the Type field value
func (o *JwtTokenSecretContent) GetType() SecretType {
	if o == nil {
		var ret SecretType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JwtTokenSecretContent) GetTypeOk() (*SecretType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JwtTokenSecretContent) SetType(v SecretType) {
	o.Type = v
}

// GetContent returns the Content field value
func (o *JwtTokenSecretContent) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *JwtTokenSecretContent) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *JwtTokenSecretContent) SetContent(v string) {
	o.Content = v
}

func (o JwtTokenSecretContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JwtTokenSecretContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *JwtTokenSecretContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJwtTokenSecretContent := _JwtTokenSecretContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJwtTokenSecretContent)

	if err != nil {
		return err
	}

	*o = JwtTokenSecretContent(varJwtTokenSecretContent)

	return err
}

type NullableJwtTokenSecretContent struct {
	value *JwtTokenSecretContent
	isSet bool
}

func (v NullableJwtTokenSecretContent) Get() *JwtTokenSecretContent {
	return v.value
}

func (v *NullableJwtTokenSecretContent) Set(val *JwtTokenSecretContent) {
	v.value = val
	v.isSet = true
}

func (v NullableJwtTokenSecretContent) IsSet() bool {
	return v.isSet
}

func (v *NullableJwtTokenSecretContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJwtTokenSecretContent(val *JwtTokenSecretContent) *NullableJwtTokenSecretContent {
	return &NullableJwtTokenSecretContent{value: val, isSet: true}
}

func (v NullableJwtTokenSecretContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJwtTokenSecretContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


