/*
Connector Attributes v2 API

The connector-global Attributes v2 API (the common NG connector-interface generation, alongside Info/Health/Metrics in connector.common.v2): a definition registry plus a dynamic-attribute callback surface. NOTE on version axes: the \"v2\" here is the common-interface/NG generation version, NOT attribute schema v2 — payloads carry the independent attribute-schema axis (v2/v3), and the callback response `content` arm is attribute schema v3 by design. Extracted from the authority-v3 spec (the common.v2 attributes subset) for cross-language parity with OmniTrustILM/interfaces#738; the schema set is the transitive closure of the three envelope DTOs.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// ErrorCode the model 'ErrorCode'
type ErrorCode string

// List of ErrorCode
const (
	ERRORCODE_VALIDATION_FAILED ErrorCode = "VALIDATION_FAILED"
	ERRORCODE_RESOURCE_NOT_FOUND ErrorCode = "RESOURCE_NOT_FOUND"
	ERRORCODE_RESOURCE_ALREADY_EXISTS ErrorCode = "RESOURCE_ALREADY_EXISTS"
	ERRORCODE_REQUEST_TIMEOUT ErrorCode = "REQUEST_TIMEOUT"
	ERRORCODE_OPERATION_NOT_SUPPORTED ErrorCode = "OPERATION_NOT_SUPPORTED"
	ERRORCODE_ATTRIBUTES_ERROR ErrorCode = "ATTRIBUTES_ERROR"
	ERRORCODE_SERVICE_UNAVAILABLE ErrorCode = "SERVICE_UNAVAILABLE"
	ERRORCODE_INTERNAL_SERVER_ERROR ErrorCode = "INTERNAL_SERVER_ERROR"
	ERRORCODE_BAD_REQUEST ErrorCode = "BAD_REQUEST"
	ERRORCODE_UNAUTHORIZED ErrorCode = "UNAUTHORIZED"
	ERRORCODE_FORBIDDEN ErrorCode = "FORBIDDEN"
	ERRORCODE_RATE_LIMIT_EXCEEDED ErrorCode = "RATE_LIMIT_EXCEEDED"
	ERRORCODE_GATEWAY_TIMEOUT ErrorCode = "GATEWAY_TIMEOUT"
	ERRORCODE_UPSTREAM_ERROR ErrorCode = "UPSTREAM_ERROR"
	ERRORCODE_CREDENTIAL_INVALID ErrorCode = "CREDENTIAL_INVALID"
	ERRORCODE_POLICY_VIOLATION ErrorCode = "POLICY_VIOLATION"
	ERRORCODE_OPERATION_PAST_POINT_OF_NO_RETURN ErrorCode = "OPERATION_PAST_POINT_OF_NO_RETURN"
	ERRORCODE_OPERATION_NOT_TRACKED ErrorCode = "OPERATION_NOT_TRACKED"
	ERRORCODE_ATTRIBUTE_DEFINITION_NOT_FOUND ErrorCode = "ATTRIBUTE_DEFINITION_NOT_FOUND"
	ERRORCODE_CSR_MALFORMED ErrorCode = "CSR_MALFORMED"
	ERRORCODE_REVOCATION_NOT_ALLOWED ErrorCode = "REVOCATION_NOT_ALLOWED"
	ERRORCODE_REGISTRATION_NOT_FOUND ErrorCode = "REGISTRATION_NOT_FOUND"
	ERRORCODE_RENEWAL_SOURCE_NOT_FOUND ErrorCode = "RENEWAL_SOURCE_NOT_FOUND"
	ERRORCODE_CSR_SUBJECT_MISMATCH ErrorCode = "CSR_SUBJECT_MISMATCH"
	ERRORCODE_CERTIFICATE_MISMATCH ErrorCode = "CERTIFICATE_MISMATCH"
)

// All allowed values of ErrorCode enum
var AllowedErrorCodeEnumValues = []ErrorCode{
	"VALIDATION_FAILED",
	"RESOURCE_NOT_FOUND",
	"RESOURCE_ALREADY_EXISTS",
	"REQUEST_TIMEOUT",
	"OPERATION_NOT_SUPPORTED",
	"ATTRIBUTES_ERROR",
	"SERVICE_UNAVAILABLE",
	"INTERNAL_SERVER_ERROR",
	"BAD_REQUEST",
	"UNAUTHORIZED",
	"FORBIDDEN",
	"RATE_LIMIT_EXCEEDED",
	"GATEWAY_TIMEOUT",
	"UPSTREAM_ERROR",
	"CREDENTIAL_INVALID",
	"POLICY_VIOLATION",
	"OPERATION_PAST_POINT_OF_NO_RETURN",
	"OPERATION_NOT_TRACKED",
	"ATTRIBUTE_DEFINITION_NOT_FOUND",
	"CSR_MALFORMED",
	"REVOCATION_NOT_ALLOWED",
	"REGISTRATION_NOT_FOUND",
	"RENEWAL_SOURCE_NOT_FOUND",
	"CSR_SUBJECT_MISMATCH",
	"CERTIFICATE_MISMATCH",
}

func (v *ErrorCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ErrorCode(value)
	for _, existing := range AllowedErrorCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ErrorCode", value)
}

// NewErrorCodeFromValue returns a pointer to a valid ErrorCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewErrorCodeFromValue(v string) (*ErrorCode, error) {
	ev := ErrorCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ErrorCode: valid values are %v", v, AllowedErrorCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ErrorCode) IsValid() bool {
	for _, existing := range AllowedErrorCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ErrorCode value
func (v ErrorCode) Ptr() *ErrorCode {
	return &v
}

type NullableErrorCode struct {
	value *ErrorCode
	isSet bool
}

func (v NullableErrorCode) Get() *ErrorCode {
	return v.value
}

func (v *NullableErrorCode) Set(val *ErrorCode) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorCode) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorCode(val *ErrorCode) *NullableErrorCode {
	return &NullableErrorCode{value: val, isSet: true}
}

func (v NullableErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

