/*
Connector Attributes v2 API

The connector-global Attributes v2 API (the common NG connector-interface generation, alongside Info/Health/Metrics in connector.common.v2): a definition registry plus a dynamic-attribute callback surface. NOTE on version axes: the \"v2\" here is the common-interface/NG generation version, NOT attribute schema v2 — payloads carry the independent attribute-schema axis (v2/v3), and the callback response `content` arm is attribute schema v3 by design. Extracted from the authority-v3 spec (the common.v2 attributes subset) for cross-language parity with OmniTrustILM/interfaces#738; the schema set is the transitive closure of the three envelope DTOs.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// GeneralNameType the model 'GeneralNameType'
type GeneralNameType string

// List of GeneralNameType
const (
	GENERALNAMETYPE_DNS GeneralNameType = "dns"
	GENERALNAMETYPE_EMAIL GeneralNameType = "email"
	GENERALNAMETYPE_IP GeneralNameType = "ip"
	GENERALNAMETYPE_URI GeneralNameType = "uri"
	GENERALNAMETYPE_OTHER_NAME GeneralNameType = "otherName"
	GENERALNAMETYPE_DIRECTORY_NAME GeneralNameType = "directoryName"
	GENERALNAMETYPE_REGISTERED_ID GeneralNameType = "registeredId"
)

// All allowed values of GeneralNameType enum
var AllowedGeneralNameTypeEnumValues = []GeneralNameType{
	"dns",
	"email",
	"ip",
	"uri",
	"otherName",
	"directoryName",
	"registeredId",
}

func (v *GeneralNameType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GeneralNameType(value)
	for _, existing := range AllowedGeneralNameTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GeneralNameType", value)
}

// NewGeneralNameTypeFromValue returns a pointer to a valid GeneralNameType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGeneralNameTypeFromValue(v string) (*GeneralNameType, error) {
	ev := GeneralNameType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GeneralNameType: valid values are %v", v, AllowedGeneralNameTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GeneralNameType) IsValid() bool {
	for _, existing := range AllowedGeneralNameTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GeneralNameType value
func (v GeneralNameType) Ptr() *GeneralNameType {
	return &v
}

type NullableGeneralNameType struct {
	value *GeneralNameType
	isSet bool
}

func (v NullableGeneralNameType) Get() *GeneralNameType {
	return v.value
}

func (v *NullableGeneralNameType) Set(val *GeneralNameType) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneralNameType) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneralNameType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneralNameType(val *GeneralNameType) *NullableGeneralNameType {
	return &NullableGeneralNameType{value: val, isSet: true}
}

func (v NullableGeneralNameType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneralNameType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

