/*
Credential Provider API

REST API for implementations of custom Credential Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credential

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MetadataAttributeV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataAttributeV3{}

// MetadataAttributeV3 Info attribute contains content that is for metadata. Its content can not be edited and is not send in requests to store.
type MetadataAttributeV3 struct {
	// UUID of the Attribute for unique identification
	Uuid string `json:"uuid"`
	// Name of the Attribute that is used for identification
	Name string `json:"name"`
	// Optional description of the Attribute, should contain helper text on what is expected
	Description *string `json:"description,omitempty"`
	// Version of the attribute
	Version int32 `json:"version"`
	// Type of the Attribute
	Type AttributeType `json:"type"`
	// Content of the Attribute
	Content []BaseAttributeContentDtoV3 `json:"content,omitempty"`
	// Type of the Content
	ContentType AttributeContentType `json:"contentType"`
	// Properties of the Attributes
	Properties MetadataAttributeProperties `json:"properties"`
	// Schema version of the Attribute
	SchemaVersion AttributeVersion `json:"schemaVersion"`
}

type _MetadataAttributeV3 MetadataAttributeV3

// NewMetadataAttributeV3 instantiates a new MetadataAttributeV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataAttributeV3(uuid string, name string, version int32, type_ AttributeType, contentType AttributeContentType, properties MetadataAttributeProperties, schemaVersion AttributeVersion) *MetadataAttributeV3 {
	this := MetadataAttributeV3{}
	this.Uuid = uuid
	this.Name = name
	this.Version = version
	this.Type = type_
	this.ContentType = contentType
	this.Properties = properties
	this.SchemaVersion = schemaVersion
	return &this
}

// NewMetadataAttributeV3WithDefaults instantiates a new MetadataAttributeV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataAttributeV3WithDefaults() *MetadataAttributeV3 {
	this := MetadataAttributeV3{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *MetadataAttributeV3) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *MetadataAttributeV3) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *MetadataAttributeV3) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MetadataAttributeV3) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MetadataAttributeV3) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MetadataAttributeV3) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MetadataAttributeV3) SetDescription(v string) {
	o.Description = &v
}

// GetVersion returns the Version field value
func (o *MetadataAttributeV3) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *MetadataAttributeV3) SetVersion(v int32) {
	o.Version = v
}

// GetType returns the Type field value
func (o *MetadataAttributeV3) GetType() AttributeType {
	if o == nil {
		var ret AttributeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetTypeOk() (*AttributeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MetadataAttributeV3) SetType(v AttributeType) {
	o.Type = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *MetadataAttributeV3) GetContent() []BaseAttributeContentDtoV3 {
	if o == nil || IsNil(o.Content) {
		var ret []BaseAttributeContentDtoV3
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetContentOk() ([]BaseAttributeContentDtoV3, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *MetadataAttributeV3) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []BaseAttributeContentDtoV3 and assigns it to the Content field.
func (o *MetadataAttributeV3) SetContent(v []BaseAttributeContentDtoV3) {
	o.Content = v
}

// GetContentType returns the ContentType field value
func (o *MetadataAttributeV3) GetContentType() AttributeContentType {
	if o == nil {
		var ret AttributeContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetContentTypeOk() (*AttributeContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *MetadataAttributeV3) SetContentType(v AttributeContentType) {
	o.ContentType = v
}

// GetProperties returns the Properties field value
func (o *MetadataAttributeV3) GetProperties() MetadataAttributeProperties {
	if o == nil {
		var ret MetadataAttributeProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetPropertiesOk() (*MetadataAttributeProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *MetadataAttributeV3) SetProperties(v MetadataAttributeProperties) {
	o.Properties = v
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *MetadataAttributeV3) GetSchemaVersion() AttributeVersion {
	if o == nil {
		var ret AttributeVersion
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *MetadataAttributeV3) GetSchemaVersionOk() (*AttributeVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *MetadataAttributeV3) SetSchemaVersion(v AttributeVersion) {
	o.SchemaVersion = v
}

func (o MetadataAttributeV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataAttributeV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["version"] = o.Version
	toSerialize["type"] = o.Type
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	toSerialize["contentType"] = o.ContentType
	toSerialize["properties"] = o.Properties
	toSerialize["schemaVersion"] = o.SchemaVersion
	return toSerialize, nil
}

func (o *MetadataAttributeV3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"version",
		"type",
		"contentType",
		"properties",
		"schemaVersion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetadataAttributeV3 := _MetadataAttributeV3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetadataAttributeV3)

	if err != nil {
		return err
	}

	*o = MetadataAttributeV3(varMetadataAttributeV3)

	return err
}

type NullableMetadataAttributeV3 struct {
	value *MetadataAttributeV3
	isSet bool
}

func (v NullableMetadataAttributeV3) Get() *MetadataAttributeV3 {
	return v.value
}

func (v *NullableMetadataAttributeV3) Set(val *MetadataAttributeV3) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataAttributeV3) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataAttributeV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataAttributeV3(val *MetadataAttributeV3) *NullableMetadataAttributeV3 {
	return &NullableMetadataAttributeV3{value: val, isSet: true}
}

func (v NullableMetadataAttributeV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataAttributeV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


