/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the EprkiKeyValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EprkiKeyValue{}

// EprkiKeyValue struct for EprkiKeyValue
type EprkiKeyValue struct {
	// Base64 ASN.1 encoded EncryptedPrivateKeyInfo
	Value string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _EprkiKeyValue EprkiKeyValue

// NewEprkiKeyValue instantiates a new EprkiKeyValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEprkiKeyValue(value string) *EprkiKeyValue {
	this := EprkiKeyValue{}
	this.Value = value
	return &this
}

// NewEprkiKeyValueWithDefaults instantiates a new EprkiKeyValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEprkiKeyValueWithDefaults() *EprkiKeyValue {
	this := EprkiKeyValue{}
	return &this
}

// GetValue returns the Value field value
func (o *EprkiKeyValue) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *EprkiKeyValue) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *EprkiKeyValue) SetValue(v string) {
	o.Value = v
}

func (o EprkiKeyValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EprkiKeyValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EprkiKeyValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEprkiKeyValue := _EprkiKeyValue{}

	err = json.Unmarshal(data, &varEprkiKeyValue)

	if err != nil {
		return err
	}

	*o = EprkiKeyValue(varEprkiKeyValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEprkiKeyValue struct {
	value *EprkiKeyValue
	isSet bool
}

func (v NullableEprkiKeyValue) Get() *EprkiKeyValue {
	return v.value
}

func (v *NullableEprkiKeyValue) Set(val *EprkiKeyValue) {
	v.value = val
	v.isSet = true
}

func (v NullableEprkiKeyValue) IsSet() bool {
	return v.isSet
}

func (v *NullableEprkiKeyValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEprkiKeyValue(val *EprkiKeyValue) *NullableEprkiKeyValue {
	return &NullableEprkiKeyValue{value: val, isSet: true}
}

func (v NullableEprkiKeyValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEprkiKeyValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


