/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the SignatureRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignatureRequestData{}

// SignatureRequestData struct for SignatureRequestData
type SignatureRequestData struct {
	// Data to be signed or verified
	Data string `json:"data"`
	// Custom identifier of the data, that should be the same as in the request, if available
	Identifier *string `json:"identifier,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SignatureRequestData SignatureRequestData

// NewSignatureRequestData instantiates a new SignatureRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignatureRequestData(data string) *SignatureRequestData {
	this := SignatureRequestData{}
	this.Data = data
	return &this
}

// NewSignatureRequestDataWithDefaults instantiates a new SignatureRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignatureRequestDataWithDefaults() *SignatureRequestData {
	this := SignatureRequestData{}
	return &this
}

// GetData returns the Data field value
func (o *SignatureRequestData) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SignatureRequestData) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SignatureRequestData) SetData(v string) {
	o.Data = v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *SignatureRequestData) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignatureRequestData) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *SignatureRequestData) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *SignatureRequestData) SetIdentifier(v string) {
	o.Identifier = &v
}

func (o SignatureRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignatureRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SignatureRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignatureRequestData := _SignatureRequestData{}

	err = json.Unmarshal(data, &varSignatureRequestData)

	if err != nil {
		return err
	}

	*o = SignatureRequestData(varSignatureRequestData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "identifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSignatureRequestData struct {
	value *SignatureRequestData
	isSet bool
}

func (v NullableSignatureRequestData) Get() *SignatureRequestData {
	return v.value
}

func (v *NullableSignatureRequestData) Set(val *SignatureRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableSignatureRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableSignatureRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignatureRequestData(val *SignatureRequestData) *NullableSignatureRequestData {
	return &NullableSignatureRequestData{value: val, isSet: true}
}

func (v NullableSignatureRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignatureRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


