/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DateTimeAttributeContentV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DateTimeAttributeContentV3{}

// DateTimeAttributeContentV3 DateTime attribute content in predefined format with timezone
type DateTimeAttributeContentV3 struct {
	// Content Reference
	Reference *string `json:"reference,omitempty"`
	// DateTime attribute value in format yyyy-MM-ddTHH:mm:ss.SSSXXX
	Data time.Time `json:"data"`
	// Content Type of the attribute
	ContentType AttributeContentType `json:"contentType"`
}

type _DateTimeAttributeContentV3 DateTimeAttributeContentV3

// NewDateTimeAttributeContentV3 instantiates a new DateTimeAttributeContentV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDateTimeAttributeContentV3(data time.Time, contentType AttributeContentType) *DateTimeAttributeContentV3 {
	this := DateTimeAttributeContentV3{}
	this.Data = data
	this.ContentType = contentType
	return &this
}

// NewDateTimeAttributeContentV3WithDefaults instantiates a new DateTimeAttributeContentV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDateTimeAttributeContentV3WithDefaults() *DateTimeAttributeContentV3 {
	this := DateTimeAttributeContentV3{}
	return &this
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *DateTimeAttributeContentV3) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DateTimeAttributeContentV3) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *DateTimeAttributeContentV3) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *DateTimeAttributeContentV3) SetReference(v string) {
	o.Reference = &v
}

// GetData returns the Data field value
func (o *DateTimeAttributeContentV3) GetData() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DateTimeAttributeContentV3) GetDataOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DateTimeAttributeContentV3) SetData(v time.Time) {
	o.Data = v
}

// GetContentType returns the ContentType field value
func (o *DateTimeAttributeContentV3) GetContentType() AttributeContentType {
	if o == nil {
		var ret AttributeContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *DateTimeAttributeContentV3) GetContentTypeOk() (*AttributeContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *DateTimeAttributeContentV3) SetContentType(v AttributeContentType) {
	o.ContentType = v
}

func (o DateTimeAttributeContentV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DateTimeAttributeContentV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	toSerialize["data"] = o.Data
	toSerialize["contentType"] = o.ContentType
	return toSerialize, nil
}

func (o *DateTimeAttributeContentV3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"contentType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDateTimeAttributeContentV3 := _DateTimeAttributeContentV3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDateTimeAttributeContentV3)

	if err != nil {
		return err
	}

	*o = DateTimeAttributeContentV3(varDateTimeAttributeContentV3)

	return err
}

type NullableDateTimeAttributeContentV3 struct {
	value *DateTimeAttributeContentV3
	isSet bool
}

func (v NullableDateTimeAttributeContentV3) Get() *DateTimeAttributeContentV3 {
	return v.value
}

func (v *NullableDateTimeAttributeContentV3) Set(val *DateTimeAttributeContentV3) {
	v.value = val
	v.isSet = true
}

func (v NullableDateTimeAttributeContentV3) IsSet() bool {
	return v.isSet
}

func (v *NullableDateTimeAttributeContentV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDateTimeAttributeContentV3(val *DateTimeAttributeContentV3) *NullableDateTimeAttributeContentV3 {
	return &NullableDateTimeAttributeContentV3{value: val, isSet: true}
}

func (v NullableDateTimeAttributeContentV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDateTimeAttributeContentV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


