/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the TokenInstanceDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInstanceDto{}

// TokenInstanceDto struct for TokenInstanceDto
type TokenInstanceDto struct {
	// Object identifier
	Uuid string `json:"uuid"`
	// Object Name
	Name string `json:"name"`
	// Token instance Metadata
	Metadata []MetadataAttribute `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TokenInstanceDto TokenInstanceDto

// NewTokenInstanceDto instantiates a new TokenInstanceDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInstanceDto(uuid string, name string) *TokenInstanceDto {
	this := TokenInstanceDto{}
	this.Uuid = uuid
	this.Name = name
	return &this
}

// NewTokenInstanceDtoWithDefaults instantiates a new TokenInstanceDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInstanceDtoWithDefaults() *TokenInstanceDto {
	this := TokenInstanceDto{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *TokenInstanceDto) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TokenInstanceDto) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TokenInstanceDto) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *TokenInstanceDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TokenInstanceDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TokenInstanceDto) SetName(v string) {
	o.Name = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *TokenInstanceDto) GetMetadata() []MetadataAttribute {
	if o == nil || IsNil(o.Metadata) {
		var ret []MetadataAttribute
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInstanceDto) GetMetadataOk() ([]MetadataAttribute, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *TokenInstanceDto) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []MetadataAttribute and assigns it to the Metadata field.
func (o *TokenInstanceDto) SetMetadata(v []MetadataAttribute) {
	o.Metadata = v
}

func (o TokenInstanceDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInstanceDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokenInstanceDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenInstanceDto := _TokenInstanceDto{}

	err = json.Unmarshal(data, &varTokenInstanceDto)

	if err != nil {
		return err
	}

	*o = TokenInstanceDto(varTokenInstanceDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokenInstanceDto struct {
	value *TokenInstanceDto
	isSet bool
}

func (v NullableTokenInstanceDto) Get() *TokenInstanceDto {
	return v.value
}

func (v *NullableTokenInstanceDto) Set(val *TokenInstanceDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInstanceDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInstanceDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInstanceDto(val *TokenInstanceDto) *NullableTokenInstanceDto {
	return &NullableTokenInstanceDto{value: val, isSet: true}
}

func (v NullableTokenInstanceDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInstanceDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


