/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the EncryptDataResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EncryptDataResponseDto{}

// EncryptDataResponseDto struct for EncryptDataResponseDto
type EncryptDataResponseDto struct {
	// Encrypted data
	EncryptedData []CipherResponseData `json:"encryptedData"`
	AdditionalProperties map[string]interface{}
}

type _EncryptDataResponseDto EncryptDataResponseDto

// NewEncryptDataResponseDto instantiates a new EncryptDataResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEncryptDataResponseDto(encryptedData []CipherResponseData) *EncryptDataResponseDto {
	this := EncryptDataResponseDto{}
	this.EncryptedData = encryptedData
	return &this
}

// NewEncryptDataResponseDtoWithDefaults instantiates a new EncryptDataResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEncryptDataResponseDtoWithDefaults() *EncryptDataResponseDto {
	this := EncryptDataResponseDto{}
	return &this
}

// GetEncryptedData returns the EncryptedData field value
func (o *EncryptDataResponseDto) GetEncryptedData() []CipherResponseData {
	if o == nil {
		var ret []CipherResponseData
		return ret
	}

	return o.EncryptedData
}

// GetEncryptedDataOk returns a tuple with the EncryptedData field value
// and a boolean to check if the value has been set.
func (o *EncryptDataResponseDto) GetEncryptedDataOk() ([]CipherResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return o.EncryptedData, true
}

// SetEncryptedData sets field value
func (o *EncryptDataResponseDto) SetEncryptedData(v []CipherResponseData) {
	o.EncryptedData = v
}

func (o EncryptDataResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EncryptDataResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["encryptedData"] = o.EncryptedData

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EncryptDataResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"encryptedData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEncryptDataResponseDto := _EncryptDataResponseDto{}

	err = json.Unmarshal(data, &varEncryptDataResponseDto)

	if err != nil {
		return err
	}

	*o = EncryptDataResponseDto(varEncryptDataResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "encryptedData")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEncryptDataResponseDto struct {
	value *EncryptDataResponseDto
	isSet bool
}

func (v NullableEncryptDataResponseDto) Get() *EncryptDataResponseDto {
	return v.value
}

func (v *NullableEncryptDataResponseDto) Set(val *EncryptDataResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEncryptDataResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEncryptDataResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncryptDataResponseDto(val *EncryptDataResponseDto) *NullableEncryptDataResponseDto {
	return &NullableEncryptDataResponseDto{value: val, isSet: true}
}

func (v NullableEncryptDataResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncryptDataResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


