/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the TokenInstanceRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInstanceRequestDto{}

// TokenInstanceRequestDto struct for TokenInstanceRequestDto
type TokenInstanceRequestDto struct {
	// Token instance name
	Name string `json:"name"`
	// Kind of Token instance
	Kind string `json:"kind"`
	// List of Token instance Attributes
	Attributes []RequestAttribute `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _TokenInstanceRequestDto TokenInstanceRequestDto

// NewTokenInstanceRequestDto instantiates a new TokenInstanceRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInstanceRequestDto(name string, kind string, attributes []RequestAttribute) *TokenInstanceRequestDto {
	this := TokenInstanceRequestDto{}
	this.Name = name
	this.Kind = kind
	this.Attributes = attributes
	return &this
}

// NewTokenInstanceRequestDtoWithDefaults instantiates a new TokenInstanceRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInstanceRequestDtoWithDefaults() *TokenInstanceRequestDto {
	this := TokenInstanceRequestDto{}
	return &this
}

// GetName returns the Name field value
func (o *TokenInstanceRequestDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TokenInstanceRequestDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TokenInstanceRequestDto) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *TokenInstanceRequestDto) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *TokenInstanceRequestDto) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *TokenInstanceRequestDto) SetKind(v string) {
	o.Kind = v
}

// GetAttributes returns the Attributes field value
func (o *TokenInstanceRequestDto) GetAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *TokenInstanceRequestDto) GetAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attributes, true
}

// SetAttributes sets field value
func (o *TokenInstanceRequestDto) SetAttributes(v []RequestAttribute) {
	o.Attributes = v
}

func (o TokenInstanceRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInstanceRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokenInstanceRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"kind",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenInstanceRequestDto := _TokenInstanceRequestDto{}

	err = json.Unmarshal(data, &varTokenInstanceRequestDto)

	if err != nil {
		return err
	}

	*o = TokenInstanceRequestDto(varTokenInstanceRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokenInstanceRequestDto struct {
	value *TokenInstanceRequestDto
	isSet bool
}

func (v NullableTokenInstanceRequestDto) Get() *TokenInstanceRequestDto {
	return v.value
}

func (v *NullableTokenInstanceRequestDto) Set(val *TokenInstanceRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInstanceRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInstanceRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInstanceRequestDto(val *TokenInstanceRequestDto) *NullableTokenInstanceRequestDto {
	return &NullableTokenInstanceRequestDto{value: val, isSet: true}
}

func (v NullableTokenInstanceRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInstanceRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


