/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CipherDataRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CipherDataRequestDto{}

// CipherDataRequestDto struct for CipherDataRequestDto
type CipherDataRequestDto struct {
	// List of cipher Attributes
	CipherAttributes []RequestAttribute `json:"cipherAttributes"`
	// Encrypted/decrypted data
	CipherData []CipherRequestData `json:"cipherData"`
}

type _CipherDataRequestDto CipherDataRequestDto

// NewCipherDataRequestDto instantiates a new CipherDataRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCipherDataRequestDto(cipherAttributes []RequestAttribute, cipherData []CipherRequestData) *CipherDataRequestDto {
	this := CipherDataRequestDto{}
	this.CipherAttributes = cipherAttributes
	this.CipherData = cipherData
	return &this
}

// NewCipherDataRequestDtoWithDefaults instantiates a new CipherDataRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCipherDataRequestDtoWithDefaults() *CipherDataRequestDto {
	this := CipherDataRequestDto{}
	return &this
}

// GetCipherAttributes returns the CipherAttributes field value
func (o *CipherDataRequestDto) GetCipherAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.CipherAttributes
}

// GetCipherAttributesOk returns a tuple with the CipherAttributes field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestDto) GetCipherAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.CipherAttributes, true
}

// SetCipherAttributes sets field value
func (o *CipherDataRequestDto) SetCipherAttributes(v []RequestAttribute) {
	o.CipherAttributes = v
}

// GetCipherData returns the CipherData field value
func (o *CipherDataRequestDto) GetCipherData() []CipherRequestData {
	if o == nil {
		var ret []CipherRequestData
		return ret
	}

	return o.CipherData
}

// GetCipherDataOk returns a tuple with the CipherData field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestDto) GetCipherDataOk() ([]CipherRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return o.CipherData, true
}

// SetCipherData sets field value
func (o *CipherDataRequestDto) SetCipherData(v []CipherRequestData) {
	o.CipherData = v
}

func (o CipherDataRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CipherDataRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cipherAttributes"] = o.CipherAttributes
	toSerialize["cipherData"] = o.CipherData
	return toSerialize, nil
}

func (o *CipherDataRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cipherAttributes",
		"cipherData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCipherDataRequestDto := _CipherDataRequestDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCipherDataRequestDto)

	if err != nil {
		return err
	}

	*o = CipherDataRequestDto(varCipherDataRequestDto)

	return err
}

type NullableCipherDataRequestDto struct {
	value *CipherDataRequestDto
	isSet bool
}

func (v NullableCipherDataRequestDto) Get() *CipherDataRequestDto {
	return v.value
}

func (v *NullableCipherDataRequestDto) Set(val *CipherDataRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCipherDataRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCipherDataRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCipherDataRequestDto(val *CipherDataRequestDto) *NullableCipherDataRequestDto {
	return &NullableCipherDataRequestDto{value: val, isSet: true}
}

func (v NullableCipherDataRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCipherDataRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


