/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the SignatureResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignatureResponseData{}

// SignatureResponseData struct for SignatureResponseData
type SignatureResponseData struct {
	// Signature data
	Data string `json:"data"`
	// Custom identifier of the data, that should be the same as in the request, if available
	Identifier *string `json:"identifier,omitempty"`
	Details interface{} `json:"details,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SignatureResponseData SignatureResponseData

// NewSignatureResponseData instantiates a new SignatureResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignatureResponseData(data string) *SignatureResponseData {
	this := SignatureResponseData{}
	this.Data = data
	return &this
}

// NewSignatureResponseDataWithDefaults instantiates a new SignatureResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignatureResponseDataWithDefaults() *SignatureResponseData {
	this := SignatureResponseData{}
	return &this
}

// GetData returns the Data field value
func (o *SignatureResponseData) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SignatureResponseData) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SignatureResponseData) SetData(v string) {
	o.Data = v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *SignatureResponseData) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignatureResponseData) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *SignatureResponseData) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *SignatureResponseData) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SignatureResponseData) GetDetails() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SignatureResponseData) GetDetailsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return &o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *SignatureResponseData) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given interface{} and assigns it to the Details field.
func (o *SignatureResponseData) SetDetails(v interface{}) {
	o.Details = v
}

func (o SignatureResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignatureResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if o.Details != nil {
		toSerialize["details"] = o.Details
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SignatureResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignatureResponseData := _SignatureResponseData{}

	err = json.Unmarshal(data, &varSignatureResponseData)

	if err != nil {
		return err
	}

	*o = SignatureResponseData(varSignatureResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "details")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSignatureResponseData struct {
	value *SignatureResponseData
	isSet bool
}

func (v NullableSignatureResponseData) Get() *SignatureResponseData {
	return v.value
}

func (v *NullableSignatureResponseData) Set(val *SignatureResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableSignatureResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableSignatureResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignatureResponseData(val *SignatureResponseData) *NullableSignatureResponseData {
	return &NullableSignatureResponseData{value: val, isSet: true}
}

func (v NullableSignatureResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignatureResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


