/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the DecryptDataResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecryptDataResponseDto{}

// DecryptDataResponseDto struct for DecryptDataResponseDto
type DecryptDataResponseDto struct {
	// Decrypted data
	DecryptedData []CipherResponseData `json:"decryptedData"`
	AdditionalProperties map[string]interface{}
}

type _DecryptDataResponseDto DecryptDataResponseDto

// NewDecryptDataResponseDto instantiates a new DecryptDataResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecryptDataResponseDto(decryptedData []CipherResponseData) *DecryptDataResponseDto {
	this := DecryptDataResponseDto{}
	this.DecryptedData = decryptedData
	return &this
}

// NewDecryptDataResponseDtoWithDefaults instantiates a new DecryptDataResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecryptDataResponseDtoWithDefaults() *DecryptDataResponseDto {
	this := DecryptDataResponseDto{}
	return &this
}

// GetDecryptedData returns the DecryptedData field value
func (o *DecryptDataResponseDto) GetDecryptedData() []CipherResponseData {
	if o == nil {
		var ret []CipherResponseData
		return ret
	}

	return o.DecryptedData
}

// GetDecryptedDataOk returns a tuple with the DecryptedData field value
// and a boolean to check if the value has been set.
func (o *DecryptDataResponseDto) GetDecryptedDataOk() ([]CipherResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return o.DecryptedData, true
}

// SetDecryptedData sets field value
func (o *DecryptDataResponseDto) SetDecryptedData(v []CipherResponseData) {
	o.DecryptedData = v
}

func (o DecryptDataResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecryptDataResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["decryptedData"] = o.DecryptedData

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DecryptDataResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"decryptedData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDecryptDataResponseDto := _DecryptDataResponseDto{}

	err = json.Unmarshal(data, &varDecryptDataResponseDto)

	if err != nil {
		return err
	}

	*o = DecryptDataResponseDto(varDecryptDataResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "decryptedData")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDecryptDataResponseDto struct {
	value *DecryptDataResponseDto
	isSet bool
}

func (v NullableDecryptDataResponseDto) Get() *DecryptDataResponseDto {
	return v.value
}

func (v *NullableDecryptDataResponseDto) Set(val *DecryptDataResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDecryptDataResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDecryptDataResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecryptDataResponseDto(val *DecryptDataResponseDto) *NullableDecryptDataResponseDto {
	return &NullableDecryptDataResponseDto{value: val, isSet: true}
}

func (v NullableDecryptDataResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecryptDataResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


