/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// checks if the KeyStoreSecretContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyStoreSecretContent{}

// KeyStoreSecretContent Secret representing Key Store
type KeyStoreSecretContent struct {
	// Secret type
	Type SecretType `json:"type"`
	// Key Store type
	KeyStoreType KeyStoreType `json:"keyStoreType"`
	// BASE64 encoded content of key store
	Content string `json:"content"`
	// Password for key store
	Password string `json:"password"`
	AdditionalProperties map[string]interface{}
}

type _KeyStoreSecretContent KeyStoreSecretContent

// NewKeyStoreSecretContent instantiates a new KeyStoreSecretContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyStoreSecretContent(type_ SecretType, keyStoreType KeyStoreType, content string, password string) *KeyStoreSecretContent {
	this := KeyStoreSecretContent{}
	this.Type = type_
	this.KeyStoreType = keyStoreType
	this.Content = content
	this.Password = password
	return &this
}

// NewKeyStoreSecretContentWithDefaults instantiates a new KeyStoreSecretContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyStoreSecretContentWithDefaults() *KeyStoreSecretContent {
	this := KeyStoreSecretContent{}
	return &this
}

// GetType returns the Type field value
func (o *KeyStoreSecretContent) GetType() SecretType {
	if o == nil {
		var ret SecretType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *KeyStoreSecretContent) GetTypeOk() (*SecretType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *KeyStoreSecretContent) SetType(v SecretType) {
	o.Type = v
}

// GetKeyStoreType returns the KeyStoreType field value
func (o *KeyStoreSecretContent) GetKeyStoreType() KeyStoreType {
	if o == nil {
		var ret KeyStoreType
		return ret
	}

	return o.KeyStoreType
}

// GetKeyStoreTypeOk returns a tuple with the KeyStoreType field value
// and a boolean to check if the value has been set.
func (o *KeyStoreSecretContent) GetKeyStoreTypeOk() (*KeyStoreType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyStoreType, true
}

// SetKeyStoreType sets field value
func (o *KeyStoreSecretContent) SetKeyStoreType(v KeyStoreType) {
	o.KeyStoreType = v
}

// GetContent returns the Content field value
func (o *KeyStoreSecretContent) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *KeyStoreSecretContent) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *KeyStoreSecretContent) SetContent(v string) {
	o.Content = v
}

// GetPassword returns the Password field value
func (o *KeyStoreSecretContent) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *KeyStoreSecretContent) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *KeyStoreSecretContent) SetPassword(v string) {
	o.Password = v
}

func (o KeyStoreSecretContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyStoreSecretContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["keyStoreType"] = o.KeyStoreType
	toSerialize["content"] = o.Content
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KeyStoreSecretContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"keyStoreType",
		"content",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyStoreSecretContent := _KeyStoreSecretContent{}

	err = json.Unmarshal(data, &varKeyStoreSecretContent)

	if err != nil {
		return err
	}

	*o = KeyStoreSecretContent(varKeyStoreSecretContent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "keyStoreType")
		delete(additionalProperties, "content")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKeyStoreSecretContent struct {
	value *KeyStoreSecretContent
	isSet bool
}

func (v NullableKeyStoreSecretContent) Get() *KeyStoreSecretContent {
	return v.value
}

func (v *NullableKeyStoreSecretContent) Set(val *KeyStoreSecretContent) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyStoreSecretContent) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyStoreSecretContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyStoreSecretContent(val *KeyStoreSecretContent) *NullableKeyStoreSecretContent {
	return &NullableKeyStoreSecretContent{value: val, isSet: true}
}

func (v NullableKeyStoreSecretContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyStoreSecretContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


