/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"fmt"
)

// TokenInstanceStatus the model 'TokenInstanceStatus'
type TokenInstanceStatus string

// List of TokenInstanceStatus
const (
	TOKENINSTANCESTATUS_CONNECTED TokenInstanceStatus = "Connected"
	TOKENINSTANCESTATUS_DISCONNECTED TokenInstanceStatus = "Disconnected"
	TOKENINSTANCESTATUS_ACTIVATED TokenInstanceStatus = "Activated"
	TOKENINSTANCESTATUS_DEACTIVATED TokenInstanceStatus = "Deactivated"
	TOKENINSTANCESTATUS_WARNING TokenInstanceStatus = "Warning"
	TOKENINSTANCESTATUS_UNKNOWN TokenInstanceStatus = "Unknown"
)

// All allowed values of TokenInstanceStatus enum
var AllowedTokenInstanceStatusEnumValues = []TokenInstanceStatus{
	"Connected",
	"Disconnected",
	"Activated",
	"Deactivated",
	"Warning",
	"Unknown",
}

func (v *TokenInstanceStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TokenInstanceStatus(value)
	for _, existing := range AllowedTokenInstanceStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TokenInstanceStatus", value)
}

// NewTokenInstanceStatusFromValue returns a pointer to a valid TokenInstanceStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTokenInstanceStatusFromValue(v string) (*TokenInstanceStatus, error) {
	ev := TokenInstanceStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TokenInstanceStatus: valid values are %v", v, AllowedTokenInstanceStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TokenInstanceStatus) IsValid() bool {
	for _, existing := range AllowedTokenInstanceStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TokenInstanceStatus value
func (v TokenInstanceStatus) Ptr() *TokenInstanceStatus {
	return &v
}

type NullableTokenInstanceStatus struct {
	value *TokenInstanceStatus
	isSet bool
}

func (v NullableTokenInstanceStatus) Get() *TokenInstanceStatus {
	return v.value
}

func (v *NullableTokenInstanceStatus) Set(val *TokenInstanceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInstanceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInstanceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInstanceStatus(val *TokenInstanceStatus) *NullableTokenInstanceStatus {
	return &NullableTokenInstanceStatus{value: val, isSet: true}
}

func (v NullableTokenInstanceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInstanceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

