/*
Cryptography Provider API

REST API for implementations of custom Cryptography Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptography

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataAttributeV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataAttributeV2{}

// DataAttributeV2 Data attribute allows to store and transfer dynamic data. Its content can be edited and send in requests to store.
type DataAttributeV2 struct {
	// UUID of the Attribute for unique identification
	Uuid string `json:"uuid"`
	// Name of the Attribute that is used for identification
	Name string `json:"name"`
	// Optional description of the Attribute, should contain helper text on what is expected
	Description *string `json:"description,omitempty"`
	// Version of the attribute
	Version int32 `json:"version"`
	// Type of the Attribute
	Type AttributeType `json:"type"`
	// Content of the Attribute
	Content []BaseAttributeContentDtoV2 `json:"content,omitempty"`
	// Type of the Content
	ContentType AttributeContentType `json:"contentType"`
	// Properties of the Attributes
	Properties DataAttributeProperties `json:"properties"`
	// Optional constraints used for validating the Attribute content
	Constraints []BaseAttributeConstraint `json:"constraints,omitempty"`
	// Optional definition of callback for getting the content of the Attribute based on the action
	AttributeCallback *AttributeCallback `json:"attributeCallback,omitempty"`
}

type _DataAttributeV2 DataAttributeV2

// NewDataAttributeV2 instantiates a new DataAttributeV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataAttributeV2(uuid string, name string, version int32, type_ AttributeType, contentType AttributeContentType, properties DataAttributeProperties) *DataAttributeV2 {
	this := DataAttributeV2{}
	this.Uuid = uuid
	this.Name = name
	this.Version = version
	this.Type = type_
	this.ContentType = contentType
	this.Properties = properties
	return &this
}

// NewDataAttributeV2WithDefaults instantiates a new DataAttributeV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataAttributeV2WithDefaults() *DataAttributeV2 {
	this := DataAttributeV2{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *DataAttributeV2) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *DataAttributeV2) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *DataAttributeV2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataAttributeV2) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DataAttributeV2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DataAttributeV2) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DataAttributeV2) SetDescription(v string) {
	o.Description = &v
}

// GetVersion returns the Version field value
func (o *DataAttributeV2) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *DataAttributeV2) SetVersion(v int32) {
	o.Version = v
}

// GetType returns the Type field value
func (o *DataAttributeV2) GetType() AttributeType {
	if o == nil {
		var ret AttributeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetTypeOk() (*AttributeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DataAttributeV2) SetType(v AttributeType) {
	o.Type = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *DataAttributeV2) GetContent() []BaseAttributeContentDtoV2 {
	if o == nil || IsNil(o.Content) {
		var ret []BaseAttributeContentDtoV2
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetContentOk() ([]BaseAttributeContentDtoV2, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *DataAttributeV2) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []BaseAttributeContentDtoV2 and assigns it to the Content field.
func (o *DataAttributeV2) SetContent(v []BaseAttributeContentDtoV2) {
	o.Content = v
}

// GetContentType returns the ContentType field value
func (o *DataAttributeV2) GetContentType() AttributeContentType {
	if o == nil {
		var ret AttributeContentType
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetContentTypeOk() (*AttributeContentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *DataAttributeV2) SetContentType(v AttributeContentType) {
	o.ContentType = v
}

// GetProperties returns the Properties field value
func (o *DataAttributeV2) GetProperties() DataAttributeProperties {
	if o == nil {
		var ret DataAttributeProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetPropertiesOk() (*DataAttributeProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *DataAttributeV2) SetProperties(v DataAttributeProperties) {
	o.Properties = v
}

// GetConstraints returns the Constraints field value if set, zero value otherwise.
func (o *DataAttributeV2) GetConstraints() []BaseAttributeConstraint {
	if o == nil || IsNil(o.Constraints) {
		var ret []BaseAttributeConstraint
		return ret
	}
	return o.Constraints
}

// GetConstraintsOk returns a tuple with the Constraints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetConstraintsOk() ([]BaseAttributeConstraint, bool) {
	if o == nil || IsNil(o.Constraints) {
		return nil, false
	}
	return o.Constraints, true
}

// HasConstraints returns a boolean if a field has been set.
func (o *DataAttributeV2) HasConstraints() bool {
	if o != nil && !IsNil(o.Constraints) {
		return true
	}

	return false
}

// SetConstraints gets a reference to the given []BaseAttributeConstraint and assigns it to the Constraints field.
func (o *DataAttributeV2) SetConstraints(v []BaseAttributeConstraint) {
	o.Constraints = v
}

// GetAttributeCallback returns the AttributeCallback field value if set, zero value otherwise.
func (o *DataAttributeV2) GetAttributeCallback() AttributeCallback {
	if o == nil || IsNil(o.AttributeCallback) {
		var ret AttributeCallback
		return ret
	}
	return *o.AttributeCallback
}

// GetAttributeCallbackOk returns a tuple with the AttributeCallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataAttributeV2) GetAttributeCallbackOk() (*AttributeCallback, bool) {
	if o == nil || IsNil(o.AttributeCallback) {
		return nil, false
	}
	return o.AttributeCallback, true
}

// HasAttributeCallback returns a boolean if a field has been set.
func (o *DataAttributeV2) HasAttributeCallback() bool {
	if o != nil && !IsNil(o.AttributeCallback) {
		return true
	}

	return false
}

// SetAttributeCallback gets a reference to the given AttributeCallback and assigns it to the AttributeCallback field.
func (o *DataAttributeV2) SetAttributeCallback(v AttributeCallback) {
	o.AttributeCallback = &v
}

func (o DataAttributeV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataAttributeV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["version"] = o.Version
	toSerialize["type"] = o.Type
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	toSerialize["contentType"] = o.ContentType
	toSerialize["properties"] = o.Properties
	if !IsNil(o.Constraints) {
		toSerialize["constraints"] = o.Constraints
	}
	if !IsNil(o.AttributeCallback) {
		toSerialize["attributeCallback"] = o.AttributeCallback
	}
	return toSerialize, nil
}

func (o *DataAttributeV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"version",
		"type",
		"contentType",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataAttributeV2 := _DataAttributeV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataAttributeV2)

	if err != nil {
		return err
	}

	*o = DataAttributeV2(varDataAttributeV2)

	return err
}

type NullableDataAttributeV2 struct {
	value *DataAttributeV2
	isSet bool
}

func (v NullableDataAttributeV2) Get() *DataAttributeV2 {
	return v.value
}

func (v *NullableDataAttributeV2) Set(val *DataAttributeV2) {
	v.value = val
	v.isSet = true
}

func (v NullableDataAttributeV2) IsSet() bool {
	return v.isSet
}

func (v *NullableDataAttributeV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataAttributeV2(val *DataAttributeV2) *NullableDataAttributeV2 {
	return &NullableDataAttributeV2{value: val, isSet: true}
}

func (v NullableDataAttributeV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataAttributeV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


