/*
Credential Provider API

REST API for implementations of custom Credential Provider

API version: 2.18.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// SecretContent - Secret content dependent on secret type
type SecretContent struct {
	ApiKeySecretContent *ApiKeySecretContent
	BasicAuthSecretContent *BasicAuthSecretContent
	GenericSecretContent *GenericSecretContent
	JwtTokenSecretContent *JwtTokenSecretContent
	KeyStoreSecretContent *KeyStoreSecretContent
	KeyValueSecretContent *KeyValueSecretContent
	PrivateKeySecretContent *PrivateKeySecretContent
	SecretKeySecretContent *SecretKeySecretContent
}

// ApiKeySecretContentAsSecretContent is a convenience function that returns ApiKeySecretContent wrapped in SecretContent
func ApiKeySecretContentAsSecretContent(v *ApiKeySecretContent) SecretContent {
	return SecretContent{
		ApiKeySecretContent: v,
	}
}

// BasicAuthSecretContentAsSecretContent is a convenience function that returns BasicAuthSecretContent wrapped in SecretContent
func BasicAuthSecretContentAsSecretContent(v *BasicAuthSecretContent) SecretContent {
	return SecretContent{
		BasicAuthSecretContent: v,
	}
}

// GenericSecretContentAsSecretContent is a convenience function that returns GenericSecretContent wrapped in SecretContent
func GenericSecretContentAsSecretContent(v *GenericSecretContent) SecretContent {
	return SecretContent{
		GenericSecretContent: v,
	}
}

// JwtTokenSecretContentAsSecretContent is a convenience function that returns JwtTokenSecretContent wrapped in SecretContent
func JwtTokenSecretContentAsSecretContent(v *JwtTokenSecretContent) SecretContent {
	return SecretContent{
		JwtTokenSecretContent: v,
	}
}

// KeyStoreSecretContentAsSecretContent is a convenience function that returns KeyStoreSecretContent wrapped in SecretContent
func KeyStoreSecretContentAsSecretContent(v *KeyStoreSecretContent) SecretContent {
	return SecretContent{
		KeyStoreSecretContent: v,
	}
}

// KeyValueSecretContentAsSecretContent is a convenience function that returns KeyValueSecretContent wrapped in SecretContent
func KeyValueSecretContentAsSecretContent(v *KeyValueSecretContent) SecretContent {
	return SecretContent{
		KeyValueSecretContent: v,
	}
}

// PrivateKeySecretContentAsSecretContent is a convenience function that returns PrivateKeySecretContent wrapped in SecretContent
func PrivateKeySecretContentAsSecretContent(v *PrivateKeySecretContent) SecretContent {
	return SecretContent{
		PrivateKeySecretContent: v,
	}
}

// SecretKeySecretContentAsSecretContent is a convenience function that returns SecretKeySecretContent wrapped in SecretContent
func SecretKeySecretContentAsSecretContent(v *SecretKeySecretContent) SecretContent {
	return SecretContent{
		SecretKeySecretContent: v,
	}
}


// UnmarshalJSON decodes SecretContent by switching on the JSON "type" field.
// Patched by tools/fixoneof — the generator's match-counting decoder
// fails on this oneOf because multiple variants share the same Go struct
// shape and pass strict decode simultaneously.
func (dst *SecretContent) UnmarshalJSON(data []byte) error {
	var probe struct {
		Disc string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("SecretContent: probe type: %w", err)
	}
	disc := probe.Disc
	dst.ApiKeySecretContent = nil
	dst.BasicAuthSecretContent = nil
	dst.GenericSecretContent = nil
	dst.JwtTokenSecretContent = nil
	dst.KeyStoreSecretContent = nil
	dst.KeyValueSecretContent = nil
	dst.PrivateKeySecretContent = nil
	dst.SecretKeySecretContent = nil
	switch disc {
	case "apiKey":
		var v ApiKeySecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode ApiKeySecretContent: %w", err)
		}
		dst.ApiKeySecretContent = &v
		return nil
	case "basicAuth":
		var v BasicAuthSecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode BasicAuthSecretContent: %w", err)
		}
		dst.BasicAuthSecretContent = &v
		return nil
	case "generic":
		var v GenericSecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode GenericSecretContent: %w", err)
		}
		dst.GenericSecretContent = &v
		return nil
	case "jwtToken":
		var v JwtTokenSecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode JwtTokenSecretContent: %w", err)
		}
		dst.JwtTokenSecretContent = &v
		return nil
	case "keyStore":
		var v KeyStoreSecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode KeyStoreSecretContent: %w", err)
		}
		dst.KeyStoreSecretContent = &v
		return nil
	case "keyValue":
		var v KeyValueSecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode KeyValueSecretContent: %w", err)
		}
		dst.KeyValueSecretContent = &v
		return nil
	case "privateKey":
		var v PrivateKeySecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode PrivateKeySecretContent: %w", err)
		}
		dst.PrivateKeySecretContent = &v
		return nil
	case "secretKey":
		var v SecretKeySecretContent
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("SecretContent: decode SecretKeySecretContent: %w", err)
		}
		dst.SecretKeySecretContent = &v
		return nil
	default:
		return fmt.Errorf("SecretContent: unknown type %q", disc)
	}
}


// Marshal data from the first non-nil pointers in the struct to JSON
func (src SecretContent) MarshalJSON() ([]byte, error) {
	if src.ApiKeySecretContent != nil {
		return json.Marshal(&src.ApiKeySecretContent)
	}

	if src.BasicAuthSecretContent != nil {
		return json.Marshal(&src.BasicAuthSecretContent)
	}

	if src.GenericSecretContent != nil {
		return json.Marshal(&src.GenericSecretContent)
	}

	if src.JwtTokenSecretContent != nil {
		return json.Marshal(&src.JwtTokenSecretContent)
	}

	if src.KeyStoreSecretContent != nil {
		return json.Marshal(&src.KeyStoreSecretContent)
	}

	if src.KeyValueSecretContent != nil {
		return json.Marshal(&src.KeyValueSecretContent)
	}

	if src.PrivateKeySecretContent != nil {
		return json.Marshal(&src.PrivateKeySecretContent)
	}

	if src.SecretKeySecretContent != nil {
		return json.Marshal(&src.SecretKeySecretContent)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SecretContent) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ApiKeySecretContent != nil {
		return obj.ApiKeySecretContent
	}

	if obj.BasicAuthSecretContent != nil {
		return obj.BasicAuthSecretContent
	}

	if obj.GenericSecretContent != nil {
		return obj.GenericSecretContent
	}

	if obj.JwtTokenSecretContent != nil {
		return obj.JwtTokenSecretContent
	}

	if obj.KeyStoreSecretContent != nil {
		return obj.KeyStoreSecretContent
	}

	if obj.KeyValueSecretContent != nil {
		return obj.KeyValueSecretContent
	}

	if obj.PrivateKeySecretContent != nil {
		return obj.PrivateKeySecretContent
	}

	if obj.SecretKeySecretContent != nil {
		return obj.SecretKeySecretContent
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SecretContent) GetActualInstanceValue() (interface{}) {
	if obj.ApiKeySecretContent != nil {
		return *obj.ApiKeySecretContent
	}

	if obj.BasicAuthSecretContent != nil {
		return *obj.BasicAuthSecretContent
	}

	if obj.GenericSecretContent != nil {
		return *obj.GenericSecretContent
	}

	if obj.JwtTokenSecretContent != nil {
		return *obj.JwtTokenSecretContent
	}

	if obj.KeyStoreSecretContent != nil {
		return *obj.KeyStoreSecretContent
	}

	if obj.KeyValueSecretContent != nil {
		return *obj.KeyValueSecretContent
	}

	if obj.PrivateKeySecretContent != nil {
		return *obj.PrivateKeySecretContent
	}

	if obj.SecretKeySecretContent != nil {
		return *obj.SecretKeySecretContent
	}

	// all schemas are nil
	return nil
}

type NullableSecretContent struct {
	value *SecretContent
	isSet bool
}

func (v NullableSecretContent) Get() *SecretContent {
	return v.value
}

func (v *NullableSecretContent) Set(val *SecretContent) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretContent) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretContent(val *SecretContent) *NullableSecretContent {
	return &NullableSecretContent{value: val, isSet: true}
}

func (v NullableSecretContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


