/*
Secret Provider API

REST API for implementations of custom Secret Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secret

import (
	"encoding/json"
	"fmt"
)

// FeatureFlag the model 'FeatureFlag'
type FeatureFlag string

// List of FeatureFlag
const (
	FEATUREFLAG_STATELESS FeatureFlag = "stateless"
	FEATUREFLAG_OPEN_METRICS FeatureFlag = "openMetrics"
	FEATUREFLAG_SECRET_VERSIONING FeatureFlag = "secretVersioning"
	FEATUREFLAG_SECRET_ROTATION FeatureFlag = "secretRotation"
)

// All allowed values of FeatureFlag enum
var AllowedFeatureFlagEnumValues = []FeatureFlag{
	"stateless",
	"openMetrics",
	"secretVersioning",
	"secretRotation",
}

func (v *FeatureFlag) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FeatureFlag(value)
	for _, existing := range AllowedFeatureFlagEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FeatureFlag", value)
}

// NewFeatureFlagFromValue returns a pointer to a valid FeatureFlag
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFeatureFlagFromValue(v string) (*FeatureFlag, error) {
	ev := FeatureFlag(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FeatureFlag: valid values are %v", v, AllowedFeatureFlagEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FeatureFlag) IsValid() bool {
	for _, existing := range AllowedFeatureFlagEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FeatureFlag value
func (v FeatureFlag) Ptr() *FeatureFlag {
	return &v
}

type NullableFeatureFlag struct {
	value *FeatureFlag
	isSet bool
}

func (v NullableFeatureFlag) Get() *FeatureFlag {
	return v.value
}

func (v *NullableFeatureFlag) Set(val *FeatureFlag) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureFlag) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureFlag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureFlag(val *FeatureFlag) *NullableFeatureFlag {
	return &NullableFeatureFlag{value: val, isSet: true}
}

func (v NullableFeatureFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureFlag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

