/*
Secret Provider API

REST API for implementations of custom Secret Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secret

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSecretRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSecretRequestDto{}

// CreateSecretRequestDto Create Secret request
type CreateSecretRequestDto struct {
	// Name of the secret
	Name string `json:"name"`
	// Secret content
	Secret SecretContent `json:"secret"`
	// Vault attributes
	VaultAttributes []RequestAttribute `json:"vaultAttributes,omitempty"`
	// Vault profile attributes
	VaultProfileAttributes []RequestAttribute `json:"vaultProfileAttributes,omitempty"`
	// Secret attributes
	SecretAttributes []RequestAttribute `json:"secretAttributes,omitempty"`
}

type _CreateSecretRequestDto CreateSecretRequestDto

// NewCreateSecretRequestDto instantiates a new CreateSecretRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSecretRequestDto(name string, secret SecretContent) *CreateSecretRequestDto {
	this := CreateSecretRequestDto{}
	this.Name = name
	this.Secret = secret
	return &this
}

// NewCreateSecretRequestDtoWithDefaults instantiates a new CreateSecretRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSecretRequestDtoWithDefaults() *CreateSecretRequestDto {
	this := CreateSecretRequestDto{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSecretRequestDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSecretRequestDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSecretRequestDto) SetName(v string) {
	o.Name = v
}

// GetSecret returns the Secret field value
func (o *CreateSecretRequestDto) GetSecret() SecretContent {
	if o == nil {
		var ret SecretContent
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *CreateSecretRequestDto) GetSecretOk() (*SecretContent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *CreateSecretRequestDto) SetSecret(v SecretContent) {
	o.Secret = v
}

// GetVaultAttributes returns the VaultAttributes field value if set, zero value otherwise.
func (o *CreateSecretRequestDto) GetVaultAttributes() []RequestAttribute {
	if o == nil || IsNil(o.VaultAttributes) {
		var ret []RequestAttribute
		return ret
	}
	return o.VaultAttributes
}

// GetVaultAttributesOk returns a tuple with the VaultAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSecretRequestDto) GetVaultAttributesOk() ([]RequestAttribute, bool) {
	if o == nil || IsNil(o.VaultAttributes) {
		return nil, false
	}
	return o.VaultAttributes, true
}

// HasVaultAttributes returns a boolean if a field has been set.
func (o *CreateSecretRequestDto) HasVaultAttributes() bool {
	if o != nil && !IsNil(o.VaultAttributes) {
		return true
	}

	return false
}

// SetVaultAttributes gets a reference to the given []RequestAttribute and assigns it to the VaultAttributes field.
func (o *CreateSecretRequestDto) SetVaultAttributes(v []RequestAttribute) {
	o.VaultAttributes = v
}

// GetVaultProfileAttributes returns the VaultProfileAttributes field value if set, zero value otherwise.
func (o *CreateSecretRequestDto) GetVaultProfileAttributes() []RequestAttribute {
	if o == nil || IsNil(o.VaultProfileAttributes) {
		var ret []RequestAttribute
		return ret
	}
	return o.VaultProfileAttributes
}

// GetVaultProfileAttributesOk returns a tuple with the VaultProfileAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSecretRequestDto) GetVaultProfileAttributesOk() ([]RequestAttribute, bool) {
	if o == nil || IsNil(o.VaultProfileAttributes) {
		return nil, false
	}
	return o.VaultProfileAttributes, true
}

// HasVaultProfileAttributes returns a boolean if a field has been set.
func (o *CreateSecretRequestDto) HasVaultProfileAttributes() bool {
	if o != nil && !IsNil(o.VaultProfileAttributes) {
		return true
	}

	return false
}

// SetVaultProfileAttributes gets a reference to the given []RequestAttribute and assigns it to the VaultProfileAttributes field.
func (o *CreateSecretRequestDto) SetVaultProfileAttributes(v []RequestAttribute) {
	o.VaultProfileAttributes = v
}

// GetSecretAttributes returns the SecretAttributes field value if set, zero value otherwise.
func (o *CreateSecretRequestDto) GetSecretAttributes() []RequestAttribute {
	if o == nil || IsNil(o.SecretAttributes) {
		var ret []RequestAttribute
		return ret
	}
	return o.SecretAttributes
}

// GetSecretAttributesOk returns a tuple with the SecretAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSecretRequestDto) GetSecretAttributesOk() ([]RequestAttribute, bool) {
	if o == nil || IsNil(o.SecretAttributes) {
		return nil, false
	}
	return o.SecretAttributes, true
}

// HasSecretAttributes returns a boolean if a field has been set.
func (o *CreateSecretRequestDto) HasSecretAttributes() bool {
	if o != nil && !IsNil(o.SecretAttributes) {
		return true
	}

	return false
}

// SetSecretAttributes gets a reference to the given []RequestAttribute and assigns it to the SecretAttributes field.
func (o *CreateSecretRequestDto) SetSecretAttributes(v []RequestAttribute) {
	o.SecretAttributes = v
}

func (o CreateSecretRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSecretRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["secret"] = o.Secret
	if !IsNil(o.VaultAttributes) {
		toSerialize["vaultAttributes"] = o.VaultAttributes
	}
	if !IsNil(o.VaultProfileAttributes) {
		toSerialize["vaultProfileAttributes"] = o.VaultProfileAttributes
	}
	if !IsNil(o.SecretAttributes) {
		toSerialize["secretAttributes"] = o.SecretAttributes
	}
	return toSerialize, nil
}

func (o *CreateSecretRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSecretRequestDto := _CreateSecretRequestDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSecretRequestDto)

	if err != nil {
		return err
	}

	*o = CreateSecretRequestDto(varCreateSecretRequestDto)

	return err
}

type NullableCreateSecretRequestDto struct {
	value *CreateSecretRequestDto
	isSet bool
}

func (v NullableCreateSecretRequestDto) Get() *CreateSecretRequestDto {
	return v.value
}

func (v *NullableCreateSecretRequestDto) Set(val *CreateSecretRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSecretRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSecretRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSecretRequestDto(val *CreateSecretRequestDto) *NullableCreateSecretRequestDto {
	return &NullableCreateSecretRequestDto{value: val, isSet: true}
}

func (v NullableCreateSecretRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSecretRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


