/*
Secret Provider API

REST API for implementations of custom Secret Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secret

import (
	"encoding/json"
	"fmt"
)

// checks if the KeyValueSecretContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyValueSecretContent{}

// KeyValueSecretContent Secret representing key-value pairs
type KeyValueSecretContent struct {
	// Secret type
	Type SecretType `json:"type"`
	// Key-Value pairs stored as the secret content, represented by JSON object
	Content map[string]interface{} `json:"content"`
	AdditionalProperties map[string]interface{}
}

type _KeyValueSecretContent KeyValueSecretContent

// NewKeyValueSecretContent instantiates a new KeyValueSecretContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyValueSecretContent(type_ SecretType, content map[string]interface{}) *KeyValueSecretContent {
	this := KeyValueSecretContent{}
	this.Type = type_
	this.Content = content
	return &this
}

// NewKeyValueSecretContentWithDefaults instantiates a new KeyValueSecretContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyValueSecretContentWithDefaults() *KeyValueSecretContent {
	this := KeyValueSecretContent{}
	return &this
}

// GetType returns the Type field value
func (o *KeyValueSecretContent) GetType() SecretType {
	if o == nil {
		var ret SecretType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *KeyValueSecretContent) GetTypeOk() (*SecretType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *KeyValueSecretContent) SetType(v SecretType) {
	o.Type = v
}

// GetContent returns the Content field value
func (o *KeyValueSecretContent) GetContent() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *KeyValueSecretContent) GetContentOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Content, true
}

// SetContent sets field value
func (o *KeyValueSecretContent) SetContent(v map[string]interface{}) {
	o.Content = v
}

func (o KeyValueSecretContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyValueSecretContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["content"] = o.Content

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KeyValueSecretContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyValueSecretContent := _KeyValueSecretContent{}

	err = json.Unmarshal(data, &varKeyValueSecretContent)

	if err != nil {
		return err
	}

	*o = KeyValueSecretContent(varKeyValueSecretContent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "content")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKeyValueSecretContent struct {
	value *KeyValueSecretContent
	isSet bool
}

func (v NullableKeyValueSecretContent) Get() *KeyValueSecretContent {
	return v.value
}

func (v *NullableKeyValueSecretContent) Set(val *KeyValueSecretContent) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyValueSecretContent) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyValueSecretContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyValueSecretContent(val *KeyValueSecretContent) *NullableKeyValueSecretContent {
	return &NullableKeyValueSecretContent{value: val, isSet: true}
}

func (v NullableKeyValueSecretContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyValueSecretContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


