/*
Secret Provider API

REST API for implementations of custom Secret Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secret

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ResourceObjectContentData - struct for ResourceObjectContentData
type ResourceObjectContentData struct {
	ResourceCertificateContentData *ResourceCertificateContentData
	ResourceSecretContentData *ResourceSecretContentData
	ResourceSimpleContentData *ResourceSimpleContentData
}

// ResourceCertificateContentDataAsResourceObjectContentData is a convenience function that returns ResourceCertificateContentData wrapped in ResourceObjectContentData
func ResourceCertificateContentDataAsResourceObjectContentData(v *ResourceCertificateContentData) ResourceObjectContentData {
	return ResourceObjectContentData{
		ResourceCertificateContentData: v,
	}
}

// ResourceSecretContentDataAsResourceObjectContentData is a convenience function that returns ResourceSecretContentData wrapped in ResourceObjectContentData
func ResourceSecretContentDataAsResourceObjectContentData(v *ResourceSecretContentData) ResourceObjectContentData {
	return ResourceObjectContentData{
		ResourceSecretContentData: v,
	}
}

// ResourceSimpleContentDataAsResourceObjectContentData is a convenience function that returns ResourceSimpleContentData wrapped in ResourceObjectContentData
func ResourceSimpleContentDataAsResourceObjectContentData(v *ResourceSimpleContentData) ResourceObjectContentData {
	return ResourceObjectContentData{
		ResourceSimpleContentData: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ResourceObjectContentData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ResourceCertificateContentData
	err = newStrictDecoder(data).Decode(&dst.ResourceCertificateContentData)
	if err == nil {
		jsonResourceCertificateContentData, _ := json.Marshal(dst.ResourceCertificateContentData)
		if string(jsonResourceCertificateContentData) == "{}" { // empty struct
			dst.ResourceCertificateContentData = nil
		} else {
			if err = validator.Validate(dst.ResourceCertificateContentData); err != nil {
				dst.ResourceCertificateContentData = nil
			} else {
				match++
			}
		}
	} else {
		dst.ResourceCertificateContentData = nil
	}

	// try to unmarshal data into ResourceSecretContentData
	err = newStrictDecoder(data).Decode(&dst.ResourceSecretContentData)
	if err == nil {
		jsonResourceSecretContentData, _ := json.Marshal(dst.ResourceSecretContentData)
		if string(jsonResourceSecretContentData) == "{}" { // empty struct
			dst.ResourceSecretContentData = nil
		} else {
			if err = validator.Validate(dst.ResourceSecretContentData); err != nil {
				dst.ResourceSecretContentData = nil
			} else {
				match++
			}
		}
	} else {
		dst.ResourceSecretContentData = nil
	}

	// try to unmarshal data into ResourceSimpleContentData
	err = newStrictDecoder(data).Decode(&dst.ResourceSimpleContentData)
	if err == nil {
		jsonResourceSimpleContentData, _ := json.Marshal(dst.ResourceSimpleContentData)
		if string(jsonResourceSimpleContentData) == "{}" { // empty struct
			dst.ResourceSimpleContentData = nil
		} else {
			if err = validator.Validate(dst.ResourceSimpleContentData); err != nil {
				dst.ResourceSimpleContentData = nil
			} else {
				match++
			}
		}
	} else {
		dst.ResourceSimpleContentData = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ResourceCertificateContentData = nil
		dst.ResourceSecretContentData = nil
		dst.ResourceSimpleContentData = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ResourceObjectContentData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ResourceObjectContentData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResourceObjectContentData) MarshalJSON() ([]byte, error) {
	if src.ResourceCertificateContentData != nil {
		return json.Marshal(&src.ResourceCertificateContentData)
	}

	if src.ResourceSecretContentData != nil {
		return json.Marshal(&src.ResourceSecretContentData)
	}

	if src.ResourceSimpleContentData != nil {
		return json.Marshal(&src.ResourceSimpleContentData)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ResourceObjectContentData) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ResourceCertificateContentData != nil {
		return obj.ResourceCertificateContentData
	}

	if obj.ResourceSecretContentData != nil {
		return obj.ResourceSecretContentData
	}

	if obj.ResourceSimpleContentData != nil {
		return obj.ResourceSimpleContentData
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ResourceObjectContentData) GetActualInstanceValue() (interface{}) {
	if obj.ResourceCertificateContentData != nil {
		return *obj.ResourceCertificateContentData
	}

	if obj.ResourceSecretContentData != nil {
		return *obj.ResourceSecretContentData
	}

	if obj.ResourceSimpleContentData != nil {
		return *obj.ResourceSimpleContentData
	}

	// all schemas are nil
	return nil
}

type NullableResourceObjectContentData struct {
	value *ResourceObjectContentData
	isSet bool
}

func (v NullableResourceObjectContentData) Get() *ResourceObjectContentData {
	return v.value
}

func (v *NullableResourceObjectContentData) Set(val *ResourceObjectContentData) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceObjectContentData) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceObjectContentData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceObjectContentData(val *ResourceObjectContentData) *NullableResourceObjectContentData {
	return &NullableResourceObjectContentData{value: val, isSet: true}
}

func (v NullableResourceObjectContentData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceObjectContentData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


