/*
Secret Provider API

REST API for implementations of custom Secret Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secret

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecretRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretRequestDto{}

// SecretRequestDto Secret request
type SecretRequestDto struct {
	// Name of the secret
	Name string `json:"name"`
	// Secret type
	Type SecretType `json:"type"`
	// Vault attributes
	VaultAttributes []RequestAttribute `json:"vaultAttributes,omitempty"`
	// Vault profile attributes
	VaultProfileAttributes []RequestAttribute `json:"vaultProfileAttributes,omitempty"`
	// Secret attributes
	SecretAttributes []RequestAttribute `json:"secretAttributes,omitempty"`
	// Metadata for the secret
	Metadata []MetadataAttribute `json:"metadata,omitempty"`
}

type _SecretRequestDto SecretRequestDto

// NewSecretRequestDto instantiates a new SecretRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretRequestDto(name string, type_ SecretType) *SecretRequestDto {
	this := SecretRequestDto{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewSecretRequestDtoWithDefaults instantiates a new SecretRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretRequestDtoWithDefaults() *SecretRequestDto {
	this := SecretRequestDto{}
	return &this
}

// GetName returns the Name field value
func (o *SecretRequestDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SecretRequestDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SecretRequestDto) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *SecretRequestDto) GetType() SecretType {
	if o == nil {
		var ret SecretType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SecretRequestDto) GetTypeOk() (*SecretType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SecretRequestDto) SetType(v SecretType) {
	o.Type = v
}

// GetVaultAttributes returns the VaultAttributes field value if set, zero value otherwise.
func (o *SecretRequestDto) GetVaultAttributes() []RequestAttribute {
	if o == nil || IsNil(o.VaultAttributes) {
		var ret []RequestAttribute
		return ret
	}
	return o.VaultAttributes
}

// GetVaultAttributesOk returns a tuple with the VaultAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRequestDto) GetVaultAttributesOk() ([]RequestAttribute, bool) {
	if o == nil || IsNil(o.VaultAttributes) {
		return nil, false
	}
	return o.VaultAttributes, true
}

// HasVaultAttributes returns a boolean if a field has been set.
func (o *SecretRequestDto) HasVaultAttributes() bool {
	if o != nil && !IsNil(o.VaultAttributes) {
		return true
	}

	return false
}

// SetVaultAttributes gets a reference to the given []RequestAttribute and assigns it to the VaultAttributes field.
func (o *SecretRequestDto) SetVaultAttributes(v []RequestAttribute) {
	o.VaultAttributes = v
}

// GetVaultProfileAttributes returns the VaultProfileAttributes field value if set, zero value otherwise.
func (o *SecretRequestDto) GetVaultProfileAttributes() []RequestAttribute {
	if o == nil || IsNil(o.VaultProfileAttributes) {
		var ret []RequestAttribute
		return ret
	}
	return o.VaultProfileAttributes
}

// GetVaultProfileAttributesOk returns a tuple with the VaultProfileAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRequestDto) GetVaultProfileAttributesOk() ([]RequestAttribute, bool) {
	if o == nil || IsNil(o.VaultProfileAttributes) {
		return nil, false
	}
	return o.VaultProfileAttributes, true
}

// HasVaultProfileAttributes returns a boolean if a field has been set.
func (o *SecretRequestDto) HasVaultProfileAttributes() bool {
	if o != nil && !IsNil(o.VaultProfileAttributes) {
		return true
	}

	return false
}

// SetVaultProfileAttributes gets a reference to the given []RequestAttribute and assigns it to the VaultProfileAttributes field.
func (o *SecretRequestDto) SetVaultProfileAttributes(v []RequestAttribute) {
	o.VaultProfileAttributes = v
}

// GetSecretAttributes returns the SecretAttributes field value if set, zero value otherwise.
func (o *SecretRequestDto) GetSecretAttributes() []RequestAttribute {
	if o == nil || IsNil(o.SecretAttributes) {
		var ret []RequestAttribute
		return ret
	}
	return o.SecretAttributes
}

// GetSecretAttributesOk returns a tuple with the SecretAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRequestDto) GetSecretAttributesOk() ([]RequestAttribute, bool) {
	if o == nil || IsNil(o.SecretAttributes) {
		return nil, false
	}
	return o.SecretAttributes, true
}

// HasSecretAttributes returns a boolean if a field has been set.
func (o *SecretRequestDto) HasSecretAttributes() bool {
	if o != nil && !IsNil(o.SecretAttributes) {
		return true
	}

	return false
}

// SetSecretAttributes gets a reference to the given []RequestAttribute and assigns it to the SecretAttributes field.
func (o *SecretRequestDto) SetSecretAttributes(v []RequestAttribute) {
	o.SecretAttributes = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *SecretRequestDto) GetMetadata() []MetadataAttribute {
	if o == nil || IsNil(o.Metadata) {
		var ret []MetadataAttribute
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRequestDto) GetMetadataOk() ([]MetadataAttribute, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SecretRequestDto) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []MetadataAttribute and assigns it to the Metadata field.
func (o *SecretRequestDto) SetMetadata(v []MetadataAttribute) {
	o.Metadata = v
}

func (o SecretRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.VaultAttributes) {
		toSerialize["vaultAttributes"] = o.VaultAttributes
	}
	if !IsNil(o.VaultProfileAttributes) {
		toSerialize["vaultProfileAttributes"] = o.VaultProfileAttributes
	}
	if !IsNil(o.SecretAttributes) {
		toSerialize["secretAttributes"] = o.SecretAttributes
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *SecretRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretRequestDto := _SecretRequestDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretRequestDto)

	if err != nil {
		return err
	}

	*o = SecretRequestDto(varSecretRequestDto)

	return err
}

type NullableSecretRequestDto struct {
	value *SecretRequestDto
	isSet bool
}

func (v NullableSecretRequestDto) Get() *SecretRequestDto {
	return v.value
}

func (v *NullableSecretRequestDto) Set(val *SecretRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretRequestDto(val *SecretRequestDto) *NullableSecretRequestDto {
	return &NullableSecretRequestDto{value: val, isSet: true}
}

func (v NullableSecretRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


