/*
Secret Provider API

REST API for implementations of custom Secret Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secret

import (
	"encoding/json"
	"fmt"
)

// checks if the HealthInfoComponent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthInfoComponent{}

// HealthInfoComponent struct for HealthInfoComponent
type HealthInfoComponent struct {
	// Current status of component
	Status HealthStatus `json:"status"`
	// Additional details about the component status
	Details map[string]interface{} `json:"details,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HealthInfoComponent HealthInfoComponent

// NewHealthInfoComponent instantiates a new HealthInfoComponent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthInfoComponent(status HealthStatus) *HealthInfoComponent {
	this := HealthInfoComponent{}
	this.Status = status
	return &this
}

// NewHealthInfoComponentWithDefaults instantiates a new HealthInfoComponent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthInfoComponentWithDefaults() *HealthInfoComponent {
	this := HealthInfoComponent{}
	return &this
}

// GetStatus returns the Status field value
func (o *HealthInfoComponent) GetStatus() HealthStatus {
	if o == nil {
		var ret HealthStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HealthInfoComponent) GetStatusOk() (*HealthStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HealthInfoComponent) SetStatus(v HealthStatus) {
	o.Status = v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *HealthInfoComponent) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthInfoComponent) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *HealthInfoComponent) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *HealthInfoComponent) SetDetails(v map[string]interface{}) {
	o.Details = v
}

func (o HealthInfoComponent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthInfoComponent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HealthInfoComponent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthInfoComponent := _HealthInfoComponent{}

	err = json.Unmarshal(data, &varHealthInfoComponent)

	if err != nil {
		return err
	}

	*o = HealthInfoComponent(varHealthInfoComponent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "details")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHealthInfoComponent struct {
	value *HealthInfoComponent
	isSet bool
}

func (v NullableHealthInfoComponent) Get() *HealthInfoComponent {
	return v.value
}

func (v *NullableHealthInfoComponent) Set(val *HealthInfoComponent) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthInfoComponent) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthInfoComponent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthInfoComponent(val *HealthInfoComponent) *NullableHealthInfoComponent {
	return &NullableHealthInfoComponent{value: val, isSet: true}
}

func (v NullableHealthInfoComponent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthInfoComponent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


