/*
Discovery Provider API

REST API for implementations of custom Discovery Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discovery

import (
	"encoding/json"
	"fmt"
)

// checks if the DiscoveryProviderDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscoveryProviderDto{}

// DiscoveryProviderDto struct for DiscoveryProviderDto
type DiscoveryProviderDto struct {
	// Object identifier
	Uuid string `json:"uuid"`
	// Object Name
	Name string `json:"name"`
	// Status of Discovery
	Status DiscoveryStatus `json:"status"`
	// Number of Certificates discovered
	TotalCertificatesDiscovered *int32 `json:"totalCertificatesDiscovered,omitempty"`
	// Certificate data
	CertificateData []DiscoveryProviderCertificateDataDto `json:"certificateData"`
	// Certificate Metadata
	Meta []MetadataAttribute `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _DiscoveryProviderDto DiscoveryProviderDto

// NewDiscoveryProviderDto instantiates a new DiscoveryProviderDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoveryProviderDto(uuid string, name string, status DiscoveryStatus, certificateData []DiscoveryProviderCertificateDataDto, meta []MetadataAttribute) *DiscoveryProviderDto {
	this := DiscoveryProviderDto{}
	this.Uuid = uuid
	this.Name = name
	this.Status = status
	var totalCertificatesDiscovered int32 = 0
	this.TotalCertificatesDiscovered = &totalCertificatesDiscovered
	this.CertificateData = certificateData
	this.Meta = meta
	return &this
}

// NewDiscoveryProviderDtoWithDefaults instantiates a new DiscoveryProviderDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoveryProviderDtoWithDefaults() *DiscoveryProviderDto {
	this := DiscoveryProviderDto{}
	var totalCertificatesDiscovered int32 = 0
	this.TotalCertificatesDiscovered = &totalCertificatesDiscovered
	return &this
}

// GetUuid returns the Uuid field value
func (o *DiscoveryProviderDto) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *DiscoveryProviderDto) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *DiscoveryProviderDto) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *DiscoveryProviderDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DiscoveryProviderDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DiscoveryProviderDto) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *DiscoveryProviderDto) GetStatus() DiscoveryStatus {
	if o == nil {
		var ret DiscoveryStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DiscoveryProviderDto) GetStatusOk() (*DiscoveryStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DiscoveryProviderDto) SetStatus(v DiscoveryStatus) {
	o.Status = v
}

// GetTotalCertificatesDiscovered returns the TotalCertificatesDiscovered field value if set, zero value otherwise.
func (o *DiscoveryProviderDto) GetTotalCertificatesDiscovered() int32 {
	if o == nil || IsNil(o.TotalCertificatesDiscovered) {
		var ret int32
		return ret
	}
	return *o.TotalCertificatesDiscovered
}

// GetTotalCertificatesDiscoveredOk returns a tuple with the TotalCertificatesDiscovered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveryProviderDto) GetTotalCertificatesDiscoveredOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCertificatesDiscovered) {
		return nil, false
	}
	return o.TotalCertificatesDiscovered, true
}

// HasTotalCertificatesDiscovered returns a boolean if a field has been set.
func (o *DiscoveryProviderDto) HasTotalCertificatesDiscovered() bool {
	if o != nil && !IsNil(o.TotalCertificatesDiscovered) {
		return true
	}

	return false
}

// SetTotalCertificatesDiscovered gets a reference to the given int32 and assigns it to the TotalCertificatesDiscovered field.
func (o *DiscoveryProviderDto) SetTotalCertificatesDiscovered(v int32) {
	o.TotalCertificatesDiscovered = &v
}

// GetCertificateData returns the CertificateData field value
func (o *DiscoveryProviderDto) GetCertificateData() []DiscoveryProviderCertificateDataDto {
	if o == nil {
		var ret []DiscoveryProviderCertificateDataDto
		return ret
	}

	return o.CertificateData
}

// GetCertificateDataOk returns a tuple with the CertificateData field value
// and a boolean to check if the value has been set.
func (o *DiscoveryProviderDto) GetCertificateDataOk() ([]DiscoveryProviderCertificateDataDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertificateData, true
}

// SetCertificateData sets field value
func (o *DiscoveryProviderDto) SetCertificateData(v []DiscoveryProviderCertificateDataDto) {
	o.CertificateData = v
}

// GetMeta returns the Meta field value
func (o *DiscoveryProviderDto) GetMeta() []MetadataAttribute {
	if o == nil {
		var ret []MetadataAttribute
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *DiscoveryProviderDto) GetMetaOk() ([]MetadataAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *DiscoveryProviderDto) SetMeta(v []MetadataAttribute) {
	o.Meta = v
}

func (o DiscoveryProviderDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscoveryProviderDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	if !IsNil(o.TotalCertificatesDiscovered) {
		toSerialize["totalCertificatesDiscovered"] = o.TotalCertificatesDiscovered
	}
	toSerialize["certificateData"] = o.CertificateData
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DiscoveryProviderDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"status",
		"certificateData",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiscoveryProviderDto := _DiscoveryProviderDto{}

	err = json.Unmarshal(data, &varDiscoveryProviderDto)

	if err != nil {
		return err
	}

	*o = DiscoveryProviderDto(varDiscoveryProviderDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "totalCertificatesDiscovered")
		delete(additionalProperties, "certificateData")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDiscoveryProviderDto struct {
	value *DiscoveryProviderDto
	isSet bool
}

func (v NullableDiscoveryProviderDto) Get() *DiscoveryProviderDto {
	return v.value
}

func (v *NullableDiscoveryProviderDto) Set(val *DiscoveryProviderDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoveryProviderDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoveryProviderDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoveryProviderDto(val *DiscoveryProviderDto) *NullableDiscoveryProviderDto {
	return &NullableDiscoveryProviderDto{value: val, isSet: true}
}

func (v NullableDiscoveryProviderDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoveryProviderDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


