/*
Discovery Provider API

REST API for implementations of custom Discovery Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discovery

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GenericSecretContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenericSecretContent{}

// GenericSecretContent Secret representing generic content represented as string
type GenericSecretContent struct {
	// Secret type
	Type SecretType `json:"type"`
	// Generic secret content represented as string. In case secret content is binary data, it should be encoded as BASE64 string.
	Content string `json:"content"`
}

type _GenericSecretContent GenericSecretContent

// NewGenericSecretContent instantiates a new GenericSecretContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericSecretContent(type_ SecretType, content string) *GenericSecretContent {
	this := GenericSecretContent{}
	this.Type = type_
	this.Content = content
	return &this
}

// NewGenericSecretContentWithDefaults instantiates a new GenericSecretContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericSecretContentWithDefaults() *GenericSecretContent {
	this := GenericSecretContent{}
	return &this
}

// GetType returns the Type field value
func (o *GenericSecretContent) GetType() SecretType {
	if o == nil {
		var ret SecretType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GenericSecretContent) GetTypeOk() (*SecretType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GenericSecretContent) SetType(v SecretType) {
	o.Type = v
}

// GetContent returns the Content field value
func (o *GenericSecretContent) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *GenericSecretContent) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *GenericSecretContent) SetContent(v string) {
	o.Content = v
}

func (o GenericSecretContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenericSecretContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *GenericSecretContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenericSecretContent := _GenericSecretContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenericSecretContent)

	if err != nil {
		return err
	}

	*o = GenericSecretContent(varGenericSecretContent)

	return err
}

type NullableGenericSecretContent struct {
	value *GenericSecretContent
	isSet bool
}

func (v NullableGenericSecretContent) Get() *GenericSecretContent {
	return v.value
}

func (v *NullableGenericSecretContent) Set(val *GenericSecretContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericSecretContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericSecretContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericSecretContent(val *GenericSecretContent) *NullableGenericSecretContent {
	return &NullableGenericSecretContent{value: val, isSet: true}
}

func (v NullableGenericSecretContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericSecretContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


