/*
Discovery Provider API

REST API for implementations of custom Discovery Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discovery

import (
	"encoding/json"
	"fmt"
)

// DiscoveryStatus the model 'DiscoveryStatus'
type DiscoveryStatus string

// List of DiscoveryStatus
const (
	DISCOVERYSTATUS_IN_PROGRESS DiscoveryStatus = "inProgress"
	DISCOVERYSTATUS_PROCESSING DiscoveryStatus = "processing"
	DISCOVERYSTATUS_FAILED DiscoveryStatus = "failed"
	DISCOVERYSTATUS_COMPLETED DiscoveryStatus = "completed"
	DISCOVERYSTATUS_WARNING DiscoveryStatus = "warning"
)

// All allowed values of DiscoveryStatus enum
var AllowedDiscoveryStatusEnumValues = []DiscoveryStatus{
	"inProgress",
	"processing",
	"failed",
	"completed",
	"warning",
}

func (v *DiscoveryStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiscoveryStatus(value)
	for _, existing := range AllowedDiscoveryStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiscoveryStatus", value)
}

// NewDiscoveryStatusFromValue returns a pointer to a valid DiscoveryStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiscoveryStatusFromValue(v string) (*DiscoveryStatus, error) {
	ev := DiscoveryStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiscoveryStatus: valid values are %v", v, AllowedDiscoveryStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiscoveryStatus) IsValid() bool {
	for _, existing := range AllowedDiscoveryStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DiscoveryStatus value
func (v DiscoveryStatus) Ptr() *DiscoveryStatus {
	return &v
}

type NullableDiscoveryStatus struct {
	value *DiscoveryStatus
	isSet bool
}

func (v NullableDiscoveryStatus) Get() *DiscoveryStatus {
	return v.value
}

func (v *NullableDiscoveryStatus) Set(val *DiscoveryStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoveryStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoveryStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoveryStatus(val *DiscoveryStatus) *NullableDiscoveryStatus {
	return &NullableDiscoveryStatus{value: val, isSet: true}
}

func (v NullableDiscoveryStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoveryStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

