/*
Discovery Provider API

REST API for implementations of custom Discovery Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discovery

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupAttributeV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupAttributeV3{}

// GroupAttributeV3 Group attribute and its content represents dynamic list of additional attributes retrieved by callback. Its content can not be edited and is not send in requests to store.
type GroupAttributeV3 struct {
	// Version of the Attribute
	SchemaVersion AttributeVersion `json:"schemaVersion"`
	// UUID of the Attribute for unique identification
	Uuid string `json:"uuid"`
	// Name of the Attribute that is used for identification
	Name string `json:"name"`
	// Optional description of the Attribute, should contain helper text on what is expected
	Description *string `json:"description,omitempty"`
	// List of all different types of attributes
	Content []BaseAttributeDto `json:"content,omitempty"`
	Version *int32 `json:"version,omitempty"`
	// Type of the Attribute
	Type AttributeType `json:"type"`
	// Optional definition of callback for getting the content of the Attribute based on the action
	AttributeCallback *AttributeCallback `json:"attributeCallback,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupAttributeV3 GroupAttributeV3

// NewGroupAttributeV3 instantiates a new GroupAttributeV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupAttributeV3(schemaVersion AttributeVersion, uuid string, name string, type_ AttributeType) *GroupAttributeV3 {
	this := GroupAttributeV3{}
	this.SchemaVersion = schemaVersion
	this.Uuid = uuid
	this.Name = name
	this.Type = type_
	return &this
}

// NewGroupAttributeV3WithDefaults instantiates a new GroupAttributeV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupAttributeV3WithDefaults() *GroupAttributeV3 {
	this := GroupAttributeV3{}
	return &this
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *GroupAttributeV3) GetSchemaVersion() AttributeVersion {
	if o == nil {
		var ret AttributeVersion
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetSchemaVersionOk() (*AttributeVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *GroupAttributeV3) SetSchemaVersion(v AttributeVersion) {
	o.SchemaVersion = v
}

// GetUuid returns the Uuid field value
func (o *GroupAttributeV3) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *GroupAttributeV3) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *GroupAttributeV3) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupAttributeV3) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GroupAttributeV3) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GroupAttributeV3) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GroupAttributeV3) SetDescription(v string) {
	o.Description = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *GroupAttributeV3) GetContent() []BaseAttributeDto {
	if o == nil || IsNil(o.Content) {
		var ret []BaseAttributeDto
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetContentOk() ([]BaseAttributeDto, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *GroupAttributeV3) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []BaseAttributeDto and assigns it to the Content field.
func (o *GroupAttributeV3) SetContent(v []BaseAttributeDto) {
	o.Content = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GroupAttributeV3) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GroupAttributeV3) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *GroupAttributeV3) SetVersion(v int32) {
	o.Version = &v
}

// GetType returns the Type field value
func (o *GroupAttributeV3) GetType() AttributeType {
	if o == nil {
		var ret AttributeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetTypeOk() (*AttributeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GroupAttributeV3) SetType(v AttributeType) {
	o.Type = v
}

// GetAttributeCallback returns the AttributeCallback field value if set, zero value otherwise.
func (o *GroupAttributeV3) GetAttributeCallback() AttributeCallback {
	if o == nil || IsNil(o.AttributeCallback) {
		var ret AttributeCallback
		return ret
	}
	return *o.AttributeCallback
}

// GetAttributeCallbackOk returns a tuple with the AttributeCallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupAttributeV3) GetAttributeCallbackOk() (*AttributeCallback, bool) {
	if o == nil || IsNil(o.AttributeCallback) {
		return nil, false
	}
	return o.AttributeCallback, true
}

// HasAttributeCallback returns a boolean if a field has been set.
func (o *GroupAttributeV3) HasAttributeCallback() bool {
	if o != nil && !IsNil(o.AttributeCallback) {
		return true
	}

	return false
}

// SetAttributeCallback gets a reference to the given AttributeCallback and assigns it to the AttributeCallback field.
func (o *GroupAttributeV3) SetAttributeCallback(v AttributeCallback) {
	o.AttributeCallback = &v
}

func (o GroupAttributeV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupAttributeV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemaVersion"] = o.SchemaVersion
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.AttributeCallback) {
		toSerialize["attributeCallback"] = o.AttributeCallback
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupAttributeV3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schemaVersion",
		"uuid",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupAttributeV3 := _GroupAttributeV3{}

	err = json.Unmarshal(data, &varGroupAttributeV3)

	if err != nil {
		return err
	}

	*o = GroupAttributeV3(varGroupAttributeV3)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schemaVersion")
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "content")
		delete(additionalProperties, "version")
		delete(additionalProperties, "type")
		delete(additionalProperties, "attributeCallback")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupAttributeV3 struct {
	value *GroupAttributeV3
	isSet bool
}

func (v NullableGroupAttributeV3) Get() *GroupAttributeV3 {
	return v.value
}

func (v *NullableGroupAttributeV3) Set(val *GroupAttributeV3) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupAttributeV3) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupAttributeV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupAttributeV3(val *GroupAttributeV3) *NullableGroupAttributeV3 {
	return &NullableGroupAttributeV3{value: val, isSet: true}
}

func (v NullableGroupAttributeV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupAttributeV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


