/*
Entity Provider API

REST API for implementations of custom Entity Provider

API version: 2.18.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// FieldMappingFieldsInner - struct for FieldMappingFieldsInner
type FieldMappingFieldsInner struct {
	ExtensionMappedField *ExtensionMappedField
	RdnMappedField *RdnMappedField
	SanMappedField *SanMappedField
}

// ExtensionMappedFieldAsFieldMappingFieldsInner is a convenience function that returns ExtensionMappedField wrapped in FieldMappingFieldsInner
func ExtensionMappedFieldAsFieldMappingFieldsInner(v *ExtensionMappedField) FieldMappingFieldsInner {
	return FieldMappingFieldsInner{
		ExtensionMappedField: v,
	}
}

// RdnMappedFieldAsFieldMappingFieldsInner is a convenience function that returns RdnMappedField wrapped in FieldMappingFieldsInner
func RdnMappedFieldAsFieldMappingFieldsInner(v *RdnMappedField) FieldMappingFieldsInner {
	return FieldMappingFieldsInner{
		RdnMappedField: v,
	}
}

// SanMappedFieldAsFieldMappingFieldsInner is a convenience function that returns SanMappedField wrapped in FieldMappingFieldsInner
func SanMappedFieldAsFieldMappingFieldsInner(v *SanMappedField) FieldMappingFieldsInner {
	return FieldMappingFieldsInner{
		SanMappedField: v,
	}
}


// UnmarshalJSON decodes FieldMappingFieldsInner by switching on the JSON "fieldType" field.
// Patched by tools/fixoneof — the generator's match-counting decoder
// fails on this oneOf because multiple variants share the same Go struct
// shape and pass strict decode simultaneously.
func (dst *FieldMappingFieldsInner) UnmarshalJSON(data []byte) error {
	var probe struct {
		Disc string `json:"fieldType"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("FieldMappingFieldsInner: probe fieldType: %w", err)
	}
	disc := probe.Disc
	dst.ExtensionMappedField = nil
	dst.RdnMappedField = nil
	dst.SanMappedField = nil
	switch disc {
	case "extension":
		var v ExtensionMappedField
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("FieldMappingFieldsInner: decode ExtensionMappedField: %w", err)
		}
		dst.ExtensionMappedField = &v
		return nil
	case "rdn":
		var v RdnMappedField
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("FieldMappingFieldsInner: decode RdnMappedField: %w", err)
		}
		dst.RdnMappedField = &v
		return nil
	case "san":
		var v SanMappedField
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("FieldMappingFieldsInner: decode SanMappedField: %w", err)
		}
		dst.SanMappedField = &v
		return nil
	default:
		return fmt.Errorf("FieldMappingFieldsInner: unknown fieldType %q", disc)
	}
}


// Marshal data from the first non-nil pointers in the struct to JSON
func (src FieldMappingFieldsInner) MarshalJSON() ([]byte, error) {
	if src.ExtensionMappedField != nil {
		return json.Marshal(&src.ExtensionMappedField)
	}

	if src.RdnMappedField != nil {
		return json.Marshal(&src.RdnMappedField)
	}

	if src.SanMappedField != nil {
		return json.Marshal(&src.SanMappedField)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FieldMappingFieldsInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ExtensionMappedField != nil {
		return obj.ExtensionMappedField
	}

	if obj.RdnMappedField != nil {
		return obj.RdnMappedField
	}

	if obj.SanMappedField != nil {
		return obj.SanMappedField
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj FieldMappingFieldsInner) GetActualInstanceValue() (interface{}) {
	if obj.ExtensionMappedField != nil {
		return *obj.ExtensionMappedField
	}

	if obj.RdnMappedField != nil {
		return *obj.RdnMappedField
	}

	if obj.SanMappedField != nil {
		return *obj.SanMappedField
	}

	// all schemas are nil
	return nil
}

type NullableFieldMappingFieldsInner struct {
	value *FieldMappingFieldsInner
	isSet bool
}

func (v NullableFieldMappingFieldsInner) Get() *FieldMappingFieldsInner {
	return v.value
}

func (v *NullableFieldMappingFieldsInner) Set(val *FieldMappingFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldMappingFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldMappingFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldMappingFieldsInner(val *FieldMappingFieldsInner) *NullableFieldMappingFieldsInner {
	return &NullableFieldMappingFieldsInner{value: val, isSet: true}
}

func (v NullableFieldMappingFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldMappingFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


