/*
Entity Provider API

REST API for implementations of custom Entity Provider

API version: 2.18.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// ValueSourceType the model 'ValueSourceType'
type ValueSourceType string

// List of ValueSourceType
const (
	VALUESOURCETYPE_NONE ValueSourceType = "none"
	VALUESOURCETYPE_CONNECTOR_CALLBACK ValueSourceType = "connectorCallback"
	VALUESOURCETYPE_STATIC_LIST ValueSourceType = "staticList"
)

// All allowed values of ValueSourceType enum
var AllowedValueSourceTypeEnumValues = []ValueSourceType{
	"none",
	"connectorCallback",
	"staticList",
}

func (v *ValueSourceType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ValueSourceType(value)
	for _, existing := range AllowedValueSourceTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ValueSourceType", value)
}

// NewValueSourceTypeFromValue returns a pointer to a valid ValueSourceType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewValueSourceTypeFromValue(v string) (*ValueSourceType, error) {
	ev := ValueSourceType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ValueSourceType: valid values are %v", v, AllowedValueSourceTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ValueSourceType) IsValid() bool {
	for _, existing := range AllowedValueSourceTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ValueSourceType value
func (v ValueSourceType) Ptr() *ValueSourceType {
	return &v
}

type NullableValueSourceType struct {
	value *ValueSourceType
	isSet bool
}

func (v NullableValueSourceType) Get() *ValueSourceType {
	return v.value
}

func (v *NullableValueSourceType) Set(val *ValueSourceType) {
	v.value = val
	v.isSet = true
}

func (v NullableValueSourceType) IsSet() bool {
	return v.isSet
}

func (v *NullableValueSourceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueSourceType(val *ValueSourceType) *NullableValueSourceType {
	return &NullableValueSourceType{value: val, isSet: true}
}

func (v NullableValueSourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueSourceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

