/*
Compliance Provider v2 API

REST API for implementations of custom v2 Compliance Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FloatAttributeContentV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FloatAttributeContentV2{}

// FloatAttributeContentV2 Float attribute content for decimal numbers
type FloatAttributeContentV2 struct {
	// ContentV2 Reference
	Reference *string `json:"reference,omitempty"`
	// Float attribute value
	Data float32 `json:"data"`
}

type _FloatAttributeContentV2 FloatAttributeContentV2

// NewFloatAttributeContentV2 instantiates a new FloatAttributeContentV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFloatAttributeContentV2(data float32) *FloatAttributeContentV2 {
	this := FloatAttributeContentV2{}
	this.Data = data
	return &this
}

// NewFloatAttributeContentV2WithDefaults instantiates a new FloatAttributeContentV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFloatAttributeContentV2WithDefaults() *FloatAttributeContentV2 {
	this := FloatAttributeContentV2{}
	return &this
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *FloatAttributeContentV2) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloatAttributeContentV2) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *FloatAttributeContentV2) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *FloatAttributeContentV2) SetReference(v string) {
	o.Reference = &v
}

// GetData returns the Data field value
func (o *FloatAttributeContentV2) GetData() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *FloatAttributeContentV2) GetDataOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *FloatAttributeContentV2) SetData(v float32) {
	o.Data = v
}

func (o FloatAttributeContentV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FloatAttributeContentV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *FloatAttributeContentV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFloatAttributeContentV2 := _FloatAttributeContentV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFloatAttributeContentV2)

	if err != nil {
		return err
	}

	*o = FloatAttributeContentV2(varFloatAttributeContentV2)

	return err
}

type NullableFloatAttributeContentV2 struct {
	value *FloatAttributeContentV2
	isSet bool
}

func (v NullableFloatAttributeContentV2) Get() *FloatAttributeContentV2 {
	return v.value
}

func (v *NullableFloatAttributeContentV2) Set(val *FloatAttributeContentV2) {
	v.value = val
	v.isSet = true
}

func (v NullableFloatAttributeContentV2) IsSet() bool {
	return v.isSet
}

func (v *NullableFloatAttributeContentV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFloatAttributeContentV2(val *FloatAttributeContentV2) *NullableFloatAttributeContentV2 {
	return &NullableFloatAttributeContentV2{value: val, isSet: true}
}

func (v NullableFloatAttributeContentV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFloatAttributeContentV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


