/*
Compliance Provider v2 API

REST API for implementations of custom v2 Compliance Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecretKeySecretContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretKeySecretContent{}

// SecretKeySecretContent Secret representing secret key
type SecretKeySecretContent struct {
	// Secret type
	Type SecretType `json:"type"`
	// BASE64 encoded binary (raw) content of key
	Content string `json:"content"`
}

type _SecretKeySecretContent SecretKeySecretContent

// NewSecretKeySecretContent instantiates a new SecretKeySecretContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretKeySecretContent(type_ SecretType, content string) *SecretKeySecretContent {
	this := SecretKeySecretContent{}
	this.Type = type_
	this.Content = content
	return &this
}

// NewSecretKeySecretContentWithDefaults instantiates a new SecretKeySecretContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretKeySecretContentWithDefaults() *SecretKeySecretContent {
	this := SecretKeySecretContent{}
	return &this
}

// GetType returns the Type field value
func (o *SecretKeySecretContent) GetType() SecretType {
	if o == nil {
		var ret SecretType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SecretKeySecretContent) GetTypeOk() (*SecretType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SecretKeySecretContent) SetType(v SecretType) {
	o.Type = v
}

// GetContent returns the Content field value
func (o *SecretKeySecretContent) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *SecretKeySecretContent) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *SecretKeySecretContent) SetContent(v string) {
	o.Content = v
}

func (o SecretKeySecretContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretKeySecretContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *SecretKeySecretContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretKeySecretContent := _SecretKeySecretContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretKeySecretContent)

	if err != nil {
		return err
	}

	*o = SecretKeySecretContent(varSecretKeySecretContent)

	return err
}

type NullableSecretKeySecretContent struct {
	value *SecretKeySecretContent
	isSet bool
}

func (v NullableSecretKeySecretContent) Get() *SecretKeySecretContent {
	return v.value
}

func (v *NullableSecretKeySecretContent) Set(val *SecretKeySecretContent) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretKeySecretContent) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretKeySecretContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretKeySecretContent(val *SecretKeySecretContent) *NullableSecretKeySecretContent {
	return &NullableSecretKeySecretContent{value: val, isSet: true}
}

func (v NullableSecretKeySecretContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretKeySecretContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


