/*
Notification Provider API

REST API for implementations of custom Notification Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notification

import (
	"encoding/json"
	"fmt"
)

// ResourceEvent the model 'ResourceEvent'
type ResourceEvent string

// List of ResourceEvent
const (
	RESOURCEEVENT_CERTIFICATE_STATUS_CHANGED ResourceEvent = "certificate_status_changed"
	RESOURCEEVENT_CERTIFICATE_ACTION_PERFORMED ResourceEvent = "certificate_action_performed"
	RESOURCEEVENT_CERTIFICATE_DISCOVERED ResourceEvent = "certificate_discovered"
	RESOURCEEVENT_CERTIFICATE_EXPIRING ResourceEvent = "certificate_expiring"
	RESOURCEEVENT_CERTIFICATE_NOT_COMPLIANT ResourceEvent = "certificate_not_compliant"
	RESOURCEEVENT_DISCOVERY_FINISHED ResourceEvent = "discovery_finished"
	RESOURCEEVENT_APPROVAL_REQUESTED ResourceEvent = "approval_requested"
	RESOURCEEVENT_APPROVAL_CLOSED ResourceEvent = "approval_closed"
	RESOURCEEVENT_SCHEDULED_JOB_FINISHED ResourceEvent = "scheduled_job_finished"
)

// All allowed values of ResourceEvent enum
var AllowedResourceEventEnumValues = []ResourceEvent{
	"certificate_status_changed",
	"certificate_action_performed",
	"certificate_discovered",
	"certificate_expiring",
	"certificate_not_compliant",
	"discovery_finished",
	"approval_requested",
	"approval_closed",
	"scheduled_job_finished",
}

func (v *ResourceEvent) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceEvent(value)
	for _, existing := range AllowedResourceEventEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ResourceEvent", value)
}

// NewResourceEventFromValue returns a pointer to a valid ResourceEvent
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceEventFromValue(v string) (*ResourceEvent, error) {
	ev := ResourceEvent(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResourceEvent: valid values are %v", v, AllowedResourceEventEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResourceEvent) IsValid() bool {
	for _, existing := range AllowedResourceEventEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResourceEvent value
func (v ResourceEvent) Ptr() *ResourceEvent {
	return &v
}

type NullableResourceEvent struct {
	value *ResourceEvent
	isSet bool
}

func (v NullableResourceEvent) Get() *ResourceEvent {
	return v.value
}

func (v *NullableResourceEvent) Set(val *ResourceEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceEvent(val *ResourceEvent) *NullableResourceEvent {
	return &NullableResourceEvent{value: val, isSet: true}
}

func (v NullableResourceEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

