/*
Notification Provider API

REST API for implementations of custom Notification Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notification

import (
	"encoding/json"
	"fmt"
)

// checks if the NotificationProviderInstanceDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationProviderInstanceDto{}

// NotificationProviderInstanceDto struct for NotificationProviderInstanceDto
type NotificationProviderInstanceDto struct {
	// Object identifier
	Uuid string `json:"uuid"`
	// Object Name
	Name string `json:"name"`
	// List of Notification instance Attributes
	Attributes []BaseAttributeDto `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _NotificationProviderInstanceDto NotificationProviderInstanceDto

// NewNotificationProviderInstanceDto instantiates a new NotificationProviderInstanceDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationProviderInstanceDto(uuid string, name string, attributes []BaseAttributeDto) *NotificationProviderInstanceDto {
	this := NotificationProviderInstanceDto{}
	this.Uuid = uuid
	this.Name = name
	this.Attributes = attributes
	return &this
}

// NewNotificationProviderInstanceDtoWithDefaults instantiates a new NotificationProviderInstanceDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationProviderInstanceDtoWithDefaults() *NotificationProviderInstanceDto {
	this := NotificationProviderInstanceDto{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *NotificationProviderInstanceDto) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *NotificationProviderInstanceDto) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *NotificationProviderInstanceDto) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *NotificationProviderInstanceDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NotificationProviderInstanceDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NotificationProviderInstanceDto) SetName(v string) {
	o.Name = v
}

// GetAttributes returns the Attributes field value
func (o *NotificationProviderInstanceDto) GetAttributes() []BaseAttributeDto {
	if o == nil {
		var ret []BaseAttributeDto
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *NotificationProviderInstanceDto) GetAttributesOk() ([]BaseAttributeDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attributes, true
}

// SetAttributes sets field value
func (o *NotificationProviderInstanceDto) SetAttributes(v []BaseAttributeDto) {
	o.Attributes = v
}

func (o NotificationProviderInstanceDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationProviderInstanceDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotificationProviderInstanceDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationProviderInstanceDto := _NotificationProviderInstanceDto{}

	err = json.Unmarshal(data, &varNotificationProviderInstanceDto)

	if err != nil {
		return err
	}

	*o = NotificationProviderInstanceDto(varNotificationProviderInstanceDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotificationProviderInstanceDto struct {
	value *NotificationProviderInstanceDto
	isSet bool
}

func (v NullableNotificationProviderInstanceDto) Get() *NotificationProviderInstanceDto {
	return v.value
}

func (v *NullableNotificationProviderInstanceDto) Set(val *NotificationProviderInstanceDto) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationProviderInstanceDto) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationProviderInstanceDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationProviderInstanceDto(val *NotificationProviderInstanceDto) *NullableNotificationProviderInstanceDto {
	return &NullableNotificationProviderInstanceDto{value: val, isSet: true}
}

func (v NullableNotificationProviderInstanceDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationProviderInstanceDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


