/*
Notification Provider API

REST API for implementations of custom Notification Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notification

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotificationProviderInstanceRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationProviderInstanceRequestDto{}

// NotificationProviderInstanceRequestDto struct for NotificationProviderInstanceRequestDto
type NotificationProviderInstanceRequestDto struct {
	// Notification instance name
	Name string `json:"name"`
	// Kind of Notification instance
	Kind string `json:"kind"`
	// List of Notification instance Attributes
	Attributes []RequestAttribute `json:"attributes"`
}

type _NotificationProviderInstanceRequestDto NotificationProviderInstanceRequestDto

// NewNotificationProviderInstanceRequestDto instantiates a new NotificationProviderInstanceRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationProviderInstanceRequestDto(name string, kind string, attributes []RequestAttribute) *NotificationProviderInstanceRequestDto {
	this := NotificationProviderInstanceRequestDto{}
	this.Name = name
	this.Kind = kind
	this.Attributes = attributes
	return &this
}

// NewNotificationProviderInstanceRequestDtoWithDefaults instantiates a new NotificationProviderInstanceRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationProviderInstanceRequestDtoWithDefaults() *NotificationProviderInstanceRequestDto {
	this := NotificationProviderInstanceRequestDto{}
	return &this
}

// GetName returns the Name field value
func (o *NotificationProviderInstanceRequestDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NotificationProviderInstanceRequestDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NotificationProviderInstanceRequestDto) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *NotificationProviderInstanceRequestDto) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *NotificationProviderInstanceRequestDto) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *NotificationProviderInstanceRequestDto) SetKind(v string) {
	o.Kind = v
}

// GetAttributes returns the Attributes field value
func (o *NotificationProviderInstanceRequestDto) GetAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *NotificationProviderInstanceRequestDto) GetAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attributes, true
}

// SetAttributes sets field value
func (o *NotificationProviderInstanceRequestDto) SetAttributes(v []RequestAttribute) {
	o.Attributes = v
}

func (o NotificationProviderInstanceRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationProviderInstanceRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *NotificationProviderInstanceRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"kind",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationProviderInstanceRequestDto := _NotificationProviderInstanceRequestDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotificationProviderInstanceRequestDto)

	if err != nil {
		return err
	}

	*o = NotificationProviderInstanceRequestDto(varNotificationProviderInstanceRequestDto)

	return err
}

type NullableNotificationProviderInstanceRequestDto struct {
	value *NotificationProviderInstanceRequestDto
	isSet bool
}

func (v NullableNotificationProviderInstanceRequestDto) Get() *NotificationProviderInstanceRequestDto {
	return v.value
}

func (v *NullableNotificationProviderInstanceRequestDto) Set(val *NotificationProviderInstanceRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationProviderInstanceRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationProviderInstanceRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationProviderInstanceRequestDto(val *NotificationProviderInstanceRequestDto) *NullableNotificationProviderInstanceRequestDto {
	return &NullableNotificationProviderInstanceRequestDto{value: val, isSet: true}
}

func (v NullableNotificationProviderInstanceRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationProviderInstanceRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


