/*
Cryptography Provider v2 API

REST API for implementations of custom v2 Cryptography Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecretKeyOperationStatusResponseV2Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretKeyOperationStatusResponseV2Dto{}

// SecretKeyOperationStatusResponseV2Dto struct for SecretKeyOperationStatusResponseV2Dto
type SecretKeyOperationStatusResponseV2Dto struct {
	// Operation status as known to the connector
	Status OperationStatus `json:"status"`
	// Failure or cancellation detail when status is `failed` or `cancelled`
	Reason *string `json:"reason,omitempty"`
	// Created secret-key result. Present only when status is `completed`.
	Result *SecretKeyDataResponseV2Dto `json:"result,omitempty"`
	// Type of key requested
	KeyRequestType KeyRequestType `json:"keyRequestType"`
}

type _SecretKeyOperationStatusResponseV2Dto SecretKeyOperationStatusResponseV2Dto

// NewSecretKeyOperationStatusResponseV2Dto instantiates a new SecretKeyOperationStatusResponseV2Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretKeyOperationStatusResponseV2Dto(status OperationStatus) *SecretKeyOperationStatusResponseV2Dto {
	this := SecretKeyOperationStatusResponseV2Dto{}
	this.Status = status
	this.KeyRequestType = KEYREQUESTTYPE_SECRET
	return &this
}

// NewSecretKeyOperationStatusResponseV2DtoWithDefaults instantiates a new SecretKeyOperationStatusResponseV2Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretKeyOperationStatusResponseV2DtoWithDefaults() *SecretKeyOperationStatusResponseV2Dto {
	this := SecretKeyOperationStatusResponseV2Dto{}
	this.KeyRequestType = KEYREQUESTTYPE_SECRET
	return &this
}

// GetStatus returns the Status field value
func (o *SecretKeyOperationStatusResponseV2Dto) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SecretKeyOperationStatusResponseV2Dto) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SecretKeyOperationStatusResponseV2Dto) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *SecretKeyOperationStatusResponseV2Dto) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretKeyOperationStatusResponseV2Dto) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *SecretKeyOperationStatusResponseV2Dto) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *SecretKeyOperationStatusResponseV2Dto) SetReason(v string) {
	o.Reason = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *SecretKeyOperationStatusResponseV2Dto) GetResult() SecretKeyDataResponseV2Dto {
	if o == nil || IsNil(o.Result) {
		var ret SecretKeyDataResponseV2Dto
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretKeyOperationStatusResponseV2Dto) GetResultOk() (*SecretKeyDataResponseV2Dto, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *SecretKeyOperationStatusResponseV2Dto) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given SecretKeyDataResponseV2Dto and assigns it to the Result field.
func (o *SecretKeyOperationStatusResponseV2Dto) SetResult(v SecretKeyDataResponseV2Dto) {
	o.Result = &v
}

// GetKeyRequestType returns the KeyRequestType field value
func (o *SecretKeyOperationStatusResponseV2Dto) GetKeyRequestType() KeyRequestType {
	if o == nil {
		var ret KeyRequestType
		return ret
	}

	return o.KeyRequestType
}

// GetKeyRequestTypeOk returns a tuple with the KeyRequestType field value
// and a boolean to check if the value has been set.
func (o *SecretKeyOperationStatusResponseV2Dto) GetKeyRequestTypeOk() (*KeyRequestType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyRequestType, true
}

// SetKeyRequestType sets field value
func (o *SecretKeyOperationStatusResponseV2Dto) SetKeyRequestType(v KeyRequestType) {
	o.KeyRequestType = v
}

func (o SecretKeyOperationStatusResponseV2Dto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretKeyOperationStatusResponseV2Dto) ToMap() (map[string]interface{}, error) {
	// fixoneof: pinned by the spec to "secret": any other value would not round-trip.
	if o.KeyRequestType != KEYREQUESTTYPE_SECRET {
		return nil, fmt.Errorf("keyRequestType must be %q for SecretKeyOperationStatusResponseV2Dto, got %q", KEYREQUESTTYPE_SECRET, o.KeyRequestType)
	}
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	toSerialize["keyRequestType"] = o.KeyRequestType
	return toSerialize, nil
}

func (o *SecretKeyOperationStatusResponseV2Dto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"keyRequestType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretKeyOperationStatusResponseV2Dto := _SecretKeyOperationStatusResponseV2Dto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretKeyOperationStatusResponseV2Dto)

	if err != nil {
		return err
	}

	*o = SecretKeyOperationStatusResponseV2Dto(varSecretKeyOperationStatusResponseV2Dto)
	// fixoneof: pinned by the spec to "secret": any other value would not round-trip.
	if o.KeyRequestType != KEYREQUESTTYPE_SECRET {
		return fmt.Errorf("keyRequestType must be %q for SecretKeyOperationStatusResponseV2Dto, got %q", KEYREQUESTTYPE_SECRET, o.KeyRequestType)
	}

	return err
}

type NullableSecretKeyOperationStatusResponseV2Dto struct {
	value *SecretKeyOperationStatusResponseV2Dto
	isSet bool
}

func (v NullableSecretKeyOperationStatusResponseV2Dto) Get() *SecretKeyOperationStatusResponseV2Dto {
	return v.value
}

func (v *NullableSecretKeyOperationStatusResponseV2Dto) Set(val *SecretKeyOperationStatusResponseV2Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretKeyOperationStatusResponseV2Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretKeyOperationStatusResponseV2Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretKeyOperationStatusResponseV2Dto(val *SecretKeyOperationStatusResponseV2Dto) *NullableSecretKeyOperationStatusResponseV2Dto {
	return &NullableSecretKeyOperationStatusResponseV2Dto{value: val, isSet: true}
}

func (v NullableSecretKeyOperationStatusResponseV2Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretKeyOperationStatusResponseV2Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


