/*
Cryptography Provider v2 API

REST API for implementations of custom v2 Cryptography Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CipherDataRequestV2Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CipherDataRequestV2Dto{}

// CipherDataRequestV2Dto struct for CipherDataRequestV2Dto
type CipherDataRequestV2Dto struct {
	// Token attributes
	TokenAttributes []RequestAttribute `json:"tokenAttributes"`
	// Token profile attributes
	TokenProfileAttributes []RequestAttribute `json:"tokenProfileAttributes"`
	// Key usages selected on the token profile
	KeyUsages []KeyUsage `json:"keyUsages"`
	// Connector-defined metadata identifying the key, as returned when the key was created, listed or identified. Supply the metadata unchanged in subsequent requests for the key. Metadata must identify the key durably—it must remain valid across connector restarts and sessions; ephemeral handles must not be used.
	KeyMeta []MetadataAttribute `json:"keyMeta"`
	// Batch-wide cipher settings.
	CipherAttributes []RequestAttribute `json:"cipherAttributes"`
	// Data to be encrypted or decrypted
	CipherData []CipherDataV2Dto `json:"cipherData"`
}

type _CipherDataRequestV2Dto CipherDataRequestV2Dto

// NewCipherDataRequestV2Dto instantiates a new CipherDataRequestV2Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCipherDataRequestV2Dto(tokenAttributes []RequestAttribute, tokenProfileAttributes []RequestAttribute, keyUsages []KeyUsage, keyMeta []MetadataAttribute, cipherAttributes []RequestAttribute, cipherData []CipherDataV2Dto) *CipherDataRequestV2Dto {
	this := CipherDataRequestV2Dto{}
	this.TokenAttributes = tokenAttributes
	this.TokenProfileAttributes = tokenProfileAttributes
	this.KeyUsages = keyUsages
	this.KeyMeta = keyMeta
	this.CipherAttributes = cipherAttributes
	this.CipherData = cipherData
	return &this
}

// NewCipherDataRequestV2DtoWithDefaults instantiates a new CipherDataRequestV2Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCipherDataRequestV2DtoWithDefaults() *CipherDataRequestV2Dto {
	this := CipherDataRequestV2Dto{}
	return &this
}

// GetTokenAttributes returns the TokenAttributes field value
func (o *CipherDataRequestV2Dto) GetTokenAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.TokenAttributes
}

// GetTokenAttributesOk returns a tuple with the TokenAttributes field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestV2Dto) GetTokenAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenAttributes, true
}

// SetTokenAttributes sets field value
func (o *CipherDataRequestV2Dto) SetTokenAttributes(v []RequestAttribute) {
	o.TokenAttributes = v
}

// GetTokenProfileAttributes returns the TokenProfileAttributes field value
func (o *CipherDataRequestV2Dto) GetTokenProfileAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.TokenProfileAttributes
}

// GetTokenProfileAttributesOk returns a tuple with the TokenProfileAttributes field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestV2Dto) GetTokenProfileAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenProfileAttributes, true
}

// SetTokenProfileAttributes sets field value
func (o *CipherDataRequestV2Dto) SetTokenProfileAttributes(v []RequestAttribute) {
	o.TokenProfileAttributes = v
}

// GetKeyUsages returns the KeyUsages field value
func (o *CipherDataRequestV2Dto) GetKeyUsages() []KeyUsage {
	if o == nil {
		var ret []KeyUsage
		return ret
	}

	return o.KeyUsages
}

// GetKeyUsagesOk returns a tuple with the KeyUsages field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestV2Dto) GetKeyUsagesOk() ([]KeyUsage, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyUsages, true
}

// SetKeyUsages sets field value
func (o *CipherDataRequestV2Dto) SetKeyUsages(v []KeyUsage) {
	o.KeyUsages = v
}

// GetKeyMeta returns the KeyMeta field value
func (o *CipherDataRequestV2Dto) GetKeyMeta() []MetadataAttribute {
	if o == nil {
		var ret []MetadataAttribute
		return ret
	}

	return o.KeyMeta
}

// GetKeyMetaOk returns a tuple with the KeyMeta field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestV2Dto) GetKeyMetaOk() ([]MetadataAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyMeta, true
}

// SetKeyMeta sets field value
func (o *CipherDataRequestV2Dto) SetKeyMeta(v []MetadataAttribute) {
	o.KeyMeta = v
}

// GetCipherAttributes returns the CipherAttributes field value
func (o *CipherDataRequestV2Dto) GetCipherAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.CipherAttributes
}

// GetCipherAttributesOk returns a tuple with the CipherAttributes field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestV2Dto) GetCipherAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.CipherAttributes, true
}

// SetCipherAttributes sets field value
func (o *CipherDataRequestV2Dto) SetCipherAttributes(v []RequestAttribute) {
	o.CipherAttributes = v
}

// GetCipherData returns the CipherData field value
func (o *CipherDataRequestV2Dto) GetCipherData() []CipherDataV2Dto {
	if o == nil {
		var ret []CipherDataV2Dto
		return ret
	}

	return o.CipherData
}

// GetCipherDataOk returns a tuple with the CipherData field value
// and a boolean to check if the value has been set.
func (o *CipherDataRequestV2Dto) GetCipherDataOk() ([]CipherDataV2Dto, bool) {
	if o == nil {
		return nil, false
	}
	return o.CipherData, true
}

// SetCipherData sets field value
func (o *CipherDataRequestV2Dto) SetCipherData(v []CipherDataV2Dto) {
	o.CipherData = v
}

func (o CipherDataRequestV2Dto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CipherDataRequestV2Dto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tokenAttributes"] = o.TokenAttributes
	toSerialize["tokenProfileAttributes"] = o.TokenProfileAttributes
	toSerialize["keyUsages"] = o.KeyUsages
	toSerialize["keyMeta"] = o.KeyMeta
	toSerialize["cipherAttributes"] = o.CipherAttributes
	toSerialize["cipherData"] = o.CipherData
	return toSerialize, nil
}

func (o *CipherDataRequestV2Dto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tokenAttributes",
		"tokenProfileAttributes",
		"keyUsages",
		"keyMeta",
		"cipherAttributes",
		"cipherData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCipherDataRequestV2Dto := _CipherDataRequestV2Dto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCipherDataRequestV2Dto)

	if err != nil {
		return err
	}

	*o = CipherDataRequestV2Dto(varCipherDataRequestV2Dto)

	return err
}

type NullableCipherDataRequestV2Dto struct {
	value *CipherDataRequestV2Dto
	isSet bool
}

func (v NullableCipherDataRequestV2Dto) Get() *CipherDataRequestV2Dto {
	return v.value
}

func (v *NullableCipherDataRequestV2Dto) Set(val *CipherDataRequestV2Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableCipherDataRequestV2Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableCipherDataRequestV2Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCipherDataRequestV2Dto(val *CipherDataRequestV2Dto) *NullableCipherDataRequestV2Dto {
	return &NullableCipherDataRequestV2Dto{value: val, isSet: true}
}

func (v NullableCipherDataRequestV2Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCipherDataRequestV2Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


