/*
Cryptography Provider v2 API

REST API for implementations of custom v2 Cryptography Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// KeyCreationStatusResponse - Status of an asynchronous key-creation operation selected by key request type
type KeyCreationStatusResponse struct {
	KeyPairOperationStatusResponseV2Dto *KeyPairOperationStatusResponseV2Dto
	SecretKeyOperationStatusResponseV2Dto *SecretKeyOperationStatusResponseV2Dto
}

// KeyPairOperationStatusResponseV2DtoAsKeyCreationStatusResponse is a convenience function that returns KeyPairOperationStatusResponseV2Dto wrapped in KeyCreationStatusResponse
func KeyPairOperationStatusResponseV2DtoAsKeyCreationStatusResponse(v *KeyPairOperationStatusResponseV2Dto) KeyCreationStatusResponse {
	return KeyCreationStatusResponse{
		KeyPairOperationStatusResponseV2Dto: v,
	}
}

// SecretKeyOperationStatusResponseV2DtoAsKeyCreationStatusResponse is a convenience function that returns SecretKeyOperationStatusResponseV2Dto wrapped in KeyCreationStatusResponse
func SecretKeyOperationStatusResponseV2DtoAsKeyCreationStatusResponse(v *SecretKeyOperationStatusResponseV2Dto) KeyCreationStatusResponse {
	return KeyCreationStatusResponse{
		SecretKeyOperationStatusResponseV2Dto: v,
	}
}


// UnmarshalJSON decodes KeyCreationStatusResponse by switching on the JSON "keyRequestType" field.
// Patched by tools/fixoneof — the generator's match-counting decoder
// fails on this oneOf because multiple variants share the same Go struct
// shape and pass strict decode simultaneously.
func (dst *KeyCreationStatusResponse) UnmarshalJSON(data []byte) error {
	var probe struct {
		Disc string `json:"keyRequestType"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("KeyCreationStatusResponse: probe keyRequestType: %w", err)
	}
	disc := probe.Disc
	dst.KeyPairOperationStatusResponseV2Dto = nil
	dst.SecretKeyOperationStatusResponseV2Dto = nil
	switch disc {
	case "keyPair":
		var v KeyPairOperationStatusResponseV2Dto
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("KeyCreationStatusResponse: decode KeyPairOperationStatusResponseV2Dto: %w", err)
		}
		dst.KeyPairOperationStatusResponseV2Dto = &v
		return nil
	case "secret":
		var v SecretKeyOperationStatusResponseV2Dto
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("KeyCreationStatusResponse: decode SecretKeyOperationStatusResponseV2Dto: %w", err)
		}
		dst.SecretKeyOperationStatusResponseV2Dto = &v
		return nil
	default:
		return fmt.Errorf("KeyCreationStatusResponse: unknown keyRequestType %q", disc)
	}
}


// Marshal data from the first non-nil pointers in the struct to JSON
func (src KeyCreationStatusResponse) MarshalJSON() ([]byte, error) {
	if src.KeyPairOperationStatusResponseV2Dto != nil {
		return json.Marshal(&src.KeyPairOperationStatusResponseV2Dto)
	}

	if src.SecretKeyOperationStatusResponseV2Dto != nil {
		return json.Marshal(&src.SecretKeyOperationStatusResponseV2Dto)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *KeyCreationStatusResponse) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.KeyPairOperationStatusResponseV2Dto != nil {
		return obj.KeyPairOperationStatusResponseV2Dto
	}

	if obj.SecretKeyOperationStatusResponseV2Dto != nil {
		return obj.SecretKeyOperationStatusResponseV2Dto
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj KeyCreationStatusResponse) GetActualInstanceValue() (interface{}) {
	if obj.KeyPairOperationStatusResponseV2Dto != nil {
		return *obj.KeyPairOperationStatusResponseV2Dto
	}

	if obj.SecretKeyOperationStatusResponseV2Dto != nil {
		return *obj.SecretKeyOperationStatusResponseV2Dto
	}

	// all schemas are nil
	return nil
}

type NullableKeyCreationStatusResponse struct {
	value *KeyCreationStatusResponse
	isSet bool
}

func (v NullableKeyCreationStatusResponse) Get() *KeyCreationStatusResponse {
	return v.value
}

func (v *NullableKeyCreationStatusResponse) Set(val *KeyCreationStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyCreationStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyCreationStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyCreationStatusResponse(val *KeyCreationStatusResponse) *NullableKeyCreationStatusResponse {
	return &NullableKeyCreationStatusResponse{value: val, isSet: true}
}

func (v NullableKeyCreationStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyCreationStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


