/*
Cryptography Provider v2 API

REST API for implementations of custom v2 Cryptography Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// FeatureFlag the model 'FeatureFlag'
type FeatureFlag string

// List of FeatureFlag
const (
	FEATUREFLAG_STATELESS FeatureFlag = "stateless"
	FEATUREFLAG_OPEN_METRICS FeatureFlag = "openMetrics"
	FEATUREFLAG_ASYNCHRONOUS FeatureFlag = "asynchronous"
	FEATUREFLAG_SECRET_VERSIONING FeatureFlag = "secretVersioning"
	FEATUREFLAG_SECRET_ROTATION FeatureFlag = "secretRotation"
	FEATUREFLAG_CONTENT_SIGNING FeatureFlag = "contentSigning"
	FEATUREFLAG_TIMESTAMPING FeatureFlag = "timestamping"
	FEATUREFLAG_CERTIFICATE_REGISTRATION FeatureFlag = "certificateRegistration"
	FEATUREFLAG_CERTIFICATE_STATUS_POLLING FeatureFlag = "certificateStatusPolling"
	FEATUREFLAG_CERTIFICATE_REQUEST_STRUCTURED FeatureFlag = "certificateRequestStructured"
	FEATUREFLAG_CERTIFICATE_IDENTITY_OVERRIDE FeatureFlag = "certificateIdentityOverride"
	FEATUREFLAG_DISCOVERY_STREAMING FeatureFlag = "discoveryStreaming"
	FEATUREFLAG_DISCOVERY_STOP_RESUME FeatureFlag = "discoveryStopResume"
)

// All allowed values of FeatureFlag enum
var AllowedFeatureFlagEnumValues = []FeatureFlag{
	"stateless",
	"openMetrics",
	"asynchronous",
	"secretVersioning",
	"secretRotation",
	"contentSigning",
	"timestamping",
	"certificateRegistration",
	"certificateStatusPolling",
	"certificateRequestStructured",
	"certificateIdentityOverride",
	"discoveryStreaming",
	"discoveryStopResume",
}

func (v *FeatureFlag) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FeatureFlag(value)
	for _, existing := range AllowedFeatureFlagEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FeatureFlag", value)
}

// NewFeatureFlagFromValue returns a pointer to a valid FeatureFlag
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFeatureFlagFromValue(v string) (*FeatureFlag, error) {
	ev := FeatureFlag(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FeatureFlag: valid values are %v", v, AllowedFeatureFlagEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FeatureFlag) IsValid() bool {
	for _, existing := range AllowedFeatureFlagEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FeatureFlag value
func (v FeatureFlag) Ptr() *FeatureFlag {
	return &v
}

type NullableFeatureFlag struct {
	value *FeatureFlag
	isSet bool
}

func (v NullableFeatureFlag) Get() *FeatureFlag {
	return v.value
}

func (v *NullableFeatureFlag) Set(val *FeatureFlag) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureFlag) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureFlag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureFlag(val *FeatureFlag) *NullableFeatureFlag {
	return &NullableFeatureFlag{value: val, isSet: true}
}

func (v NullableFeatureFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureFlag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

