/*
Cryptography Provider v2 API

REST API for implementations of custom v2 Cryptography Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationTrackingRequestV2Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationTrackingRequestV2Dto{}

// OperationTrackingRequestV2Dto Tracking handle for polling or cancelling an asynchronous cryptography operation. The connector must keep the handle valid for the operation's entire tracking lifetime.
type OperationTrackingRequestV2Dto struct {
	// Opaque connector-defined tracking handle returned in the original 202 Accepted response. It is sufficient without token, token-profile, key-usage, or key metadata and must remain valid for the operation's entire tracking lifetime.
	OperationMeta []MetadataAttribute `json:"operationMeta"`
}

type _OperationTrackingRequestV2Dto OperationTrackingRequestV2Dto

// NewOperationTrackingRequestV2Dto instantiates a new OperationTrackingRequestV2Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationTrackingRequestV2Dto(operationMeta []MetadataAttribute) *OperationTrackingRequestV2Dto {
	this := OperationTrackingRequestV2Dto{}
	this.OperationMeta = operationMeta
	return &this
}

// NewOperationTrackingRequestV2DtoWithDefaults instantiates a new OperationTrackingRequestV2Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationTrackingRequestV2DtoWithDefaults() *OperationTrackingRequestV2Dto {
	this := OperationTrackingRequestV2Dto{}
	return &this
}

// GetOperationMeta returns the OperationMeta field value
func (o *OperationTrackingRequestV2Dto) GetOperationMeta() []MetadataAttribute {
	if o == nil {
		var ret []MetadataAttribute
		return ret
	}

	return o.OperationMeta
}

// GetOperationMetaOk returns a tuple with the OperationMeta field value
// and a boolean to check if the value has been set.
func (o *OperationTrackingRequestV2Dto) GetOperationMetaOk() ([]MetadataAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperationMeta, true
}

// SetOperationMeta sets field value
func (o *OperationTrackingRequestV2Dto) SetOperationMeta(v []MetadataAttribute) {
	o.OperationMeta = v
}

func (o OperationTrackingRequestV2Dto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationTrackingRequestV2Dto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operationMeta"] = o.OperationMeta
	return toSerialize, nil
}

func (o *OperationTrackingRequestV2Dto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operationMeta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationTrackingRequestV2Dto := _OperationTrackingRequestV2Dto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationTrackingRequestV2Dto)

	if err != nil {
		return err
	}

	*o = OperationTrackingRequestV2Dto(varOperationTrackingRequestV2Dto)

	return err
}

type NullableOperationTrackingRequestV2Dto struct {
	value *OperationTrackingRequestV2Dto
	isSet bool
}

func (v NullableOperationTrackingRequestV2Dto) Get() *OperationTrackingRequestV2Dto {
	return v.value
}

func (v *NullableOperationTrackingRequestV2Dto) Set(val *OperationTrackingRequestV2Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationTrackingRequestV2Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationTrackingRequestV2Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationTrackingRequestV2Dto(val *OperationTrackingRequestV2Dto) *NullableOperationTrackingRequestV2Dto {
	return &NullableOperationTrackingRequestV2Dto{value: val, isSet: true}
}

func (v NullableOperationTrackingRequestV2Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationTrackingRequestV2Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


