/*
Cryptography Provider v2 API

REST API for implementations of custom v2 Cryptography Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EncryptedKeyMaterialV2Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EncryptedKeyMaterialV2Dto{}

// EncryptedKeyMaterialV2Dto Protected key material as a DER-encoded PKCS#8 `EncryptedPrivateKeyInfo`, protected with PBES2 using PBKDF2-HMAC-SHA256 and AES-256-CBC. See `encryptedPrivateKeyInfo` for the full profile.
type EncryptedKeyMaterialV2Dto struct {
	// Base64-encoded DER PKCS#8 `EncryptedPrivateKeyInfo` (RFC 5958). The decrypted plaintext is `PrivateKeyInfo` syntax whose algorithm identifier states the key kind.  Exactly one protection profile is accepted, and it must be readable from the envelope alone:  - **Scheme** — PBES2 (RFC 8018) with PBKDF2-HMAC-SHA256 as the key derivation, its parameters `NULL` as   RFC 8018 requires, and AES-256-CBC as the encryption. - **Salt** — at least 16 bytes, from a cryptographically secure random source, never reused. - **Initialisation vector** — exactly 16 bytes, from a cryptographically secure random source, never reused. - **Iterations** — between 100000 and 10000000; 600000 is recommended. - **Key length** — either absent, which the encryption scheme already implies, or exactly 32. Absent is the   common case: OpenSSL does not emit it. - **Ciphertext** — a non-empty whole number of 16-byte blocks. - **Total length** — at most 65536 bytes of DER.  Every way an envelope can fall short of this — bytes longer than the maximum, bytes that are not canonical DER, and a canonical envelope outside the profile — is refused as a field validation failure on this field (`VALIDATION_FAILED`), so a caller is told which rule it broke rather than that its body was unreadable.  The profile carries no integrity protection of its own, so a successful decrypt is evidence about the passphrase, not about who produced the envelope. 
	EncryptedPrivateKeyInfo string `json:"encryptedPrivateKeyInfo"`
}

type _EncryptedKeyMaterialV2Dto EncryptedKeyMaterialV2Dto

// NewEncryptedKeyMaterialV2Dto instantiates a new EncryptedKeyMaterialV2Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEncryptedKeyMaterialV2Dto(encryptedPrivateKeyInfo string) *EncryptedKeyMaterialV2Dto {
	this := EncryptedKeyMaterialV2Dto{}
	this.EncryptedPrivateKeyInfo = encryptedPrivateKeyInfo
	return &this
}

// NewEncryptedKeyMaterialV2DtoWithDefaults instantiates a new EncryptedKeyMaterialV2Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEncryptedKeyMaterialV2DtoWithDefaults() *EncryptedKeyMaterialV2Dto {
	this := EncryptedKeyMaterialV2Dto{}
	return &this
}

// GetEncryptedPrivateKeyInfo returns the EncryptedPrivateKeyInfo field value
func (o *EncryptedKeyMaterialV2Dto) GetEncryptedPrivateKeyInfo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EncryptedPrivateKeyInfo
}

// GetEncryptedPrivateKeyInfoOk returns a tuple with the EncryptedPrivateKeyInfo field value
// and a boolean to check if the value has been set.
func (o *EncryptedKeyMaterialV2Dto) GetEncryptedPrivateKeyInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncryptedPrivateKeyInfo, true
}

// SetEncryptedPrivateKeyInfo sets field value
func (o *EncryptedKeyMaterialV2Dto) SetEncryptedPrivateKeyInfo(v string) {
	o.EncryptedPrivateKeyInfo = v
}

func (o EncryptedKeyMaterialV2Dto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EncryptedKeyMaterialV2Dto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["encryptedPrivateKeyInfo"] = o.EncryptedPrivateKeyInfo
	return toSerialize, nil
}

func (o *EncryptedKeyMaterialV2Dto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"encryptedPrivateKeyInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEncryptedKeyMaterialV2Dto := _EncryptedKeyMaterialV2Dto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEncryptedKeyMaterialV2Dto)

	if err != nil {
		return err
	}

	*o = EncryptedKeyMaterialV2Dto(varEncryptedKeyMaterialV2Dto)

	return err
}

type NullableEncryptedKeyMaterialV2Dto struct {
	value *EncryptedKeyMaterialV2Dto
	isSet bool
}

func (v NullableEncryptedKeyMaterialV2Dto) Get() *EncryptedKeyMaterialV2Dto {
	return v.value
}

func (v *NullableEncryptedKeyMaterialV2Dto) Set(val *EncryptedKeyMaterialV2Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableEncryptedKeyMaterialV2Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableEncryptedKeyMaterialV2Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncryptedKeyMaterialV2Dto(val *EncryptedKeyMaterialV2Dto) *NullableEncryptedKeyMaterialV2Dto {
	return &NullableEncryptedKeyMaterialV2Dto{value: val, isSet: true}
}

func (v NullableEncryptedKeyMaterialV2Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncryptedKeyMaterialV2Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


