/*
Cryptography Provider v2 API

REST API for implementations of custom v2 Cryptography Provider

API version: 2.20.0-SNAPSHOT
Contact: ilm@omnitrust.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignDataRequestV2Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignDataRequestV2Dto{}

// SignDataRequestV2Dto struct for SignDataRequestV2Dto
type SignDataRequestV2Dto struct {
	// Token attributes
	TokenAttributes []RequestAttribute `json:"tokenAttributes"`
	// Token profile attributes
	TokenProfileAttributes []RequestAttribute `json:"tokenProfileAttributes"`
	// Key usages selected on the token profile
	KeyUsages []KeyUsage `json:"keyUsages"`
	// Connector-defined metadata identifying the key, as returned when the key was created, listed or identified. Supply the metadata unchanged in subsequent requests for the key. Metadata must identify the key durably—it must remain valid across connector restarts and sessions; ephemeral handles must not be used.
	KeyMeta []MetadataAttribute `json:"keyMeta"`
	// Caller-selected execution mode. The connector must not switch modes implicitly.
	ExecutionMode OperationExecutionMode `json:"executionMode"`
	// Signature attributes
	SignatureAttributes []RequestAttribute `json:"signatureAttributes"`
	// Data to be signed
	Data []SignatureDataV2Dto `json:"data"`
}

type _SignDataRequestV2Dto SignDataRequestV2Dto

// NewSignDataRequestV2Dto instantiates a new SignDataRequestV2Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignDataRequestV2Dto(tokenAttributes []RequestAttribute, tokenProfileAttributes []RequestAttribute, keyUsages []KeyUsage, keyMeta []MetadataAttribute, executionMode OperationExecutionMode, signatureAttributes []RequestAttribute, data []SignatureDataV2Dto) *SignDataRequestV2Dto {
	this := SignDataRequestV2Dto{}
	this.TokenAttributes = tokenAttributes
	this.TokenProfileAttributes = tokenProfileAttributes
	this.KeyUsages = keyUsages
	this.KeyMeta = keyMeta
	this.ExecutionMode = executionMode
	this.SignatureAttributes = signatureAttributes
	this.Data = data
	return &this
}

// NewSignDataRequestV2DtoWithDefaults instantiates a new SignDataRequestV2Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignDataRequestV2DtoWithDefaults() *SignDataRequestV2Dto {
	this := SignDataRequestV2Dto{}
	return &this
}

// GetTokenAttributes returns the TokenAttributes field value
func (o *SignDataRequestV2Dto) GetTokenAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.TokenAttributes
}

// GetTokenAttributesOk returns a tuple with the TokenAttributes field value
// and a boolean to check if the value has been set.
func (o *SignDataRequestV2Dto) GetTokenAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenAttributes, true
}

// SetTokenAttributes sets field value
func (o *SignDataRequestV2Dto) SetTokenAttributes(v []RequestAttribute) {
	o.TokenAttributes = v
}

// GetTokenProfileAttributes returns the TokenProfileAttributes field value
func (o *SignDataRequestV2Dto) GetTokenProfileAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.TokenProfileAttributes
}

// GetTokenProfileAttributesOk returns a tuple with the TokenProfileAttributes field value
// and a boolean to check if the value has been set.
func (o *SignDataRequestV2Dto) GetTokenProfileAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenProfileAttributes, true
}

// SetTokenProfileAttributes sets field value
func (o *SignDataRequestV2Dto) SetTokenProfileAttributes(v []RequestAttribute) {
	o.TokenProfileAttributes = v
}

// GetKeyUsages returns the KeyUsages field value
func (o *SignDataRequestV2Dto) GetKeyUsages() []KeyUsage {
	if o == nil {
		var ret []KeyUsage
		return ret
	}

	return o.KeyUsages
}

// GetKeyUsagesOk returns a tuple with the KeyUsages field value
// and a boolean to check if the value has been set.
func (o *SignDataRequestV2Dto) GetKeyUsagesOk() ([]KeyUsage, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyUsages, true
}

// SetKeyUsages sets field value
func (o *SignDataRequestV2Dto) SetKeyUsages(v []KeyUsage) {
	o.KeyUsages = v
}

// GetKeyMeta returns the KeyMeta field value
func (o *SignDataRequestV2Dto) GetKeyMeta() []MetadataAttribute {
	if o == nil {
		var ret []MetadataAttribute
		return ret
	}

	return o.KeyMeta
}

// GetKeyMetaOk returns a tuple with the KeyMeta field value
// and a boolean to check if the value has been set.
func (o *SignDataRequestV2Dto) GetKeyMetaOk() ([]MetadataAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyMeta, true
}

// SetKeyMeta sets field value
func (o *SignDataRequestV2Dto) SetKeyMeta(v []MetadataAttribute) {
	o.KeyMeta = v
}

// GetExecutionMode returns the ExecutionMode field value
func (o *SignDataRequestV2Dto) GetExecutionMode() OperationExecutionMode {
	if o == nil {
		var ret OperationExecutionMode
		return ret
	}

	return o.ExecutionMode
}

// GetExecutionModeOk returns a tuple with the ExecutionMode field value
// and a boolean to check if the value has been set.
func (o *SignDataRequestV2Dto) GetExecutionModeOk() (*OperationExecutionMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionMode, true
}

// SetExecutionMode sets field value
func (o *SignDataRequestV2Dto) SetExecutionMode(v OperationExecutionMode) {
	o.ExecutionMode = v
}

// GetSignatureAttributes returns the SignatureAttributes field value
func (o *SignDataRequestV2Dto) GetSignatureAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.SignatureAttributes
}

// GetSignatureAttributesOk returns a tuple with the SignatureAttributes field value
// and a boolean to check if the value has been set.
func (o *SignDataRequestV2Dto) GetSignatureAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignatureAttributes, true
}

// SetSignatureAttributes sets field value
func (o *SignDataRequestV2Dto) SetSignatureAttributes(v []RequestAttribute) {
	o.SignatureAttributes = v
}

// GetData returns the Data field value
func (o *SignDataRequestV2Dto) GetData() []SignatureDataV2Dto {
	if o == nil {
		var ret []SignatureDataV2Dto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SignDataRequestV2Dto) GetDataOk() ([]SignatureDataV2Dto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SignDataRequestV2Dto) SetData(v []SignatureDataV2Dto) {
	o.Data = v
}

func (o SignDataRequestV2Dto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignDataRequestV2Dto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tokenAttributes"] = o.TokenAttributes
	toSerialize["tokenProfileAttributes"] = o.TokenProfileAttributes
	toSerialize["keyUsages"] = o.KeyUsages
	toSerialize["keyMeta"] = o.KeyMeta
	toSerialize["executionMode"] = o.ExecutionMode
	toSerialize["signatureAttributes"] = o.SignatureAttributes
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SignDataRequestV2Dto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tokenAttributes",
		"tokenProfileAttributes",
		"keyUsages",
		"keyMeta",
		"executionMode",
		"signatureAttributes",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignDataRequestV2Dto := _SignDataRequestV2Dto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignDataRequestV2Dto)

	if err != nil {
		return err
	}

	*o = SignDataRequestV2Dto(varSignDataRequestV2Dto)

	return err
}

type NullableSignDataRequestV2Dto struct {
	value *SignDataRequestV2Dto
	isSet bool
}

func (v NullableSignDataRequestV2Dto) Get() *SignDataRequestV2Dto {
	return v.value
}

func (v *NullableSignDataRequestV2Dto) Set(val *SignDataRequestV2Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableSignDataRequestV2Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableSignDataRequestV2Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignDataRequestV2Dto(val *SignDataRequestV2Dto) *NullableSignDataRequestV2Dto {
	return &NullableSignDataRequestV2Dto{value: val, isSet: true}
}

func (v NullableSignDataRequestV2Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignDataRequestV2Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


