/*
Authority Provider Legacy API

REST API for implementations of custom Legacy Authority Provider

API version: 2.18.1-SNAPSHOT
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the MappedField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MappedField{}

// MappedField Describes a single target field within an object; concrete type is determined by fieldType
type MappedField struct {
	// Field type, determines the concrete subtype
	FieldType FieldType `json:"fieldType"`
	// Ordering index for fields of the same type (e.g. RDN components); ascending
	Order *int32 `json:"order,omitempty"`
	// Provenance of the value when reconciling CSR vs platform-projected values
	Source *FieldSource `json:"source,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MappedField MappedField

// NewMappedField instantiates a new MappedField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMappedField(fieldType FieldType) *MappedField {
	this := MappedField{}
	this.FieldType = fieldType
	return &this
}

// NewMappedFieldWithDefaults instantiates a new MappedField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMappedFieldWithDefaults() *MappedField {
	this := MappedField{}
	return &this
}

// GetFieldType returns the FieldType field value
func (o *MappedField) GetFieldType() FieldType {
	if o == nil {
		var ret FieldType
		return ret
	}

	return o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value
// and a boolean to check if the value has been set.
func (o *MappedField) GetFieldTypeOk() (*FieldType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldType, true
}

// SetFieldType sets field value
func (o *MappedField) SetFieldType(v FieldType) {
	o.FieldType = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *MappedField) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MappedField) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *MappedField) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *MappedField) SetOrder(v int32) {
	o.Order = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *MappedField) GetSource() FieldSource {
	if o == nil || IsNil(o.Source) {
		var ret FieldSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MappedField) GetSourceOk() (*FieldSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *MappedField) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given FieldSource and assigns it to the Source field.
func (o *MappedField) SetSource(v FieldSource) {
	o.Source = &v
}

func (o MappedField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MappedField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fieldType"] = o.FieldType
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MappedField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fieldType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMappedField := _MappedField{}

	err = json.Unmarshal(data, &varMappedField)

	if err != nil {
		return err
	}

	*o = MappedField(varMappedField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fieldType")
		delete(additionalProperties, "order")
		delete(additionalProperties, "source")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMappedField struct {
	value *MappedField
	isSet bool
}

func (v NullableMappedField) Get() *MappedField {
	return v.value
}

func (v *NullableMappedField) Set(val *MappedField) {
	v.value = val
	v.isSet = true
}

func (v NullableMappedField) IsSet() bool {
	return v.isSet
}

func (v *NullableMappedField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMappedField(val *MappedField) *NullableMappedField {
	return &NullableMappedField{value: val, isSet: true}
}

func (v NullableMappedField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMappedField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


