/*
Authority Provider v2 API

REST API for implementations of custom v2 Authority Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CaCertificatesResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaCertificatesResponseDto{}

// CaCertificatesResponseDto struct for CaCertificatesResponseDto
type CaCertificatesResponseDto struct {
	// List of Certificates
	Certificates []CertificateDataResponseDto `json:"certificates"`
}

type _CaCertificatesResponseDto CaCertificatesResponseDto

// NewCaCertificatesResponseDto instantiates a new CaCertificatesResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaCertificatesResponseDto(certificates []CertificateDataResponseDto) *CaCertificatesResponseDto {
	this := CaCertificatesResponseDto{}
	this.Certificates = certificates
	return &this
}

// NewCaCertificatesResponseDtoWithDefaults instantiates a new CaCertificatesResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaCertificatesResponseDtoWithDefaults() *CaCertificatesResponseDto {
	this := CaCertificatesResponseDto{}
	return &this
}

// GetCertificates returns the Certificates field value
func (o *CaCertificatesResponseDto) GetCertificates() []CertificateDataResponseDto {
	if o == nil {
		var ret []CertificateDataResponseDto
		return ret
	}

	return o.Certificates
}

// GetCertificatesOk returns a tuple with the Certificates field value
// and a boolean to check if the value has been set.
func (o *CaCertificatesResponseDto) GetCertificatesOk() ([]CertificateDataResponseDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Certificates, true
}

// SetCertificates sets field value
func (o *CaCertificatesResponseDto) SetCertificates(v []CertificateDataResponseDto) {
	o.Certificates = v
}

func (o CaCertificatesResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaCertificatesResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certificates"] = o.Certificates
	return toSerialize, nil
}

func (o *CaCertificatesResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certificates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCaCertificatesResponseDto := _CaCertificatesResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCaCertificatesResponseDto)

	if err != nil {
		return err
	}

	*o = CaCertificatesResponseDto(varCaCertificatesResponseDto)

	return err
}

type NullableCaCertificatesResponseDto struct {
	value *CaCertificatesResponseDto
	isSet bool
}

func (v NullableCaCertificatesResponseDto) Get() *CaCertificatesResponseDto {
	return v.value
}

func (v *NullableCaCertificatesResponseDto) Set(val *CaCertificatesResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCaCertificatesResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCaCertificatesResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaCertificatesResponseDto(val *CaCertificatesResponseDto) *NullableCaCertificatesResponseDto {
	return &NullableCaCertificatesResponseDto{value: val, isSet: true}
}

func (v NullableCaCertificatesResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaCertificatesResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


