/*
Compliance Provider API

REST API for implementations of custom Compliance Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// FunctionGroupCode the model 'FunctionGroupCode'
type FunctionGroupCode string

// List of FunctionGroupCode
const (
	FUNCTIONGROUPCODE_CREDENTIAL_PROVIDER FunctionGroupCode = "credentialProvider"
	FUNCTIONGROUPCODE_LEGACY_AUTHORITY_PROVIDER FunctionGroupCode = "legacyAuthorityProvider"
	FUNCTIONGROUPCODE_AUTHORITY_PROVIDER FunctionGroupCode = "authorityProvider"
	FUNCTIONGROUPCODE_DISCOVERY_PROVIDER FunctionGroupCode = "discoveryProvider"
	FUNCTIONGROUPCODE_ENTITY_PROVIDER FunctionGroupCode = "entityProvider"
	FUNCTIONGROUPCODE_COMPLIANCE_PROVIDER FunctionGroupCode = "complianceProvider"
	FUNCTIONGROUPCODE_COMPLIANCE_PROVIDER_V2 FunctionGroupCode = "complianceProviderV2"
	FUNCTIONGROUPCODE_CRYPTOGRAPHY_PROVIDER FunctionGroupCode = "cryptographyProvider"
	FUNCTIONGROUPCODE_NOTIFICATION_PROVIDER FunctionGroupCode = "notificationProvider"
)

// All allowed values of FunctionGroupCode enum
var AllowedFunctionGroupCodeEnumValues = []FunctionGroupCode{
	"credentialProvider",
	"legacyAuthorityProvider",
	"authorityProvider",
	"discoveryProvider",
	"entityProvider",
	"complianceProvider",
	"complianceProviderV2",
	"cryptographyProvider",
	"notificationProvider",
}

func (v *FunctionGroupCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FunctionGroupCode(value)
	for _, existing := range AllowedFunctionGroupCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FunctionGroupCode", value)
}

// NewFunctionGroupCodeFromValue returns a pointer to a valid FunctionGroupCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFunctionGroupCodeFromValue(v string) (*FunctionGroupCode, error) {
	ev := FunctionGroupCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FunctionGroupCode: valid values are %v", v, AllowedFunctionGroupCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FunctionGroupCode) IsValid() bool {
	for _, existing := range AllowedFunctionGroupCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FunctionGroupCode value
func (v FunctionGroupCode) Ptr() *FunctionGroupCode {
	return &v
}

type NullableFunctionGroupCode struct {
	value *FunctionGroupCode
	isSet bool
}

func (v NullableFunctionGroupCode) Get() *FunctionGroupCode {
	return v.value
}

func (v *NullableFunctionGroupCode) Set(val *FunctionGroupCode) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionGroupCode) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionGroupCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionGroupCode(val *FunctionGroupCode) *NullableFunctionGroupCode {
	return &NullableFunctionGroupCode{value: val, isSet: true}
}

func (v NullableFunctionGroupCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionGroupCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

