/*
Entity Provider API

REST API for implementations of custom Entity Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entity

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// BaseAttributeDtoV3 - Base Attribute definition
type BaseAttributeDtoV3 struct {
	CustomAttributeV3 *CustomAttributeV3
	DataAttributeV3 *DataAttributeV3
	GroupAttributeV3 *GroupAttributeV3
	InfoAttributeV3 *InfoAttributeV3
	MetadataAttributeV3 *MetadataAttributeV3
}

// CustomAttributeV3AsBaseAttributeDtoV3 is a convenience function that returns CustomAttributeV3 wrapped in BaseAttributeDtoV3
func CustomAttributeV3AsBaseAttributeDtoV3(v *CustomAttributeV3) BaseAttributeDtoV3 {
	return BaseAttributeDtoV3{
		CustomAttributeV3: v,
	}
}

// DataAttributeV3AsBaseAttributeDtoV3 is a convenience function that returns DataAttributeV3 wrapped in BaseAttributeDtoV3
func DataAttributeV3AsBaseAttributeDtoV3(v *DataAttributeV3) BaseAttributeDtoV3 {
	return BaseAttributeDtoV3{
		DataAttributeV3: v,
	}
}

// GroupAttributeV3AsBaseAttributeDtoV3 is a convenience function that returns GroupAttributeV3 wrapped in BaseAttributeDtoV3
func GroupAttributeV3AsBaseAttributeDtoV3(v *GroupAttributeV3) BaseAttributeDtoV3 {
	return BaseAttributeDtoV3{
		GroupAttributeV3: v,
	}
}

// InfoAttributeV3AsBaseAttributeDtoV3 is a convenience function that returns InfoAttributeV3 wrapped in BaseAttributeDtoV3
func InfoAttributeV3AsBaseAttributeDtoV3(v *InfoAttributeV3) BaseAttributeDtoV3 {
	return BaseAttributeDtoV3{
		InfoAttributeV3: v,
	}
}

// MetadataAttributeV3AsBaseAttributeDtoV3 is a convenience function that returns MetadataAttributeV3 wrapped in BaseAttributeDtoV3
func MetadataAttributeV3AsBaseAttributeDtoV3(v *MetadataAttributeV3) BaseAttributeDtoV3 {
	return BaseAttributeDtoV3{
		MetadataAttributeV3: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *BaseAttributeDtoV3) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CustomAttributeV3
	err = newStrictDecoder(data).Decode(&dst.CustomAttributeV3)
	if err == nil {
		jsonCustomAttributeV3, _ := json.Marshal(dst.CustomAttributeV3)
		if string(jsonCustomAttributeV3) == "{}" { // empty struct
			dst.CustomAttributeV3 = nil
		} else {
			if err = validator.Validate(dst.CustomAttributeV3); err != nil {
				dst.CustomAttributeV3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomAttributeV3 = nil
	}

	// try to unmarshal data into DataAttributeV3
	err = newStrictDecoder(data).Decode(&dst.DataAttributeV3)
	if err == nil {
		jsonDataAttributeV3, _ := json.Marshal(dst.DataAttributeV3)
		if string(jsonDataAttributeV3) == "{}" { // empty struct
			dst.DataAttributeV3 = nil
		} else {
			if err = validator.Validate(dst.DataAttributeV3); err != nil {
				dst.DataAttributeV3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DataAttributeV3 = nil
	}

	// try to unmarshal data into GroupAttributeV3
	err = newStrictDecoder(data).Decode(&dst.GroupAttributeV3)
	if err == nil {
		jsonGroupAttributeV3, _ := json.Marshal(dst.GroupAttributeV3)
		if string(jsonGroupAttributeV3) == "{}" { // empty struct
			dst.GroupAttributeV3 = nil
		} else {
			if err = validator.Validate(dst.GroupAttributeV3); err != nil {
				dst.GroupAttributeV3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GroupAttributeV3 = nil
	}

	// try to unmarshal data into InfoAttributeV3
	err = newStrictDecoder(data).Decode(&dst.InfoAttributeV3)
	if err == nil {
		jsonInfoAttributeV3, _ := json.Marshal(dst.InfoAttributeV3)
		if string(jsonInfoAttributeV3) == "{}" { // empty struct
			dst.InfoAttributeV3 = nil
		} else {
			if err = validator.Validate(dst.InfoAttributeV3); err != nil {
				dst.InfoAttributeV3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.InfoAttributeV3 = nil
	}

	// try to unmarshal data into MetadataAttributeV3
	err = newStrictDecoder(data).Decode(&dst.MetadataAttributeV3)
	if err == nil {
		jsonMetadataAttributeV3, _ := json.Marshal(dst.MetadataAttributeV3)
		if string(jsonMetadataAttributeV3) == "{}" { // empty struct
			dst.MetadataAttributeV3 = nil
		} else {
			if err = validator.Validate(dst.MetadataAttributeV3); err != nil {
				dst.MetadataAttributeV3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.MetadataAttributeV3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CustomAttributeV3 = nil
		dst.DataAttributeV3 = nil
		dst.GroupAttributeV3 = nil
		dst.InfoAttributeV3 = nil
		dst.MetadataAttributeV3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BaseAttributeDtoV3)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BaseAttributeDtoV3)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BaseAttributeDtoV3) MarshalJSON() ([]byte, error) {
	if src.CustomAttributeV3 != nil {
		return json.Marshal(&src.CustomAttributeV3)
	}

	if src.DataAttributeV3 != nil {
		return json.Marshal(&src.DataAttributeV3)
	}

	if src.GroupAttributeV3 != nil {
		return json.Marshal(&src.GroupAttributeV3)
	}

	if src.InfoAttributeV3 != nil {
		return json.Marshal(&src.InfoAttributeV3)
	}

	if src.MetadataAttributeV3 != nil {
		return json.Marshal(&src.MetadataAttributeV3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BaseAttributeDtoV3) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CustomAttributeV3 != nil {
		return obj.CustomAttributeV3
	}

	if obj.DataAttributeV3 != nil {
		return obj.DataAttributeV3
	}

	if obj.GroupAttributeV3 != nil {
		return obj.GroupAttributeV3
	}

	if obj.InfoAttributeV3 != nil {
		return obj.InfoAttributeV3
	}

	if obj.MetadataAttributeV3 != nil {
		return obj.MetadataAttributeV3
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BaseAttributeDtoV3) GetActualInstanceValue() (interface{}) {
	if obj.CustomAttributeV3 != nil {
		return *obj.CustomAttributeV3
	}

	if obj.DataAttributeV3 != nil {
		return *obj.DataAttributeV3
	}

	if obj.GroupAttributeV3 != nil {
		return *obj.GroupAttributeV3
	}

	if obj.InfoAttributeV3 != nil {
		return *obj.InfoAttributeV3
	}

	if obj.MetadataAttributeV3 != nil {
		return *obj.MetadataAttributeV3
	}

	// all schemas are nil
	return nil
}

type NullableBaseAttributeDtoV3 struct {
	value *BaseAttributeDtoV3
	isSet bool
}

func (v NullableBaseAttributeDtoV3) Get() *BaseAttributeDtoV3 {
	return v.value
}

func (v *NullableBaseAttributeDtoV3) Set(val *BaseAttributeDtoV3) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseAttributeDtoV3) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseAttributeDtoV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseAttributeDtoV3(val *BaseAttributeDtoV3) *NullableBaseAttributeDtoV3 {
	return &NullableBaseAttributeDtoV3{value: val, isSet: true}
}

func (v NullableBaseAttributeDtoV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseAttributeDtoV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


