/*
Entity Provider API

REST API for implementations of custom Entity Provider

API version: 2.17.0
Contact: info@otilm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entity

import (
	"encoding/json"
	"fmt"
)

// checks if the RemoveCertificateRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveCertificateRequestDto{}

// RemoveCertificateRequestDto struct for RemoveCertificateRequestDto
type RemoveCertificateRequestDto struct {
	// Metadata of the Certificate
	CertificateMetadata []MetadataAttribute `json:"certificateMetadata"`
	// List of Location Attributes
	LocationAttributes []RequestAttribute `json:"locationAttributes"`
	AdditionalProperties map[string]interface{}
}

type _RemoveCertificateRequestDto RemoveCertificateRequestDto

// NewRemoveCertificateRequestDto instantiates a new RemoveCertificateRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveCertificateRequestDto(certificateMetadata []MetadataAttribute, locationAttributes []RequestAttribute) *RemoveCertificateRequestDto {
	this := RemoveCertificateRequestDto{}
	this.CertificateMetadata = certificateMetadata
	this.LocationAttributes = locationAttributes
	return &this
}

// NewRemoveCertificateRequestDtoWithDefaults instantiates a new RemoveCertificateRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveCertificateRequestDtoWithDefaults() *RemoveCertificateRequestDto {
	this := RemoveCertificateRequestDto{}
	return &this
}

// GetCertificateMetadata returns the CertificateMetadata field value
func (o *RemoveCertificateRequestDto) GetCertificateMetadata() []MetadataAttribute {
	if o == nil {
		var ret []MetadataAttribute
		return ret
	}

	return o.CertificateMetadata
}

// GetCertificateMetadataOk returns a tuple with the CertificateMetadata field value
// and a boolean to check if the value has been set.
func (o *RemoveCertificateRequestDto) GetCertificateMetadataOk() ([]MetadataAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertificateMetadata, true
}

// SetCertificateMetadata sets field value
func (o *RemoveCertificateRequestDto) SetCertificateMetadata(v []MetadataAttribute) {
	o.CertificateMetadata = v
}

// GetLocationAttributes returns the LocationAttributes field value
func (o *RemoveCertificateRequestDto) GetLocationAttributes() []RequestAttribute {
	if o == nil {
		var ret []RequestAttribute
		return ret
	}

	return o.LocationAttributes
}

// GetLocationAttributesOk returns a tuple with the LocationAttributes field value
// and a boolean to check if the value has been set.
func (o *RemoveCertificateRequestDto) GetLocationAttributesOk() ([]RequestAttribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.LocationAttributes, true
}

// SetLocationAttributes sets field value
func (o *RemoveCertificateRequestDto) SetLocationAttributes(v []RequestAttribute) {
	o.LocationAttributes = v
}

func (o RemoveCertificateRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveCertificateRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certificateMetadata"] = o.CertificateMetadata
	toSerialize["locationAttributes"] = o.LocationAttributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RemoveCertificateRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certificateMetadata",
		"locationAttributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveCertificateRequestDto := _RemoveCertificateRequestDto{}

	err = json.Unmarshal(data, &varRemoveCertificateRequestDto)

	if err != nil {
		return err
	}

	*o = RemoveCertificateRequestDto(varRemoveCertificateRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "certificateMetadata")
		delete(additionalProperties, "locationAttributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRemoveCertificateRequestDto struct {
	value *RemoveCertificateRequestDto
	isSet bool
}

func (v NullableRemoveCertificateRequestDto) Get() *RemoveCertificateRequestDto {
	return v.value
}

func (v *NullableRemoveCertificateRequestDto) Set(val *RemoveCertificateRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveCertificateRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveCertificateRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveCertificateRequestDto(val *RemoveCertificateRequestDto) *NullableRemoveCertificateRequestDto {
	return &NullableRemoveCertificateRequestDto{value: val, isSet: true}
}

func (v NullableRemoveCertificateRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveCertificateRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


